// Every app KherveOS knows about. Apps load lazily: their code is only
// downloaded the first time a window of theirs opens.

import {
  Atom, Bird, Blocks, FlaskConical, Rocket, Spade, Presentation, BookMarked, BookOpen, BrickWall, Castle, CircleDot, Code2, FileText, Folder, Globe, Image, Mail, MessageCircle, NotebookPen, Orbit, Palette,
  Settings, Sheet, Sigma, Sparkles, SquareTerminal,
} from 'lucide-react'
import type { AppManifest } from './types'

export const APPS: AppManifest[] = [
  {
    id: 'files',
    name: 'Files',
    icon: Folder,
    color: '#3b82f6',
    brand: { label: 'KFiles', from: '#5cb1ff', to: '#1660d4', deep: ['#2d74d9', '#103a85'] },
    category: 'system',
    group: 'Tools',
    description: 'Browse, organise, upload and download your files',
    load: () => import('@/apps/files/Files'),
    defaultSize: { w: 860, h: 540 },
    minSize: { w: 420, h: 300 },
    desktop: true,
  },
  {
    id: 'khervepdf',
    name: 'KhervePDF',
    icon: FileText,
    color: '#d6342c',
    image: '/icons/apps/khervepdf.png',
    brand: { label: 'Kpdf', from: '#ff6b5e', to: '#c41f1f' },
    category: 'kherve',
    group: 'Office',
    description: 'View, annotate and edit PDFs',
    load: () => import('@/apps/khervepdf/KhervePDF'),
    defaultSize: { w: 980, h: 700 },
    minSize: { w: 480, h: 360 },
    fileTypes: ['.pdf'],
    // Like the desktop app: PDFs opened from Files arrive as tabs in one window.
    singleton: true,
  },
  {
    id: 'khervesheet',
    name: 'KherveSheet',
    icon: Sheet,
    color: '#1f9d55',
    image: '/icons/apps/khervesheet.png',
    brand: { label: 'KSheet', from: '#3ccf6e', to: '#138a3c' },
    category: 'kherve',
    group: 'Office',
    description: 'Spreadsheets with ~290 functions, Python (=PY) cells and charts',
    load: () => import('@/apps/khervesheet/KherveSheet'),
    defaultSize: { w: 1180, h: 760 },
    minSize: { w: 560, h: 380 },
    fileTypes: ['.ksheet', '.xlsx', '.xlsm', '.csv'],
  },
  {
    id: 'khervepaint',
    name: 'KhervePaint',
    icon: Palette,
    color: '#e0559b',
    image: '/icons/apps/khervepaint.png',
    brand: { label: 'KPaint', from: '#ff9fcf', to: '#c2307a' },
    category: 'kherve',
    group: 'Office',
    description: 'Raster + vector drawing: figures, diagrams and symbol libraries',
    load: () => import('@/apps/khervepaint/KhervePaint'),
    defaultSize: { w: 1200, h: 800 },
    minSize: { w: 760, h: 480 },
    fileTypes: ['.kpaint'],
  },
  {
    id: 'khervefitting',
    name: 'KherveFitting',
    icon: Sigma,
    color: '#2563eb',
    image: '/icons/apps/khervefitting.png',
    brand: { label: 'KFit', from: '#7fb0ff', to: '#1d4ed8' },
    category: 'kherve',
    group: 'Science',
    description: 'XPS peak fitting: backgrounds, peak models, constraints and atomic %',
    load: () => import('@/apps/khervefitting/KherveFitting'),
    defaultSize: { w: 1485, h: 820 },
    minSize: { w: 760, h: 520 },
    // .xlsx stays with KherveSheet; KherveFitting opens its workbooks from its own File menu.
    fileTypes: ['.vms'],
  },
  {
    id: 'kherveslide',
    name: 'KherveSlide',
    icon: Presentation,
    color: '#e8812b',
    image: '/icons/apps/kherveslide.png',
    brand: { label: 'KSlide', from: '#ffa04a', to: '#d9631a' },
    category: 'kherve',
    group: 'Office',
    description: 'Slides designed freely, typeset with LaTeX beamer',
    load: () => import('@/apps/kherveslide/KherveSlide'),
    defaultSize: { w: 1200, h: 760 },
    minSize: { w: 640, h: 420 },
    fileTypes: ['.kslide'],
  },
  {
    id: 'khervelab',
    name: 'KherveLAB',
    icon: FlaskConical,
    color: '#22b357',
    image: '/icons/apps/khervelab.png',
    brand: { label: 'KLab', from: '#3ccf6e', to: '#138a3c' },
    category: 'kherve',
    group: 'Science',
    description: 'Book the lab’s instruments together: calendars, approval and rates',
    load: () => import('@/apps/khervelab/KherveLAB'),
    defaultSize: { w: 1180, h: 760 },
    minSize: { w: 760, h: 480 },
    singleton: true,
  },
  {
    id: 'khervenote',
    name: 'KherveNote',
    icon: NotebookPen,
    color: '#2e9e5b',
    image: '/icons/apps/khervenote.png',
    brand: { label: 'KNote', from: '#3fbf73', to: '#1d7a45' },
    category: 'kherve',
    group: 'Office',
    description: 'Live notes for lectures and talks, with the speech beside them, to LaTeX/PDF',
    load: () => import('@/apps/khervenote/KherveNote'),
    defaultSize: { w: 1200, h: 760 },
    minSize: { w: 720, h: 420 },
    fileTypes: ['.knote'],
    singleton: true,
  },
  {
    id: 'khervepy',
    name: 'KhervePY',
    icon: Code2,
    color: '#3b6fd4',
    image: '/icons/apps/khervepy.png',
    brand: { label: 'KPy', from: '#4a4f5a', to: '#1d2026' },
    category: 'kherve',
    group: 'Development',
    description: 'A light Python IDE with Git and GitHub',
    load: () => import('@/apps/khervepy/KhervePY'),
    defaultSize: { w: 1040, h: 700 },
    minSize: { w: 520, h: 360 },
    fileTypes: ['.py'],
  },
  {
    id: 'khervetex',
    name: 'KherveTeX',
    icon: Sigma,
    color: '#1f6fd6',
    image: '/icons/apps/khervetex.png',
    brand: { label: 'KTeX', from: '#3d8bff', to: '#1554c4' },
    category: 'kherve',
    group: 'Office',
    description: 'WYSIWYG documents typeset with LaTeX',
    load: () => import('@/apps/khervetex/KherveTeX'),
    defaultSize: { w: 1100, h: 720 },
    minSize: { w: 560, h: 380 },
    fileTypes: ['.ktex', '.ktexz', '.kdocz'],
  },
  {
    id: 'kherveref',
    name: 'KherveRef',
    icon: BookMarked,
    color: '#0f8f7a',
    image: '/icons/apps/kherveref.png',
    brand: { label: 'Kref', from: '#2bb39b', to: '#0b6e5e' },
    category: 'kherve',
    group: 'Office',
    description: 'Your references, from PDFs to BibLaTeX',
    load: () => import('@/apps/kherveref/KherveRef'),
    defaultSize: { w: 1100, h: 700 },
    minSize: { w: 560, h: 380 },
    fileTypes: ['.kref', '.bib'],
  },
  {
    id: 'kherveai',
    name: 'KherveAI',
    icon: Sparkles,
    color: '#22b357',
    brand: { label: 'KAI', from: '#3ddc84', to: '#127a3c' },
    category: 'kherve',
    group: 'Tools',
    description: 'Chat with AI — Ollama on this computer, Claude or ChatGPT — and let it work in KherveOS',
    load: () => import('@/apps/kherveai/KherveAI'),
    defaultSize: { w: 900, h: 640 },
    minSize: { w: 420, h: 360 },
    singleton: true,
  },
  {
    id: 'notepad',
    name: 'Notepad',
    icon: NotebookPen,
    color: '#0ea5e9',
    brand: { label: 'KText', from: '#ffffff', to: '#dcd6cb', fg: '#2a2520', glyph: '#d12f2f', deep: ['#6b635a', '#2c2823'], deepGlyph: '#ff7a6b' },
    category: 'system',
    group: 'Tools',
    description: 'Edit text, Markdown, Python and other plain-text files',
    load: () => import('@/apps/notepad/Notepad'),
    defaultSize: { w: 760, h: 520 },
    minSize: { w: 360, h: 240 },
    fileTypes: ['.txt', '.md', '.py', '.json', '.csv', '.js', '.ts', '.html', '.css', '.tex', '.bib', '.yml', '.yaml', '.xml', '.log', '.ini', '.toml', '.sh', ''],
    desktop: true,
  },
  {
    id: 'terminal',
    name: 'Terminal',
    icon: SquareTerminal,
    color: '#334155',
    brand: { label: 'KTerm', from: '#4a505b', to: '#121418', glyph: '#3ddc84', deep: ['#3d424b', '#0f1114'], deepGlyph: '#3ddc84' },
    category: 'system',
    group: 'Tools',
    description: 'A shell over your drive, with Python built in',
    load: () => import('@/apps/terminal/Terminal'),
    defaultSize: { w: 760, h: 460 },
    minSize: { w: 380, h: 220 },
    translucent: true,
    desktop: true,
  },
  {
    id: 'viewer',
    name: 'Viewer',
    icon: Image,
    color: '#14b8a6',
    brand: { label: 'KView', from: '#4ce3aa', to: '#0b8f62', deep: ['#1aa877', '#0a5a40'] },
    category: 'system',
    group: 'Tools',
    description: 'Look at pictures and PDFs',
    load: () => import('@/apps/viewer/Viewer'),
    defaultSize: { w: 820, h: 600 },
    minSize: { w: 320, h: 240 },
    fileTypes: ['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg', '.bmp', '.ico', '.pdf'],
  },
  {
    id: 'settings',
    name: 'Settings',
    icon: Settings,
    color: '#64748b',
    brand: { label: 'KSet', from: '#a7afba', to: '#4b5462', deep: ['#6e7784', '#323842'] },
    category: 'system',
    group: 'Tools',
    description: 'Themes, wallpaper, storage and server',
    load: () => import('@/apps/settings/Settings'),
    defaultSize: { w: 720, h: 520 },
    minSize: { w: 480, h: 360 },
    singleton: true,
  },
  {
    id: 'khervebook',
    name: 'KherveBook',
    icon: BookOpen,
    color: '#f59e0b',
    image: '/icons/apps/khervebook.png',
    brand: { label: 'KBook', from: '#ffcc66', to: '#e08a12', deep: ['#d48d17', '#7f4a06'] },
    category: 'kherve',
    group: 'Science',
    description: 'Notebooks with Python, Markdown, LaTeX, sheet, drawing and JavaScript cells',
    load: () => import('@/apps/khervebook/KherveBook'),
    defaultSize: { w: 1280, h: 860 },
    minSize: { w: 480, h: 320 },
    fileTypes: ['.kbook', '.ipynb'],
    desktop: true,
  },
  {
    id: 'khervedb',
    name: 'KherveDB',
    icon: Atom,
    color: '#2fa866',
    image: '/icons/apps/khervedb.png',
    brand: { label: 'Kdb', from: '#8ee8b0', to: '#2fa866' },
    category: 'kherve',
    group: 'Science',
    description: 'NIST XPS binding energies with a periodic-table browser',
    load: () => import('@/apps/khervedb/KherveDB'),
    defaultSize: { w: 1100, h: 760 },
    minSize: { w: 720, h: 520 },
  },
  {
    id: 'khervemol',
    name: 'KherveMol',
    icon: FlaskConical,
    color: '#e6bd44',
    image: '/icons/apps/khervemol.png',
    brand: { label: 'KMol', from: '#ffe27a', to: '#e6bd44', fg: '#2b2b2b' },
    category: 'kherve',
    group: 'Science',
    description: 'Molecules and crystals in 3D and 2D: 700 molecules, 120 crystals, surfaces, nanotubes, polymers, reactions',
    load: () => import('@/apps/khervemol/KherveMol'),
    defaultSize: { w: 1240, h: 820 },
    minSize: { w: 760, h: 520 },
    fileTypes: ['.kmol', '.mol', '.sdf', '.pdb', '.xyz', '.cif'],
  },
  {
    id: 'browser',
    name: 'Browser',
    icon: Globe,
    color: '#10b981',
    brand: { label: 'KWeb', from: '#4fd6ff', to: '#0874b8', deep: ['#1590c7', '#094a74'] },
    category: 'internet',
    group: 'Internet',
    description: 'Browse the web inside KherveOS',
    load: () => import('@/apps/browser/Browser'),
    defaultSize: { w: 1000, h: 680 },
    minSize: { w: 420, h: 300 },
    fileTypes: ['.html', '.htm'],
    desktop: true,
  },
  {
    id: 'messages',
    name: 'Messages',
    icon: MessageCircle,
    color: '#8b5cf6',
    brand: { label: 'KChat', from: '#b892ff', to: '#6531d6', deep: ['#7b4fe0', '#3a1c90'] },
    category: 'internet',
    group: 'Internet',
    description: 'Chat with people on your KherveOS server',
    load: () => import('@/apps/messages/Messages'),
    defaultSize: { w: 860, h: 580 },
    minSize: { w: 420, h: 360 },
    singleton: true,
    desktop: true,
  },
  {
    id: 'email',
    name: 'Email',
    icon: Mail,
    color: '#ef4444',
    brand: { label: 'KMail', from: '#ff8f70', to: '#d92c2c', deep: ['#de432f', '#871a12'] },
    category: 'internet',
    group: 'Internet',
    description: 'Read and send email from your own accounts',
    load: () => import('@/apps/email/Email'),
    defaultSize: { w: 1040, h: 660 },
    minSize: { w: 560, h: 380 },
    singleton: true,
    desktop: true,
  },
  // Little arcade games: small, fixed-size windows like the classic Mac games.
  {
    id: 'tetris',
    name: 'Tetris',
    icon: Blocks,
    color: '#22b357',
    brand: { label: 'Tetris', from: '#8ef0a8', to: '#1d8f46' },
    category: 'games',
    group: 'Games',
    description: 'Stack the falling blocks and clear lines',
    load: () => import('@/apps/minigames/Tetris'),
    defaultSize: { w: 450, h: 640 },
    minSize: { w: 360, h: 520 },
    fixedSize: true,
  },
  {
    id: 'breakout',
    name: 'Breakout',
    icon: BrickWall,
    color: '#ff9b2f',
    brand: { label: 'Breakout', from: '#ffc77a', to: '#d9701a' },
    category: 'games',
    group: 'Games',
    description: 'Knock out every brick with the ball',
    load: () => import('@/apps/minigames/Breakout'),
    defaultSize: { w: 644, h: 540 },
    minSize: { w: 520, h: 440 },
    fixedSize: true,
  },
  {
    id: 'pinball',
    name: 'Pinball',
    icon: CircleDot,
    color: '#ff4fd8',
    brand: { label: 'Pinball', from: '#ff9ce9', to: '#c21fa0' },
    category: 'games',
    group: 'Games',
    description: 'Flippers, bumpers and a plunger: keep the ball in play',
    load: () => import('@/apps/minigames/Pinball'),
    defaultSize: { w: 470, h: 720 },
    minSize: { w: 400, h: 620 },
    fixedSize: true,
  },
  {
    id: 'asteroids',
    name: 'Meteor Smash',
    icon: Rocket,
    color: '#ffd27a',
    brand: { label: 'Meteor', from: '#ffe7b0', to: '#d99a2b' },
    category: 'games',
    group: 'Games',
    description: 'Steer your ship and blast the meteors to pieces',
    load: () => import('@/apps/minigames/Asteroids'),
    defaultSize: { w: 804, h: 540 },
    minSize: { w: 684, h: 450 },
    fixedSize: true,
  },
  {
    id: 'flappy',
    name: 'Flappy Khervey',
    icon: Bird,
    color: '#ffd700',
    brand: { label: 'Flappy', from: '#fff07a', to: '#e0a800' },
    category: 'games',
    group: 'Games',
    description: 'Flap through the pipes and shoot the birds and bees',
    load: () => import('@/apps/minigames/Flappy'),
    defaultSize: { w: 524, h: 600 },
    minSize: { w: 464, h: 520 },
    fixedSize: true,
  },
  {
    id: 'solitaire',
    name: 'Solitaire',
    icon: Spade,
    color: '#1f9d55',
    brand: { label: 'Cards', from: '#7fe0a6', to: '#14713b' },
    category: 'games',
    group: 'Games',
    description: 'Klondike: build the four suits from ace to king',
    load: () => import('@/apps/minigames/Solitaire'),
    defaultSize: { w: 724, h: 540 },
    minSize: { w: 624, h: 460 },
    fixedSize: true,
  },
  {
    id: 'electrons',
    name: 'Electron Game',
    icon: Atom,
    color: '#c70c78',
    brand: { label: 'Atom', from: '#ff8fc8', to: '#9a0a5c' },
    category: 'games',
    group: 'Games',
    description: 'Add electrons and keep the atom stable',
    load: () => import('@/apps/minigames/Electrons'),
    defaultSize: { w: 604, h: 500 },
    minSize: { w: 524, h: 420 },
    fixedSize: true,
  },
  {
    id: 'materiallab',
    name: 'Material Lab',
    icon: FlaskConical,
    color: '#35e0ea',
    brand: { label: 'MatLab', from: '#9ef3f7', to: '#1a9aa3' },
    category: 'games',
    group: 'Games',
    description: 'Mix elements, heat the furnace, discover 44 compounds',
    load: () => import('@/apps/minigames/MaterialLab'),
    defaultSize: { w: 884, h: 540 },
    minSize: { w: 764, h: 460 },
    fixedSize: true,
  },
  {
    id: 'planetcraft',
    name: 'PlanetCraft',
    icon: Orbit,
    color: '#16a34a',
    brand: { label: 'KPlanet', from: '#7be38a', to: '#1a7f39', deep: ['#2f9c47', '#135424'] },
    category: 'games',
    group: 'Games',
    description: 'A voxel planet to walk, dig and build on',
    load: () => import('@/apps/games/PlanetCraft'),
    defaultSize: { w: 1100, h: 700 },
    minSize: { w: 480, h: 320 },
    singleton: true,
  },
  {
    id: 'simai',
    name: 'SimAI',
    icon: Castle,
    color: '#b45309',
    brand: { label: 'KSim', from: '#ffcd6b', to: '#d1761f', deep: ['#d47f1e', '#80450b'] },
    category: 'games',
    group: 'Games',
    description: 'A village that lives by itself',
    load: () => import('@/apps/games/SimAI'),
    defaultSize: { w: 1100, h: 700 },
    minSize: { w: 480, h: 320 },
    singleton: true,
  },
  {
    id: 'facecraft',
    name: 'FaceCraft',
    icon: Palette,
    color: '#db2777',
    brand: { label: 'KFace', from: '#ff97cb', to: '#cc2d7c', deep: ['#d43b89', '#7c154b'] },
    category: 'games',
    group: 'Games',
    description: 'Turn a photo into a Minecraft skin',
    load: () => import('@/apps/games/FaceCraft'),
    defaultSize: { w: 1100, h: 700 },
    minSize: { w: 480, h: 320 },
    singleton: true,
  },
]

/** The Applications menu's submenus, in order. */
export const GROUPS: AppManifest['group'][] = ['Office', 'Science', 'Development', 'Internet', 'Tools', 'Games']

export const CATEGORY_NAMES: Record<AppManifest['category'], string> = {
  system: 'System',
  kherve: 'Ktools',
  internet: 'Internet',
  games: 'Games',
}

export function getApp(id: string): AppManifest | undefined {
  return APPS.find((a) => a.id === id)
}

/** The app that opens files with this extension by default. */
export function appForExtension(ext: string): AppManifest | undefined {
  return APPS.find((a) => a.fileTypes?.includes(ext.toLowerCase()))
}
