// KherveOS's own themes, alongside the 24 shared Kherve themes (themes.data.ts).
// Same keys as the desktop palettes, so they could be added to the desktop apps too.

export const KHERVEOS_THEMES: Record<string, Record<string, string>> = {
  // The default: near-black with a warm tint and a deep red accent.
  'Kherve Red': {
    dark: '1',
    base: '#171012',
    surface: '#1e1517',
    chrome: '#251a1c',
    text: '#f3e9e5',
    text_muted: '#a9958f',
    accent: '#e0262c',
    accent2: '#ff8a3d',
    link: '#ff7b6e',
    highlight: '#e0262c',
    highlight_text: '#ffffff',
    bright_text: '#ff3333',
    disabled: '#7a6a66',
    placeholder: '#7f6c68',
    alt_base: '#211719',
    border: '#3b2a2d',
    button: '#2c2022',
    button_hover: '#3b2b2e',
    menu_sel: '#5e1b1f',
    desk_bg: '#0e0909',
    page_bg: '#ffffff',
    page_border: '#3b2a2d',
    status_text: '#a9958f',
  },
  // THE KherveOS look: black, with green.
  'Kherve Green': {
    dark: '1',
    base: '#0d0f0e',
    surface: '#121514',
    chrome: '#171b19',
    text: '#e9f1ec',
    text_muted: '#8b998f',
    accent: '#22b357',
    accent2: '#7fe08a',
    link: '#5fdc8c',
    highlight: '#22b357',
    highlight_text: '#ffffff',
    bright_text: '#ff3333',
    disabled: '#5c6a61',
    placeholder: '#6c7b71',
    alt_base: '#131715',
    border: '#252b28',
    button: '#1b201d',
    button_hover: '#252c28',
    menu_sel: '#134d2b',
    desk_bg: '#050706',
    page_bg: '#ffffff',
    page_border: '#252b28',
    status_text: '#8b998f',
  },
  // The light companion of Kherve Green, for apps set to Light in Settings: white
  // pages, soft green-grey chrome, the same green.
  'Kherve Light': {
    dark: '0',
    base: '#ffffff',
    surface: '#f3f7f4',
    chrome: '#e9f0eb',
    text: '#14201a',
    text_muted: '#5d6f63',
    accent: '#1f9d4d',
    accent2: '#2fbf63',
    link: '#17803f',
    highlight: '#1f9d4d',
    highlight_text: '#ffffff',
    bright_text: '#d33a3a',
    disabled: '#a3b2a8',
    placeholder: '#8a9a8f',
    alt_base: '#f5f9f6',
    border: '#d5e0d8',
    button: '#edf3ef',
    button_hover: '#e1ebe4',
    menu_sel: '#cdeed8',
    desk_bg: '#d9e3dc',
    page_bg: '#ffffff',
    page_border: '#d5e0d8',
    status_text: '#5d6f63',
  },
  // The light companion of Kherve Red: white paper, warm grey chrome, the same red.
  'Kherve Paper': {
    dark: '0',
    base: '#ffffff',
    surface: '#f7f2f0',
    chrome: '#efe7e4',
    text: '#1f1416',
    text_muted: '#6f5e5b',
    accent: '#c62828',
    accent2: '#d9622b',
    link: '#b3261e',
    highlight: '#c62828',
    highlight_text: '#ffffff',
    bright_text: '#ff3333',
    disabled: '#a39390',
    placeholder: '#9a8986',
    alt_base: '#f6f1ef',
    border: '#e2d5d1',
    button: '#f4edeb',
    button_hover: '#eadfdb',
    menu_sel: '#f8d7d2',
    desk_bg: '#d8cdca',
    page_bg: '#ffffff',
    page_border: '#e2d5d1',
    status_text: '#6f5e5b',
  },
}
