# KherveFitting - XPS Data Analysis Software
# Copyright (C) 2024-2026 Gwilherm Kerherve <g.kerherve@ic.ac.uk>
#
# KherveFitting is dual-licensed:
#   - GNU GPL v3.0 (see LICENSE-GPL.txt) for open-source use
#   - Commercial Licence (see LICENSE-COMMERCIAL.txt) for proprietary use
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-KherveFitting-Commercial
#
# KherveOS port: libraries/Peak_Functions.py (KherveFitting-AI, dev-AI v1.93):
# the line-shape helpers at the top of the module (apex offsets of the
# skewed Voigt, DL and TLA profiles), the PeakFunctions and OtherCalc
# classes, unchanged except that np.trapz comes from .compat (it is gone in
# NumPy 2.4, which Pyodide ships). Generated by SCRATCH/sync/gen.py.

import numpy as np
import lmfit
from lmfit.models import VoigtModel
from lmfit.lineshapes import skewed_voigt
from functools import lru_cache
from scipy.optimize import minimize_scalar, brentq
from scipy.signal import convolve, savgol_filter
from scipy.interpolate import interp1d
from scipy.ndimage import gaussian_filter
from scipy.integrate import cumulative_trapezoid

from .compat import trapz
from .numberformat import round_sig


@lru_cache(maxsize=1024)
def _skewed_voigt_apex_offset(sigma, gamma, skew):
    """Offset between lmfit's skewed_voigt 'center' parameter and the actual
    position of the profile maximum (apex - center).

    lmfit's SkewedVoigt multiplies a Voigt by (1 + erf(skew*(x-center)/(sigma*sqrt(2)))),
    which pushes the apex away from 'center' whenever skew != 0.
    """
    if sigma <= 0 or abs(skew) < 1e-9:
        return 0.0
    span = 4.0 * (sigma + abs(gamma)) * (1.0 + abs(skew))
    x = np.linspace(-span, span, 801)
    y = skewed_voigt(x, amplitude=1.0, center=0.0, sigma=sigma, gamma=gamma, skew=skew)
    i = int(np.argmax(y))
    # Refine around the coarse maximum: finer grid + parabolic interpolation
    step = x[1] - x[0]
    x_fine = np.linspace(x[i] - step, x[i] + step, 41)
    y_fine = skewed_voigt(x_fine, amplitude=1.0, center=0.0, sigma=sigma, gamma=gamma, skew=skew)
    j = int(np.argmax(y_fine))
    if 0 < j < len(x_fine) - 1:
        denom = y_fine[j - 1] - 2.0 * y_fine[j] + y_fine[j + 1]
        if denom < 0:
            fine_step = x_fine[1] - x_fine[0]
            return float(x_fine[j] + 0.5 * fine_step * (y_fine[j - 1] - y_fine[j + 1]) / denom)
    return float(x_fine[j])


def _dl_unit_profile(t, sigma_r, a_dl, sigma_g):
    """Unit-area double Lorentzian evaluated at E0 = 0 on the uniform grid t.

    Split Lorentzian (Herrera-Gomez et al., JVST A 41, 043208 (2023), Eq. 2)
    with the wide side (sigma_l = a_dl * sigma_r) toward higher BE (t > 0),
    numerically convolved with the unit-area Gaussian of FWHM sigma_g (Eq. 3-4).
    """
    sig_l = a_dl * sigma_r
    norm = 1.0 / (np.pi * sig_l / 4.0 + np.pi * sigma_r / 4.0)
    ls = norm * np.where(t > 0,
                         1.0 / (1.0 + t ** 2 / (sig_l / 2.0) ** 2),
                         1.0 / (1.0 + t ** 2 / (sigma_r / 2.0) ** 2))
    step = t[1] - t[0]
    if sigma_g > 2.0 * step:
        half = int(np.ceil(4.0 * sigma_g / step))
        tk = np.arange(-half, half + 1) * step
        kernel = np.exp(-4.0 * np.log(2.0) * tk ** 2 / sigma_g ** 2)
        kernel /= kernel.sum()
        ls = convolve(ls, kernel, mode='same')
    return ls


@lru_cache(maxsize=512)
def _dl_apex_offset(sigma_r, a_dl, sigma_g):
    """Offset between the double Lorentzian's E0 and its actual maximum.

    The Gaussian smearing of the asymmetric split Lorentzian pushes the apex
    from E0 toward the wide (high-BE) side; this returns apex - E0.
    """
    if a_dl == 1.0 or sigma_g <= 0.0:
        return 0.0
    span = 8.0 * (sigma_r * (1.0 + a_dl) + sigma_g)
    t = np.linspace(-span, span, 4001)
    y = _dl_unit_profile(t, sigma_r, a_dl, sigma_g)
    i = int(np.argmax(y))
    if 0 < i < len(t) - 1:
        denom = y[i - 1] - 2.0 * y[i] + y[i + 1]
        if denom < 0:
            step = t[1] - t[0]
            return float(t[i] + 0.5 * step * (y[i - 1] - y[i + 1]) / denom)
    return float(t[i])


@lru_cache(maxsize=512)
def _tla_width_scale(mu, alpha):
    """FWHM of the unconvolved T profile for unit Lorentzian FWHM.

    Used so that the model's fwhm parameter is the actual FWHM of the TLA
    shape (before Gaussian convolution) rather than the raw Lorentzian width.
    """
    t = np.linspace(-40.0, 40.0, 80001)
    lor = (1.0 / (1.0 + 4.0 * t ** 2)) ** alpha
    tail = np.pi / 2.0 + np.arctan(2.0 * t) + np.pi / mu
    y = lor * tail
    half = np.max(y) / 2.0
    idx = np.where(y >= half)[0]
    if len(idx) >= 2:
        return float(t[idx[-1]] - t[idx[0]])
    return 1.0


@lru_cache(maxsize=512)
def _tla_apex_offset(fwhm, mu, wg, alpha):
    """Offset between the TLA profile's nominal centre and its actual maximum.

    The arctangent tail factor (and the Gaussian convolution) push the apex
    toward the high-BE side; this returns apex - E0 for a unit-area TLA.
    """
    span = 10.0 * (fwhm + wg)
    t = np.linspace(-span, span, 4001)
    y = _tla_unit_profile(t, fwhm, mu, wg, alpha)
    i = int(np.argmax(y))
    if 0 < i < len(t) - 1:
        denom = y[i - 1] - 2.0 * y[i] + y[i + 1]
        if denom < 0:
            step = t[1] - t[0]
            return float(t[i] + 0.5 * step * (y[i - 1] - y[i + 1]) / denom)
    return float(t[i])


def _tla_unit_profile(t, fwhm, mu, wg, alpha):
    """Unit-area TLA evaluated at E0 = 0 on the uniform grid t (BE axis).

    CasaXPS Cookbook (2026), Line shapes section:
    T(x: alpha, mu) = [1/(1+4x^2)]^alpha * [pi/2 - atan(2x) + pi/mu]
    convolved with a Gaussian; written there on the KE axis, mirrored here so
    the tail extends toward higher BE (t > 0). 'fwhm' is the actual FWHM of
    the unconvolved T profile (internally rescaled via _tla_width_scale).
    """
    f_lor = fwhm / _tla_width_scale(mu, alpha)
    u = t / f_lor
    lor = (1.0 / (1.0 + 4.0 * u ** 2)) ** alpha
    tail = np.pi / 2.0 + np.arctan(2.0 * u) + np.pi / mu
    y = lor * tail
    step = t[1] - t[0]
    if wg > 2.0 * step:
        half = int(np.ceil(4.0 * wg / step))
        tk = np.arange(-half, half + 1) * step
        kernel = np.exp(-4.0 * np.log(2.0) * tk ** 2 / wg ** 2)
        kernel /= kernel.sum()
        y = convolve(y, kernel, mode='same')
    area = trapz(y, t)
    return y / area if area > 0 else y


class PeakFunctions:

    @staticmethod
    def gaussian_other(x, E, F, m):
        return np.exp(-4 * np.log(2) * ((x - E) / F)**2) * (1 - m / 100)

    @staticmethod
    def gaussian(x, E, F, m):
        return np.exp(-4 * np.log(2) * (1 - m / 100) * ((x - E) / F)**2)

    @staticmethod
    def lorentzian(x, E, F, m):
        return 1 / (1 + 4 * m / 100 * ((x - E) / F)**2)

    @staticmethod
    def gauss_lorentz_OLD(x, center, fwhm, fraction, amplitude):
        return amplitude * (
            PeakFunctions.gaussian(x, center, fwhm, fraction*1) *
            PeakFunctions.lorentzian(x, center, fwhm, fraction*1))

    @staticmethod
    def S_gauss_lorentz(x, center, fwhm, fraction, amplitude):
        return amplitude * (
            (1-fraction/100) * PeakFunctions.gaussian(x, center, fwhm, 0) +
            fraction/100 * PeakFunctions.lorentzian(x, center, fwhm, 100))

    @staticmethod
    def gauss_lorentz(x, center , fwhm, fraction, amplitude):
        peak = amplitude * (
                PeakFunctions.gaussian(x, center, fwhm, fraction * 1) *
                PeakFunctions.lorentzian(x, center, fwhm, fraction * 1))
        return peak


    @staticmethod
    def gauss_lorentz_Area(x, center, area, fwhm, fraction):
        sigma = fwhm / (2 * np.sqrt(2 * np.log(2)))
        height = area / (sigma * np.sqrt(2 * np.pi))
        return height * (
                PeakFunctions.gaussian(x, center, fwhm, fraction * 1) *
                PeakFunctions.lorentzian(x, center, fwhm, fraction * 1))

    @staticmethod
    def S_gauss_lorentz_Area_MISMATCH(x, center, area, fwhm, fraction):
        sigma = fwhm / (2 * np.sqrt(2 * np.log(2)))
        height = area / (sigma * np.sqrt(2 * np.pi))
        Area = height * (
                (1 - fraction / 100) * PeakFunctions.gaussian(x, center, fwhm, 0) +
                fraction / 100 * PeakFunctions.lorentzian(x, center, fwhm, 100))
        # print(f"SGL Area: {Area}")
        return Area

    @staticmethod
    def S_gauss_lorentz_Area(x, center, area, fwhm, fraction):
        sigma = fwhm / (2 * np.sqrt(2 * np.log(2)))
        gamma = fwhm / 2
        height = area / ((1 - fraction / 100) * sigma * np.sqrt(2 * np.pi) + (fraction / 100) * np.pi * gamma)
        return height * (
                (1 - fraction / 100) * PeakFunctions.gaussian(x, center, fwhm, 0) +
                fraction / 100 * PeakFunctions.lorentzian(x, center, fwhm, 100))

    # SHALL NOT BE USEFUL
    @staticmethod
    def tail(x, center, tail_mix, tail_exp, fwhm):

        # Avoid division by zero and negative exponents
        safe_exp = np.maximum(tail_exp, 1e-5)
        safe_mix = np.maximum(tail_mix, 1e-5)
        return np.where(x > center,     np.exp(-safe_exp * np.abs(x - center) ** safe_mix), 0)

    @staticmethod
    def filter_func(x, center):
        return np.where(x <= center, 1, 0)



    @staticmethod
    def S_gauss_lorentz_tail(x, center, fwhm, fraction, amplitude, tail_mix, tail_exp):
        peak = amplitude * (
                (1 - fraction/100) * PeakFunctions.gaussian(x, center, fwhm, 0) +
                fraction/100 * PeakFunctions.lorentzian(x, center, fwhm, 100))
        tail = PeakFunctions.tail(x, center, tail_mix, tail_exp)
        return peak * (1 - tail_mix) + amplitude * tail

    @staticmethod
    def pseudo_voigt(x, center, amplitude, sigma, fraction):
        """
        Custom Pseudo-Voigt function.

        Parameters:
        x : array
            The x values
        center : float
            The peak center
        amplitude : float
            The peak height
        sigma : float
            The peak width (standard deviation for Gaussian component)
        fraction : float
            The fraction of Lorentzian component (0 to 1)

        Returns:
        array : The y values of the Pseudo-Voigt function
        """
        sigma2 = sigma ** 2
        gamma = sigma * np.sqrt(2 * np.log(2))

        gaussian = (1 - fraction/100) * np.exp(-((x - center) ** 2) / (2 * sigma2))
        lorentzian = fraction/100 * (gamma ** 2 / ((x - center) ** 2 + gamma ** 2))

        return amplitude * (gaussian + lorentzian)

    @staticmethod
    def pseudo_voigt_fwhm(x, center, amplitude, fwhm, fraction):
        """
        Custom Pseudo-Voigt function using FWHM.

        Parameters:
        x : array
            The x values
        center : float
            The peak center
        amplitude : float
            The peak height
        fwhm : float
            Full Width at Half Maximum of the peak
        fraction : float
            The fraction of Lorentzian component (0 to 1)

        Returns:
        array : The y values of the Pseudo-Voigt function
        """
        sigma = fwhm / (2 * np.sqrt(2 * np.log(2)))  # Convert FWHM to sigma for Gaussian
        gamma = fwhm / 2  # Convert FWHM to gamma for Lorentzian

        z = (x - center) / sigma

        gaussian = (1 - fraction/100) * np.exp(-z ** 2 / 2) / (sigma * np.sqrt(2 * np.pi))
        lorentzian = fraction/100 * gamma / (np.pi * (gamma ** 2 + (x - center) ** 2))

        return amplitude * (gaussian + lorentzian) * sigma * np.sqrt(2 * np.pi)

    @staticmethod
    def voigt_fwhm(sigma, gamma):
        """
        Approximate the FWHM of a Voigt profile.

        This uses an approximation that is accurate to within a few percent.

        Parameters:
        sigma : float
            The sigma parameter of the Gaussian component
        gamma : float
            The gamma parameter of the Lorentzian component

        Returns:
        float : The approximate FWHM of the Voigt profile
        """
        fg = 2 * sigma * np.sqrt(2 * np.log(2))
        fl = 2 * gamma
        return 0.5346 * fl + np.sqrt(0.2166 * fl ** 2 + fg ** 2)

    @staticmethod
    def skewed_voigt_fwhm(sigma, gamma, skew):
        model = lmfit.models.SkewedVoigtModel()
        x = np.linspace(-20 * sigma, 20 * sigma, 1000)
        y = model.eval(x=x, center=0, amplitude=1.0, sigma=sigma, gamma=gamma, skew=skew)

        max_y = np.max(y)
        half_max = max_y / 2

        # Find points where y crosses half_max
        idx = np.where(y >= half_max)[0]
        if len(idx) >= 2:
            fwhm = abs(x[idx[-1]] - x[idx[0]])
        else:
            fwhm = 2.355 * sigma  # Fallback to Gaussian FWHM

        return fwhm

    @staticmethod
    def voigt_fwhm_split(fwhm, fraction):
        """Split a total Voigt FWHM into (Gaussian FWHM, Lorentzian FWHM).

        fraction is the L/G ratio in percent, defined like the other Voigt
        models as f_l / (f_g + f_l) * 100. Uses the Olivero-Longbothum
        approximation F = 0.5346*f_l + sqrt(0.2166*f_l^2 + f_g^2), which is
        linear in the overall scale, so the split is analytic.
        """
        r = min(max(fraction / 100.0, 0.0), 0.999)
        k = 0.5346 * r + np.sqrt(0.2166 * r * r + (1.0 - r) ** 2)
        scale = fwhm / k
        return (1.0 - r) * scale, r * scale

    @staticmethod
    def voigt_simple(x, center=0.0, area=1.0, fwhm=1.0, fraction=30.0):
        """True Voigt parameterised directly by its total FWHM and L/G ratio.

        The FWHM column is the actual FWHM of the peak (Olivero-Longbothum,
        accurate to ~0.02%) and the L/G column sets the Lorentzian share of
        that width; the Gaussian/Lorentzian widths are derived internally.
        'area' is the analytic area of the profile.
        """
        from lmfit.lineshapes import voigt as voigt_lineshape
        f_g, f_l = PeakFunctions.voigt_fwhm_split(float(fwhm), float(fraction))
        sigma_v = max(f_g / (2.0 * np.sqrt(2.0 * np.log(2.0))), 1e-4)
        gamma_v = f_l / 2.0
        return voigt_lineshape(x, amplitude=area, center=center, sigma=sigma_v, gamma=gamma_v)

    @staticmethod
    def voigt_simple_skewed(x, center=0.0, area=1.0, fwhm=1.0, fraction=30.0, skew=0.0):
        """Skewed true Voigt driven by total FWHM, L/G ratio and tail parameter S.

        Hybrid of "Voigt (Area)" (single width: the FWHM column is the actual
        total FWHM, split internally into Gaussian/Lorentzian parts via the
        L/G ratio) and "Voigt (Area, L/G, sigma, S)" (erf-type tail S with the
        apex re-anchored so 'center' stays the peak maximum).
        """
        f_g, f_l = PeakFunctions.voigt_fwhm_split(float(fwhm), float(fraction))
        sigma_v = max(f_g / (2.0 * np.sqrt(2.0 * np.log(2.0))), 1e-4)
        gamma_v = f_l / 2.0
        return PeakFunctions.skewed_voigt_profile(x, center=center, amplitude=area,
                                                  sigma=sigma_v, gamma=gamma_v, skew=skew)

    @staticmethod
    def create_voigt_simple_skewed_model(prefix=''):
        """lmfit model for "Voigt (Area, L/G, S)" (params: center, area, fwhm,
        fraction, skew) with 'center' anchored to the true peak maximum."""
        return lmfit.Model(PeakFunctions.voigt_simple_skewed, prefix=prefix)

    @staticmethod
    def skewed_voigt_apex_offset(sigma, gamma, skew):
        """Distance between lmfit's skewed_voigt 'center' and its true maximum."""
        return _skewed_voigt_apex_offset(float(sigma), float(gamma), float(skew))

    @staticmethod
    def skewed_voigt_profile(x, center=0.0, amplitude=1.0, sigma=1.0, gamma=1.0, skew=0.0):
        """Skewed Voigt lineshape re-anchored so that 'center' is the position of
        the peak maximum, unlike lmfit's SkewedVoigt where the apex drifts away
        from 'center' when skew != 0."""
        offset = _skewed_voigt_apex_offset(float(sigma), float(gamma), float(skew))
        return skewed_voigt(x, amplitude=amplitude, center=center - offset,
                            sigma=sigma, gamma=gamma, skew=skew)

    @staticmethod
    def create_skewed_voigt_model(prefix=''):
        """Drop-in replacement for lmfit.models.SkewedVoigtModel (same parameter
        names) whose 'center' parameter is the true peak maximum."""
        return lmfit.Model(PeakFunctions.skewed_voigt_profile, prefix=prefix)

    @staticmethod
    def pseudo_voigt_amplitude_to_height(amplitude, sigma, fraction):
        """
        Convert amplitude to height for a Pseudo-Voigt profile.

        Parameters:
        amplitude : float
            The amplitude of the Pseudo-Voigt profile
        sigma : float
            The sigma parameter of the profile (related to FWHM)
        fraction : float
            The fraction of Lorentzian component (0 to 1)

        Returns:
        float : The height of the Pseudo-Voigt profile
        """
        sqrt2pi = np.sqrt(2 * np.pi)
        sqrt2ln2 = np.sqrt(2 * np.log(2))

        gaussian_height = amplitude / (sigma * sqrt2pi)
        lorentzian_height = 2 * amplitude / (np.pi * sigma * 2 * sqrt2ln2)

        height = (1 - fraction/100) * gaussian_height + fraction/100 * lorentzian_height

        return height

    @staticmethod
    def pseudo_voigt_height_to_amplitude(height, sigma, fraction):
        """
        Convert height to amplitude for a Pseudo-Voigt profile.

        Parameters:
        height : float
            The height of the Pseudo-Voigt profile
        sigma : float
            The sigma parameter of the profile (related to FWHM)
        fraction : float
            The fraction of Lorentzian component (0 to 1)

        Returns:
        float : The amplitude of the Pseudo-Voigt profile
        """
        sqrt2pi = np.sqrt(2 * np.pi)
        sqrt2ln2 = np.sqrt(2 * np.log(2))

        gaussian_amplitude = height * sigma * sqrt2pi
        lorentzian_amplitude = height * np.pi * sigma * 2 * sqrt2ln2 / 2

        amplitude = (1 - fraction/100) * gaussian_amplitude + fraction/100 * lorentzian_amplitude

        return amplitude

    def voigt_area(height, sigma, gamma):
        from scipy.special import wofz

        # Convert sigma to Gaussian FWHM
        fwhm_g = 2 * sigma * np.sqrt(2 * np.log(2))

        # Convert gamma to Lorentzian FWHM
        fwhm_l = 2 * gamma

        # Calculate the Voigt function at its center
        voigt_max = np.real(wofz((0 + 1j * gamma) / (sigma * np.sqrt(2))))

        # Calculate the area
        area = height * (np.pi * fwhm_l / 2 + np.sqrt(np.pi * np.log(2)) * fwhm_g) / voigt_max

        return area

    @staticmethod
    def get_voigt_height(amplitude, sigma, gamma):
        """
        Calculate the height of a Voigt profile directly using the lmfit model.
        """
        model = lmfit.models.VoigtModel()
        params = model.make_params(amplitude=amplitude, center=0, sigma=sigma, gamma=gamma)
        return model.eval(params, x=0)

    @staticmethod
    def get_skewedvoigt_height(amplitude, sigma, gamma, skew):
        """
        Calculate the height at the true maximum (apex) of a skewed Voigt profile.
        """
        return float(PeakFunctions.skewed_voigt_profile(0.0, center=0.0, amplitude=amplitude,
                                                        sigma=sigma, gamma=gamma, skew=skew))

    @staticmethod
    def voigt_height_to_area(height, sigma, gamma):
        voigt = VoigtModel()
        x = np.linspace(-10 * sigma, 10 * sigma, 1000)
        params = voigt.make_params(center=0, sigma=sigma, gamma=gamma, amplitude=1)
        y = voigt.eval(params, x=x)
        max_y = np.max(y)
        amplitude = height / max_y
        return amplitude  # For distribution models, amplitude is equivalent to area

    @staticmethod
    def skewedvoigt_height_to_area(height, sigma, gamma, skew):
        if sigma <= 0 or gamma < 0:
            raise ValueError("Invalid sigma/gamma parameters")

        skewedvoigt = lmfit.models.SkewedVoigtModel()
        x_range = max(abs(skew) * sigma * 20, 10 * sigma)  # Wider range for high skew
        x = np.linspace(-x_range, x_range, 1000)

        try:
            params = skewedvoigt.make_params(center=0, sigma=sigma, gamma=gamma, amplitude=1, skew=skew)
            y = skewedvoigt.eval(params, x=x)
            max_y = np.max(y)
            if max_y <= 0:
                raise ValueError("Invalid peak shape")
            amplitude = height / max_y
            return amplitude
        except:
            return height * (sigma * np.sqrt(2 * np.pi))  # Fallback to Gaussian area

    @staticmethod
    def get_pseudo_voigt_height(amplitude, sigma, fraction):
        """
        Calculate the height of a Pseudo-Voigt profile directly using the lmfit model.
        """
        model = lmfit.models.PseudoVoigtModel()
        params = model.make_params(amplitude=amplitude, center=0, sigma=sigma, fraction=fraction/100)
        return model.eval(params, x=0)

    @staticmethod
    def find_lorentzian_fwhm(true_fwhm, center, amplitude, sigma, gamma, max_iterations=50):
        def objective(lorentzian_fwhm):
            return abs(PeakFunctions.calculate_true_fwhm(center, amplitude, lorentzian_fwhm, sigma, gamma) - true_fwhm)

        if not PeakFunctions.is_valid_scalar(true_fwhm):
            raise ValueError(f"Invalid true_fwhm: {true_fwhm}")

        try:
            result = minimize_scalar(objective, bounds=(true_fwhm * 0.1, true_fwhm * 10), method='bounded',
                                     options={'maxiter': max_iterations})
            return result.x
        except Exception as e:
            print(f"Error in minimize_scalar: {e}")
            return true_fwhm  # Return the input FWHM as a fallback

    @staticmethod
    def calculate_true_fwhm(center, amplitude, fwhm, sigma, gamma, tolerance=1e-6, max_iterations=50):
        def la_function(x):
            return PeakFunctions.LA(x, center, amplitude, fwhm, sigma, gamma)

        half_max = la_function(center) / 2

        def find_half_max(x):
            return la_function(x) - half_max

        try:
            left_x = brentq(find_half_max, center - 10 * fwhm, center, maxiter=max_iterations, xtol=tolerance)
            right_x = brentq(find_half_max, center, center + 10 * fwhm, maxiter=max_iterations, xtol=tolerance)
            return right_x - left_x
        except ValueError as e:
            print(f"Error in calculate_true_fwhm: {e}")
            return fwhm  # Return the input FWHM as a fallback

    @staticmethod
    def LA_OTHER(x, center, amplitude, true_fwhm, sigma, gamma):
        true_fwhm = min(true_fwhm, 20)  # Limit true_fwhm to a maximum of 20

        if not PeakFunctions.is_valid_scalar(true_fwhm):
            raise ValueError(f"Invalid true_fwhm value: {true_fwhm}")
        if not PeakFunctions.is_valid_scalar(center):
            raise ValueError(f"Invalid center value: {center}")
        if not PeakFunctions.is_valid_scalar(amplitude):
            raise ValueError(f"Invalid amplitude value: {amplitude}")
        if not PeakFunctions.is_valid_scalar(sigma):
            raise ValueError(f"Invalid sigma value: {sigma}")
        if not PeakFunctions.is_valid_scalar(gamma):
            raise ValueError(f"Invalid gamma value: {gamma}")

        try:
            lorentzian_fwhm = PeakFunctions.estimate_lorentzian_fwhm(true_fwhm, sigma, gamma)
        except Exception as e:
            print(f"Error in estimate_lorentzian_fwhm: {e}")
            lorentzian_fwhm = true_fwhm  # Fallback to true_fwhm if estimation fails

        return amplitude * np.where(
            x <= center,
            1 / (1 + 4 * ((x - center) / lorentzian_fwhm) ** 2) ** gamma,
            1 / (1 + 4 * ((x - center) / lorentzian_fwhm) ** 2) ** sigma
        )

    @staticmethod
    def estimate_lorentzian_fwhm(true_fwhm, sigma, gamma, tolerance=1e-6, max_iterations=50):
        def peak_function(x, fwhm):
            return 1 / (1 + 4 * (x / fwhm) ** 2) ** ((sigma + gamma) / 2)

        def find_half_max(fwhm):
            half_max = peak_function(0, fwhm) / 2
            try:
                x_half = brentq(lambda x: peak_function(x, fwhm) - half_max, 0, fwhm * 10,
                                xtol=tolerance, maxiter=max_iterations)
                return 2 * x_half - true_fwhm
            except ValueError:
                return fwhm - true_fwhm  # Return a value that won't be zero to continue the search

        try:
            print("FWHM = "+str(true_fwhm))
            lorentzian_fwhm = brentq(find_half_max, true_fwhm * 0.1, true_fwhm * 10,
                                     xtol=tolerance, maxiter=max_iterations)
            return lorentzian_fwhm
        except ValueError:
            print(f"Failed to estimate Lorentzian FWHM. Using true FWHM: {true_fwhm}")
            return true_fwhm

    @staticmethod
    def is_valid_scalar(value):
        return value is not None and np.isfinite(value) and value > 0


    @staticmethod
    # @jit(nopython=True, parallel=True)
    def LA(x, center, amplitude, fwhm, sigma, gamma):
        #amplitude here is the area

        # Calculate lorentzian width from the input FWHM
        F = 2 * fwhm / (np.sqrt(2 ** (1 / sigma) - 1) + np.sqrt(2 ** (1 / gamma) - 1))

        # Create the peak shape with unit amplitude
        peak_shape = np.where(
            x <= center,
            1 / (1 + 4 * ((x - center) / F) ** 2) ** gamma,
            1 / (1 + 4 * ((x - center) / F) ** 2) ** sigma
        )

        # Sort x values and corresponding peak shape for correct integration
        sort_idx = np.argsort(x)
        x_sorted = x[sort_idx]
        peak_shape_sorted = peak_shape[sort_idx]

        # Calculate the area of unit amplitude peak
        unit_area = abs(trapz(peak_shape_sorted, x_sorted))

        # Calculate required amplitude to achieve desired area
        height = amplitude / unit_area if unit_area != 0 else 0

        return height * peak_shape

    @staticmethod
    def LF(x, center, amplitude, fwhm, sigma, gamma, w=30.0):
        """LF (finite Lorentzian): LA with exponents that grow with distance.

        Exact form from Major, Shah, Avval, Fernandez, Fairley & Linford,
        "Advanced Line Shapes in XPS II. The Finite Lorentzian (LF) Line Shape",
        Vacuum Technology & Coating, April 2020 (MATLAB listing):
            exp_eff(t) = 3 - (3 - exp0) / (1 + 4*(t/w)^2)
        i.e. the LA exponents ramp smoothly (Lorentzian-shaped ramp of width w)
        from their entered values at the peak to the constant 3 far away, which
        drives the tails to the baseline and makes the area finite.
        w ranges ~1 (strongest suppression) to 1000 (essentially LA).
        amplitude is the peak area (numerically normalised like LA).
        """
        # Calculate lorentzian width from the input FWHM
        F = 2 * fwhm / (np.sqrt(2 ** (1 / sigma) - 1) + np.sqrt(2 ** (1 / gamma) - 1))

        t = x - center
        L = 1 / (1 + 4 * (t / F) ** 2)

        # Exponents ramp from the LA values at the peak to 3 on the scale w
        ASYM_LIMIT = 3.0
        w_safe = max(float(w), 1e-3)
        ramp = 1.0 / (1.0 + 4.0 * (t / w_safe) ** 2)
        expo = np.where(t <= 0, gamma, sigma)  # same side convention as LA
        expo = ASYM_LIMIT - (ASYM_LIMIT - expo) * ramp
        peak_shape = L ** expo

        # Normalise to the requested area over the provided x range
        sort_idx = np.argsort(x)
        unit_area = abs(trapz(peak_shape[sort_idx], x[sort_idx]))
        height = amplitude / unit_area if unit_area != 0 else 0

        return height * peak_shape

    @staticmethod
    def DL(x, center=0.0, amplitude=1.0, sigma=0.4, gamma=1.0, a_dl=1.5):
        """Double Lorentzian (Herrera-Gomez et al., JVST A 41, 043208 (2023)).

        A split Lorentzian - narrow side of width sigma (eV) toward lower BE,
        wide side of width a_dl*sigma toward higher BE - analytically normalised
        to unit area, then convolved with a unit-area Gaussian of FWHM gamma (eV).
        'amplitude' is therefore the exact analytic area of the full profile.
        At a_dl = 1 the DL is exactly a Voigt function.
        The convolution shifts the maximum away from E0 toward the tail; here
        the profile is re-anchored so that 'center' is the true peak maximum.
        Grid mapping: sigma column = sigma, gamma column = Gaussian FWHM,
        skew column = a_dl (>= 1).
        """
        x_arr = np.atleast_1d(np.asarray(x, dtype=float))
        sigma = max(float(sigma), 1e-3)
        gamma = max(float(gamma), 0.0)
        a_dl = max(float(a_dl), 0.01)
        offset = _dl_apex_offset(sigma, a_dl, gamma)
        e0 = center - offset

        widths = sigma * (1.0 + a_dl) + gamma
        t_data = x_arr - e0
        span = max(10.0 * widths, (np.max(np.abs(t_data)) if t_data.size else 0.0) + 5.0 * widths)
        step = max(min(sigma, gamma if gamma > 0 else sigma) / 20.0, span / 4000.0)
        n = int(2 * span / step) + 1
        t = np.linspace(-span, span, n)
        y = _dl_unit_profile(t, sigma, a_dl, gamma)
        out = amplitude * np.interp(t_data, t, y)
        return out if np.ndim(x) else float(out[0])

    @staticmethod
    def TLA(x, center=0.0, amplitude=1.0, fwhm=1.0, mu=20.0, wg=1.0, alpha=1.0):
        """CasaXPS TLA asymmetric line shape (Cookbook 2026, Line shapes section).

        A Lorentzian raised to the power alpha and modulated by the arctangent
        tail factor [pi/2 + atan(2t/F) + pi/mu] (tail toward higher BE),
        convolved with a Gaussian of FWHM wg (eV) and normalised to unit area,
        so 'amplitude' is the area. 'fwhm' is the actual FWHM of the
        unconvolved T profile (the Lorentzian width is derived internally).
        The constant pi/mu sets the floor of the modulation: LARGER mu =
        stronger asymmetry, small mu approaches a symmetric shape.
        The profile is re-anchored so 'center' is the true peak maximum.
        Grid mapping: sigma column = mu, gamma column = alpha, W_g/skew
        column = wg (like LA*G, which also keeps its Gaussian width there).
        """
        x_arr = np.atleast_1d(np.asarray(x, dtype=float))
        fwhm = max(float(fwhm), 1e-3)
        mu = max(float(mu), 1e-3)
        wg = max(float(wg), 0.0)
        alpha = max(float(alpha), 0.05)
        offset = _tla_apex_offset(fwhm, mu, wg, alpha)
        e0 = center - offset

        widths = fwhm + wg
        t_data = x_arr - e0
        span = max(10.0 * widths, (np.max(np.abs(t_data)) if t_data.size else 0.0) + 5.0 * widths)
        step = max(min(fwhm, wg if wg > 0 else fwhm) / 20.0, span / 4000.0)
        n = int(2 * span / step) + 1
        t = np.linspace(-span, span, n)
        y = _tla_unit_profile(t, fwhm, mu, wg, alpha)
        out = amplitude * np.interp(t_data, t, y)
        return out if np.ndim(x) else float(out[0])

    @staticmethod
    def SB_voigt(x, center=0.0, fwhm=1.0, fraction=30.0, amplitude=1.0):
        """Shirley-background component SB(0)V (Fairley et al., JVST A 41, 013204
        (2023), Eq. 7: SB(0)F(x) = integral of F from x to infinity, KE axis).

        The sigmoid response of a true Voigt bell of total FWHM 'fwhm' and L/G
        ratio 'fraction': a step of height 'amplitude' rising toward higher BE,
        centred on 'center'. Used as an optimisable background component under
        a photoelectron peak (e.g. CasaXPS SB(0)LA(...)).
        """
        x_arr = np.atleast_1d(np.asarray(x, dtype=float))
        fwhm = max(float(fwhm), 1e-3)
        t_data = x_arr - center
        span = max(20.0 * fwhm, (np.max(np.abs(t_data)) if t_data.size else 0.0) + 10.0 * fwhm)
        n = 4001
        t = np.linspace(-span, span, n)
        bell = PeakFunctions.voigt_simple(t, 0.0, 1.0, fwhm, fraction)
        cdf = np.cumsum(bell)
        cdf = cdf / cdf[-1]
        out = amplitude * np.interp(t_data, t, cdf)
        return out if np.ndim(x) else float(out[0])

    @staticmethod
    # @jit(nopython=True, parallel=True)
    def LAxG(x, center, amplitude, fwhm, sigma, gamma, fwhm_g):
        # Define the LA function
        # gaussian_fwhm =0.64 # now done through the grid

        # Calculate lorentzian width from the input FWHM
        F = 2 * fwhm / (np.sqrt(2 ** (1 / sigma) - 1) + np.sqrt(2 ** (1 / gamma) - 1))
        def LA_N(x):
            return np.where(
                x <= 0,
                1 / (1 + 4 * ((x ) / F) ** 2) ** gamma,
                1 / (1 + 4 * ((x ) / F) ** 2) ** sigma
            )

        # Define the Gaussian function
        def gaussian(x, fwhm_g):
            return np.exp(-4 * np.log(2) * ((x ) / fwhm_g) ** 2)

        x_range = max(x.max() - x.min(), 4 * fwhm)
        x_high_res = np.linspace(- x_range / 2, + x_range / 2, len(x) * 4)

        la = LA_N(x_high_res)
        gauss = gaussian(x_high_res, fwhm_g)

        convolved = convolve(la, gauss, mode='same') / sum(gauss)

        peak_shape = np.interp(x - center, x_high_res, convolved)

        # Sort x values and corresponding peak shape for correct integration
        sort_idx = np.argsort(x)
        x_sorted = x[sort_idx]
        peak_shape_sorted = peak_shape[sort_idx]

        # Calculate the area of unit amplitude peak
        unit_area = abs(trapz(peak_shape_sorted, x_sorted))

        # Calculate required amplitude to achieve desired area
        height = amplitude / unit_area if unit_area != 0 else 0

        return height * peak_shape


    @staticmethod
    def A_GL(x, center=0.0, amplitude=1.0, fwhm=1.0, fraction=30.0, a=0.2, b=0.4):
        """CasaXPS A(a,b,0)GL(p) - Gelius asymmetric Gaussian/Lorentzian product.

        GL(x) = exp(-4ln2(1-m)t^2/F^2) / (1 + 4m t^2/F^2) with m = fraction/100.
        On the high-BE side (t = x - center > 0) an asymmetric tail is added:
        A(x) = GL(x) + w(a,b)*[AW(x) - GL(x;F,E,0)]
        with AW = exp(-(2*sqrt(ln2)*t / (F + a*2*sqrt(ln2)*t))^2),
        GL(x;F,E,0) = exp(-4ln2*t^2/F^2) (pure Gaussian of FWHM F) and
        w(a,b) = b*(0.7 + 0.3/(a + 0.01)).
        Source: CasaXPS "Peak Fitting in XPS" (Casa Software Ltd, 2006), p.20 -
        the Gelius function; formula given there on the KE axis, mapped here to BE.
        The tail term is zero (value and slope) at the center, so 'center' is the
        true peak maximum and 'amplitude' is the height at the maximum.
        """
        x = np.asarray(x, dtype=float)
        m = np.clip(fraction, 0.0, 100.0) / 100.0
        t = x - center
        gl = np.exp(-4 * np.log(2) * (1 - m) * t ** 2 / fwhm ** 2) / (1 + 4 * m * t ** 2 / fwhm ** 2)
        w = b * (0.7 + 0.3 / (a + 0.01))
        # u = 2*sqrt(ln2)*t so that AW(a=0) equals the pure Gaussian of FWHM F.
        # The width grows linearly with distance on the tail side, so AW decays
        # more slowly than the Gaussian and the added term is a positive tail
        # approaching w*exp(-1/a^2) asymptotically.
        u = 2.0 * np.sqrt(np.log(2.0)) * np.where(t > 0, t, 0.0)
        aw = np.exp(-(u / (fwhm + a * u)) ** 2)
        g0 = np.exp(-(u / fwhm) ** 2)
        tail = np.where(t > 0, w * (aw - g0), 0.0)
        return amplitude * (gl + tail)

    @staticmethod
    def A_SGL(x, center=0.0, amplitude=1.0, fwhm=1.0, fraction=30.0, a=0.2, b=0.4):
        """CasaXPS A(a,b,0)SGL(p) - Gelius asymmetric Gaussian/Lorentzian sum.

        Same construction as A_GL but with the SGL sum form as symmetric base:
        SGL(x) = (1-m)*exp(-4ln2*t^2/F^2) + m/(1 + 4t^2/F^2), m = fraction/100.
        The Gelius tail (see A_GL) is added on the high-BE side.
        """
        x = np.asarray(x, dtype=float)
        m = np.clip(fraction, 0.0, 100.0) / 100.0
        t = x - center
        sgl = ((1 - m) * np.exp(-4 * np.log(2) * t ** 2 / fwhm ** 2)
               + m / (1 + 4 * t ** 2 / fwhm ** 2))
        w = b * (0.7 + 0.3 / (a + 0.01))
        u = 2.0 * np.sqrt(np.log(2.0)) * np.where(t > 0, t, 0.0)
        aw = np.exp(-(u / (fwhm + a * u)) ** 2)
        g0 = np.exp(-(u / fwhm) ** 2)
        tail = np.where(t > 0, w * (aw - g0), 0.0)
        return amplitude * (sgl + tail)

    @staticmethod
    def A_SGL_height_to_area(height, fwhm, fraction, a, b):
        """Numeric area of the A*SGL profile over center +/- 10*FWHM."""
        if fwhm <= 0:
            return 0.0
        x = np.linspace(-10.0 * fwhm, 10.0 * fwhm, 2001)
        y = PeakFunctions.A_SGL(x, 0.0, 1.0, fwhm, fraction, a, b)
        return float(height * trapz(y, x))

    @staticmethod
    def A_SGL_area_to_height(area, fwhm, fraction, a, b):
        """Inverse of A_SGL_height_to_area."""
        unit_area = PeakFunctions.A_SGL_height_to_area(1.0, fwhm, fraction, a, b)
        return float(area / unit_area) if unit_area > 0 else 0.0

    @staticmethod
    def A_GL_Area(x, center=0.0, area=1.0, fwhm=1.0, fraction=30.0, a=0.2, b=0.4):
        """Area-based A*GL: 'area' is the numeric integral of the profile over
        center +/- 10*FWHM (see A_GL_height_to_area); the apex height is derived."""
        height = PeakFunctions.A_GL_area_to_height(area, fwhm, fraction, a, b)
        return PeakFunctions.A_GL(x, center, height, fwhm, fraction, a, b)

    @staticmethod
    def A_SGL_Area(x, center=0.0, area=1.0, fwhm=1.0, fraction=30.0, a=0.2, b=0.4):
        """Area-based A*SGL: 'area' is the numeric integral of the profile over
        center +/- 10*FWHM; the apex height is derived."""
        height = PeakFunctions.A_SGL_area_to_height(area, fwhm, fraction, a, b)
        return PeakFunctions.A_SGL(x, center, height, fwhm, fraction, a, b)

    @staticmethod
    def A_GL_height_to_area(height, fwhm, fraction, a, b):
        """Numeric area of the A*GL profile, integrated over center +/- 10*FWHM
        (the tail is asymptotically non-zero, so a cutoff is required - CasaXPS
        quantifies these shapes over the displayed region in the same spirit)."""
        if fwhm <= 0:
            return 0.0
        x = np.linspace(-10.0 * fwhm, 10.0 * fwhm, 2001)
        y = PeakFunctions.A_GL(x, 0.0, 1.0, fwhm, fraction, a, b)
        return float(height * trapz(y, x))

    @staticmethod
    def A_GL_area_to_height(area, fwhm, fraction, a, b):
        """Inverse of A_GL_height_to_area."""
        unit_area = PeakFunctions.A_GL_height_to_area(1.0, fwhm, fraction, a, b)
        return float(area / unit_area) if unit_area > 0 else 0.0

    @staticmethod
    def calculate_rsd_BEF_v1_6(y_experimental, y_fitted):
        residuals = y_experimental - y_fitted
        n = len(residuals)
        denominator = y_experimental
        term = (residuals / np.sqrt(denominator)) ** 2
        sum_term = np.sum(term)
        rsd = np.sqrt(sum_term / n)

        # rsd2 = np.sqrt(np.mean(residuals ** 2)) / np.mean(y_experimental) * 100
        # print(f"RSD: {rsd2}")
        return rsd

    @staticmethod
    def calculate_rsd_BEF_v1_71(y_experimental, y_fitted):
        """
        Calculate weighted RSD for XPS data using Poisson statistics weighting.
        Returns RSD as a percentage.
        """
        residuals = y_experimental - y_fitted

        # Protect against zero/negative values (common in XPS background regions)
        safe_denominator = np.maximum(y_experimental, 1.0)

        # Calculate weighted residuals (Poisson weighting: 1/sqrt(signal))
        weighted_residuals = residuals / np.sqrt(safe_denominator)

        # Calculate weighted RMS error
        weighted_rms = np.sqrt(np.mean(weighted_residuals ** 2))

        # Convert to relative percentage
        mean_signal = np.mean(y_experimental)
        if mean_signal > 0:
            rsd = (weighted_rms / np.sqrt(mean_signal)) * 100.0
        else:
            rsd = 0.0

        return rsd

    @staticmethod
    def calculate_rsd(y_experimental, y_fitted):
        """
        Calculate all three RSD metrics for comparison.
        Returns tuple: (old_rsd, normalized_chi, rsd_percent)
        """
        old_rsd = PeakFunctions.calculate_rsd_old(y_experimental, y_fitted)
        norm_chi = PeakFunctions.calculate_normalized_chi(y_experimental, y_fitted)
        rsd_pct = PeakFunctions.calculate_rsd_percent(y_experimental, y_fitted)
        return old_rsd, norm_chi, rsd_pct

    @staticmethod
    def calculate_rsd_old(y_experimental, y_fitted):
        """
        Original weighted RSD calculation (pre-v1.7).
        """
        residuals = y_experimental - y_fitted
        safe_denominator = np.maximum(y_experimental, 1.0)
        weighted_residuals = residuals / np.sqrt(safe_denominator)
        weighted_rms = np.sqrt(np.mean(weighted_residuals ** 2))
        mean_signal = np.mean(y_experimental)
        if mean_signal > 0:
            return (weighted_rms / np.sqrt(mean_signal)) * 100.0
        return 0.0

    @staticmethod
    def calculate_normalized_chi(y_experimental, y_fitted):
        """
        Normalized chi (sqrt of reduced chi-squared) for XPS data.
        Uses Poisson statistics where variance = signal intensity.
        ~1.0 indicates a statistically good fit.
        """
        residuals = y_experimental - y_fitted
        n = len(residuals)
        variance = np.maximum(y_experimental, 1.0)
        chi_squared = np.sum(residuals ** 2 / variance)
        reduced_chi_sq = chi_squared / n
        return np.sqrt(reduced_chi_sq)

    @staticmethod
    def calculate_rsd_percent(y_experimental, y_fitted):
        """
        Relative Standard Deviation as percentage.
        RSD% = (RMSE / mean_signal) * 100
        """
        residuals = y_experimental - y_fitted
        rmse = np.sqrt(np.mean(residuals ** 2))
        mean_signal = np.mean(y_experimental)
        if mean_signal > 0:
            return (rmse / mean_signal) * 100.0
        return 0.0

    @staticmethod
    def get_doniach_sunjic_height(amplitude, sigma, gamma, skew):
        """
        Calculate the height of a Doniach-Sunjic profile.
        """
        model = lmfit.models.DoniachModel()
        params = model.make_params(amplitude=amplitude, center=0, sigma=sigma, gamma=gamma, asymmetry=skew)
        height = model.eval(params, x=0)
        return height

    @staticmethod
    def doniach_sunjic_height_to_amplitude(height, sigma, gamma, skew):
        """
        Convert height to area for a Doniach-Sunjic profile.
        """
        model = lmfit.models.DoniachModel()
        x = np.linspace(-10 * sigma, 10 * sigma, 1000)
        params = model.make_params(center=0, sigma=sigma, gamma=gamma, asymmetry=skew, amplitude=1)
        y = model.eval(params, x=x)
        max_y = np.max(y)
        amplitude = height / max_y
        return amplitude

    @staticmethod
    def doniach_sunjic_area_to_amplitude(area, sigma, gamma, skew):
        """
        Convert area to amplitude for a Doniach-Sunjic profile.

        Inverse of doniach_sunjic_height_to_area function.
        """
        model = lmfit.models.DoniachModel()

        # Convert area to float to ensure scalar value
        area = float(area)

        # Calculate the area of a unit-amplitude peak
        x_wide = np.linspace(-20 * sigma, 20 * sigma + 40 * sigma * skew, 2000)
        params = model.make_params(center=0, sigma=sigma, asymmetry=skew, gamma=gamma, amplitude=1.0)
        y = model.eval(params, x=x_wide)

        # Calculate area of unit-amplitude peak
        unit_area = float(trapz(y, x_wide))

        # Required amplitude to achieve desired area
        amplitude = area / unit_area if unit_area != 0 else 0

        return amplitude

    @staticmethod
    def doniach_sunjic_height_to_area(height, sigma, gamma, skew):
        model = lmfit.models.DoniachModel()

        # First, find amplitude that gives desired height
        x_test = np.array([0])  # Just evaluate at center
        params = model.make_params(center=0, sigma=sigma, asymmetry=skew, amplitude=1)
        max_y = model.eval(params, x=x_test)[0]
        amplitude = height / max_y

        # Now calculate the area with this amplitude
        x_wide = np.linspace(-20 * sigma, 20 * sigma + 40 * sigma * skew, 2000)
        y = model.eval(params, x=x_wide)
        y = y * amplitude  # Scale by our calculated amplitude

        # Numerical integration to get area
        area = trapz(y, x_wide)

        return area  # Return the actual integrated area

    @staticmethod
    def doniach_sunjic_area_to_height_OLD(area, sigma, gamma, skew):
        model = lmfit.models.DoniachModel()

        # First, create a peak with known amplitude and get its height at center
        test_amplitude = 1.0
        params = model.make_params(center=0, sigma=sigma, asymmetry=skew, gamma=gamma, amplitude=test_amplitude)

        # Get height at center
        center_height = model.eval(params, x=np.array([0]))[0]

        # Get area of this test peak
        x_wide = np.linspace(-20 * sigma, 20 * sigma + 40 * sigma * skew, 2000)
        y_test = model.eval(params, x=x_wide)
        test_area = trapz(y_test, x_wide)

        # Scale factor: area per unit height
        area_per_unit_height = test_area / center_height

        # Calculate required height for desired area
        height = float(area) / float(area_per_unit_height) if area_per_unit_height != 0 else 0

        return height

    @staticmethod
    def doniach_sunjic_area_to_height(area, sigma, gamma, skew):
        """Convert area to height for a Doniach-Sunjic profile using a two-step approach."""
        if sigma <= 0 or area <= 0:
            return 0

        model = lmfit.models.DoniachModel()

        # Step 1: Calculate amplitude that gives desired area
        # Use wider x-range that adapts to skew parameter
        x_range = max(20 * sigma, 5 * sigma * (1 + 5 * abs(skew)))
        x_wide = np.linspace(-x_range, x_range + 2 * x_range * skew, 2000)

        # Get area for a unit amplitude peak
        params = model.make_params(center=0, sigma=sigma, asymmetry=skew, gamma=gamma, amplitude=1.0)
        y_unit = model.eval(params, x=x_wide)
        unit_area = trapz(y_unit, x_wide)

        # Calculate required amplitude
        if abs(unit_area) < 1e-10:
            return 0
        amplitude = area / unit_area

        # Step 2: Calculate height at center with this amplitude
        height = model.eval(params, x=np.array([0]))[0] * amplitude

        return height

    @staticmethod
    def calculate_actual_fwhm(x_values, position, height, grid_fwhm, lg_ratio, area, sigma, gamma, skew, model):
        """Calculate the actual FWHM from the peak shape."""
        # Create a high-resolution x range around the peak for accurate FWHM measurement
        x_range = 10 * grid_fwhm
        x_high_res = np.linspace(position - x_range / 2, position + x_range / 2, 1000)

        # Generate peak shape based on the model
        if model in ["Voigt (Area, L/G, \u03c3)", "Voigt (Area, \u03c3, \u03b3)"]:
            peak_model = lmfit.models.VoigtModel()
            sigma_val = sigma / 2.355
            gamma_val = gamma / 2
            amplitude = height / peak_model.eval(center=0, amplitude=1, sigma=sigma_val, gamma=gamma_val, x=0)
            params = peak_model.make_params(center=position, amplitude=amplitude, sigma=sigma_val, gamma=gamma_val)
            y_values = peak_model.eval(params, x=x_high_res)
        elif model in ["Voigt (Area, L/G, \u03c3, S)"]:
            peak_model = PeakFunctions.create_skewed_voigt_model()
            params = peak_model.make_params(center=position, amplitude=area, sigma=sigma / 2.355, gamma=gamma / 2,
                                            skew=skew)
            y_values = peak_model.eval(params, x=x_high_res)
        elif model == "DS (A, \u03c3, \u03b3)":
            peak_model = lmfit.models.DoniachModel()
            params = peak_model.make_params(center=position, amplitude=area, sigma=sigma, gamma=gamma, asymmetry=skew)
            y_values = peak_model.eval(params, x=x_high_res)
        elif model == "ExpGauss.(Area, \u03c3, \u03b3)":
            peak_model = lmfit.models.ExponentialGaussianModel()
            params = peak_model.make_params(center=position, amplitude=area, sigma=sigma, gamma=gamma)
            y_values = peak_model.eval(params, x=x_high_res)
        elif model == "Pseudo-Voigt (Area)":
            peak_model = lmfit.models.PseudoVoigtModel()
            amplitude = height / peak_model.eval(center=0, amplitude=1, sigma=grid_fwhm / 2, fraction=lg_ratio / 100,
                                                 x=0)
            params = peak_model.make_params(center=position, amplitude=amplitude, sigma=grid_fwhm / 2,
                                            fraction=lg_ratio / 100)
            y_values = peak_model.eval(params, x=x_high_res)
        elif model in ["LA (Area, \u03c3, \u03b3)", "LA (Area, \u03c3/\u03b3, \u03b3)"]:
            y_values = PeakFunctions.LA(x_high_res, position, area, grid_fwhm, sigma, gamma)
        elif model in ["LA*G (Area, \u03c3/\u03b3, \u03b3)"]:
            y_values = PeakFunctions.LAxG(x_high_res, position, area, grid_fwhm, sigma, gamma, skew)
        elif model == "A*GL (Area, a, b)":
            # sigma/gamma grid columns hold the asymmetry parameters a and b
            y_values = PeakFunctions.A_GL(x_high_res, position, height, grid_fwhm, lg_ratio, sigma, gamma)
        elif model == "A*SGL (Area, a, b)":
            y_values = PeakFunctions.A_SGL(x_high_res, position, height, grid_fwhm, lg_ratio, sigma, gamma)
        elif model == "LF (Area, σ, γ, w)":
            # skew grid column holds the damping width w
            y_values = PeakFunctions.LF(x_high_res, position, area, grid_fwhm, sigma, gamma, skew)
        elif model == "DL (A, σ, γ, aDL)":
            # skew grid column holds the asymmetry a_dl
            y_values = PeakFunctions.DL(x_high_res, position, area, sigma, gamma, skew)
        elif model == "TLA (A, μ, α, Wg)":
            # sigma column = mu, gamma column = alpha, W_g/skew column = wg
            y_values = PeakFunctions.TLA(x_high_res, position, area, grid_fwhm, sigma, skew, gamma)
        elif model == "GL (Height)":
            y_values = PeakFunctions.gauss_lorentz(x_high_res, position, grid_fwhm, lg_ratio, height)
        elif model == "SGL (Height)":
            y_values = PeakFunctions.S_gauss_lorentz(x_high_res, position, grid_fwhm, lg_ratio, height)
        elif model == "GL (Area)":
            y_values = PeakFunctions.gauss_lorentz_Area(x_high_res, position, area, grid_fwhm, lg_ratio)
        elif model == "SGL (Area)":
            y_values = PeakFunctions.S_gauss_lorentz_Area(x_high_res, position, area, grid_fwhm, lg_ratio)
        elif model in ["Voigt (Area)", "Voigt (Area, L/G, S)"]:
            return grid_fwhm  # The fwhm parameter is already the actual FWHM
        elif model == "D-parameter":
            return grid_fwhm  # Return grid FWHM for D-parameter
        else:
            return grid_fwhm  # Return grid FWHM for unknown models

        # Calculate the FWHM from the peak shape
        peak_max = np.max(y_values)
        half_max = peak_max / 2

        # Find crossing points
        above_half_max = y_values >= half_max
        crossing_indices = np.where(np.diff(above_half_max))[0]

        if len(crossing_indices) >= 2:
            # Linear interpolation to find more accurate crossing points
            x1, x2 = crossing_indices[0], crossing_indices[-1]

            # Left crossing
            y1, y2 = y_values[x1], y_values[x1 + 1]
            x_left = x_high_res[x1] + (half_max - y1) * (x_high_res[x1 + 1] - x_high_res[x1]) / (y2 - y1)

            # Right crossing
            y1, y2 = y_values[x2], y_values[x2 + 1]
            x_right = x_high_res[x2] + (half_max - y1) * (x_high_res[x2 + 1] - x_high_res[x2]) / (y2 - y1)

            actual_fwhm = x_right - x_left
        else:
            # Fallback to grid FWHM if crossing points can't be found
            actual_fwhm = grid_fwhm

        return actual_fwhm

    # In Peak_Functions.py, add to PeakFunctions class:
    @staticmethod
    def DS_G(x, center, amplitude, gamma, skew, sigma):
        """
        Doniach-Sunjic function convoluted with a Gaussian.

        Parameters:
        x : array - Energy values
        center : float - Peak position
        amplitude : float - Area of the peak
        gamma : float - DS width parameter (Grid 8)
        skew : float - DS asymmetry parameter (Grid 9, alpha in equation)
        sigma : float - Width of the Gaussian function (Grid 7)
        """

        # Define the DS function
        def ds_func(x):
            x = -x
            # Avoid numerical instabilities
            skew_safe = np.clip(skew, 0.001, 0.999)

            denominator = (gamma ** 2 + x ** 2) ** ((1 - skew_safe) / 2)
            arctangent = np.arctan2(x, gamma)
            cosine_term = np.cos(np.pi * skew_safe / 2 + (1 - skew_safe) * arctangent)

            return cosine_term / denominator

        # Define the Gaussian function
        def gaussian(x, fwhm):
            return np.exp(-4 * np.log(2) * (x / fwhm) ** 2)

        # Create high-resolution x array centered at 0
        x_range = max(x.max() - x.min(), 4 * (gamma + sigma))
        x_high_res = np.linspace(-x_range / 2, x_range / 2, len(x) * 4)

        # Calculate DS and Gaussian
        ds = ds_func(x_high_res)
        gauss = gaussian(x_high_res, sigma)
        gauss = gauss / np.sum(gauss)  # Normalize

        # Perform convolution
        convolved = convolve(ds, gauss, mode='same')

        # Interpolate to original x grid
        peak_shape = np.interp(x - center, x_high_res, convolved)

        # Calculate area for normalization
        sort_idx = np.argsort(x)
        x_sorted = x[sort_idx]
        peak_shape_sorted = peak_shape[sort_idx]
        unit_area = abs(trapz(peak_shape_sorted, x_sorted))

        # Scale to achieve the requested amplitude
        height = amplitude / unit_area if unit_area != 0 else 0

        return height * peak_shape


class OtherCalc:
    @staticmethod
    def smooth_and_differentiate(x_values, y_values, smooth_width=2.0, pre_smooth=1, diff_width=1.0, post_smooth=1, algorithm="Gaussian"):
        from scipy.ndimage import gaussian_filter
        from scipy.signal import savgol_filter, wiener
        import numpy as np

        # Smoothing function based on algorithm
        def apply_smooth(data, width, algorithm):
            if algorithm == "Gaussian":
                return gaussian_filter(data, width)
            elif algorithm == "Savitsky-Golay":
                window = int(width * 10) if int(width * 10) % 2 == 1 else int(width * 10) + 1
                return savgol_filter(data, window, 3)
            elif algorithm == "Moving Average":
                window = int(width * 10)
                return np.convolve(data, np.ones(window)/window, mode='same')
            elif algorithm == "Wiener":
                return wiener(data, int(width * 10))
            else:  # "None"
                return data

        # Pre-smoothing passes
        smoothed = y_values.copy()
        for _ in range(int(pre_smooth)):
            smoothed = apply_smooth(smoothed, smooth_width, algorithm)

        # Calculate derivative
        derivative = -1 * np.gradient(smoothed, x_values)

        # Post-smoothing passes
        for _ in range(int(post_smooth)):
            derivative = apply_smooth(derivative, diff_width, algorithm)

        # Normalize derivative to data range
        data_range = np.max(y_values) - np.min(y_values)
        deriv_range = np.max(derivative) - np.min(derivative)
        normalized_deriv = ((derivative - np.min(derivative)) / deriv_range * data_range) + np.min(y_values)

        return normalized_deriv
