# KherveFitting - XPS Data Analysis Software
# Copyright (C) 2024-2026 Gwilherm Kerherve <g.kerherve@ic.ac.uk>
#
# KherveFitting is dual-licensed:
#   - GNU GPL v3.0 (see LICENSE-GPL.txt) for open-source use
#   - Commercial Licence (see LICENSE-COMMERCIAL.txt) for proprietary use
# SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-KherveFitting-Commercial
#
# KherveOS port: libraries/Fit_Uncertainty.py (KherveFitting-AI, dev-AI v1.93).
# Every function that does not build a wx window is copied unchanged (peak
# links as lmfit expressions, covariance and Monte Carlo errors, storing them
# on the peaks, the results-row fields, the peak-grid hover text, the report
# rows). The wx parts (tooltips binding, Monte Carlo dialogs and windows, the
# results-grid columns) are replaced at the end of the file by headless
# versions: run_monte_carlo(window, n_runs), atomic_percent_errors on the
# results table data, errors_by_peak / grid_tooltips for the page.
# Generated by SCRATCH/sync/gen_unc.py.
"""
Uncertainties of fitted peak parameters, and the peak links they depend on.

Three pieces, used by Functions.fit_peaks and the Fitting window:

1. ``apply_peak_links`` - a constraint such as ``A*0.5`` or ``A+1.5#0.2`` on a
   peak's Position, Area, FWHM, Height or L/G used to be turned into narrow
   numeric bounds, computed from peak A's value *before* the fit. The linked
   parameter then sat pinned on those bounds: it did not follow A during the
   fit, and its uncertainty came out as ~0. Here the link becomes a real lmfit
   expression, ``target = A op k``, with ``k`` allowed the same range as before
   (``value +/- tolerance``), so the fitted doublet partner follows A exactly
   and inherits A's uncertainty.

2. ``covariance_errors`` - 1-sigma errors from the fit's covariance matrix
   (lmfit scales it by the reduced chi-square, scale_covar=True). Position,
   Height, FWHM, L/G and Area are pushed through the SAME formulas that fill
   the peak grid (``peak_quantities``), by a numerical Jacobian, so derived
   values (Voigt FWHM and height, DS area, ...) and linked peaks get correct
   errors.

3. ``monte_carlo_errors`` - refits the spectrum many times with the residuals
   resampled onto the best fit (a weighted residual bootstrap). Slower, but
   does not assume the errors are small and linear, which matters for
   strongly overlapping peaks. The background is held fixed. Works on the
   last fit, or on a peak table that was never fitted (``_reference_fit``).
   The results window adds the correlation matrix and scatter plots; the
   full method is the Uncertainties page of the User Guide (the "How does
   it work?" button opens it).

Errors are stored on each peak as ``peak['Errors']``::

    {'method': 'covariance' | 'monte carlo (N)',
     'Position': 0.012, 'Area': 35.1, 'FWHM': 0.02, 'Height': 12.0, 'L/G': 1.4,
     'status': {'Area': 'linked to A', 'FWHM': 'fixed', ...}}

A quantity whose error cannot be given is left out; its status says why.
"""

import re
import numpy as np

from .numberformat import format_intensity
from .peak_functions import PeakFunctions

QUANTITIES = ('Position', 'Height', 'FWHM', 'L/G', 'Area')

# ---------------------------------------------------------------------------
# 1. Peak links -> lmfit expressions
# ---------------------------------------------------------------------------

# Models whose lmfit 'amplitude' IS the peak area (others use 'area', or an
# amplitude that is not an area: DS, and the Height models).
_AMPLITUDE_IS_AREA = {
    "ExpGauss.(Area, σ, γ)", "LA (Area, σ, γ)", "LF (Area, σ, γ, w)",
    "DL (A, σ, γ, aDL)", "TLA (A, μ, α, Wg)", "DS*G (A, σ, γ, S)",
    "LA (Area, σ/γ, γ)", "LA*G (Area, σ/γ, γ)",
}
_HEIGHT_MODELS = {"GL (Height)", "SGL (Height)", "SB (Height)"}
# Models whose 'fraction' parameter is the grid's L/G value, in the same units
_FRACTION_IS_LG = {
    "GL (Area)", "SGL (Area)", "GL (Height)", "SGL (Height)", "SB (Height)",
    "Voigt (Area)", "Voigt (Area, L/G, S)", "A*GL (Area, a, b)", "A*SGL (Area, a, b)",
    "LA (Area, σ/γ, γ)", "LA*G (Area, σ/γ, γ)",
}

# grid column -> quantity name
_LINK_COLUMNS = {2: 'Position', 3: 'Height', 4: 'FWHM', 5: 'L/G', 6: 'Area'}
# Line-shape columns -> the lmfit parameter they hold (same name in every
# model that has it). Linked only between peaks of the same model. The grid
# may show a scaled value (Voigt: Gaussian FWHM = 2.355 sigma, 2 gamma); the
# scale is read from the peak itself, so no per-model table is needed.
_SHAPE_COLUMNS = {7: ('sigma', 'σ'), 8: ('gamma', 'γ'), 9: ('skew', 'skew')}

# Same tolerances parse_constraints() gives the plain forms, so a link allows
# exactly the range it allowed before - it now follows the fitted reference.
_SIMPLE_TOL_ADD = 0.05
_SIMPLE_TOL_MUL = 0.0001

_LINK_RE = re.compile(r'^([A-Z])([+\-*/])(\d+\.?\d*)(?:#([\d.]+))?$')


def _lmfit_name(params, prefix, model, quantity):
    """The lmfit parameter holding ``quantity`` for this peak, or None when the
    model has no single parameter for it (then the old bounds stay)."""
    def usable(name):
        p = params.get(name)
        return p is not None and p.expr is None
    if quantity == 'Position':
        return f'{prefix}center' if usable(f'{prefix}center') else None
    if quantity == 'Area':
        if usable(f'{prefix}area'):
            return f'{prefix}area'
        if model in _AMPLITUDE_IS_AREA and usable(f'{prefix}amplitude'):
            return f'{prefix}amplitude'
        return None
    if quantity == 'FWHM':
        return f'{prefix}fwhm' if usable(f'{prefix}fwhm') else None
    if quantity == 'Height':
        if model in _HEIGHT_MODELS and usable(f'{prefix}amplitude'):
            return f'{prefix}amplitude'
        return None
    if quantity == 'L/G':
        if model in _FRACTION_IS_LG and usable(f'{prefix}fraction'):
            return f'{prefix}fraction'
        # Voigt (Area, L/G, σ[, S]): L/G itself is the fitted 'lg' (%)
        if usable(f'{prefix}lg'):
            return f'{prefix}lg'
        return None
    return None


def _peak_index_by_id(grid, peak_id):
    for row in range(0, grid.GetNumberRows(), 2):
        if grid.GetCellValue(row, 0) == peak_id:
            return row // 2
    return None


def apply_peak_links(params, grid, num_peaks):
    """Turn in-sheet peak links into lmfit expressions (see module docstring).

    Returns ``{(peak_index, quantity): 'linked to A'}`` for the links made.
    A link that cannot be expressed (different units, a model without that
    parameter, a reference to another core level, a loop A->B->A) keeps the
    bounds parse_constraints() already gave it.
    """
    models = [grid.GetCellValue(i * 2, 13) for i in range(num_peaks)]

    def usable(name):
        p = params.get(name)
        return p is not None and p.expr is None

    wanted = []   # (i, quantity, target, ref_index, ref_name, op, value, tol, exact)
    columns = [(c, q, None) for c, q in _LINK_COLUMNS.items()] + \
              [(c, q, pname) for c, (pname, q) in _SHAPE_COLUMNS.items()]
    for i in range(num_peaks):
        prefix = f'peak{i}_'
        for col, quantity, pname in columns:
            m = _LINK_RE.match(grid.GetCellValue(i * 2 + 1, col).strip())
            if not m:
                continue
            ref_id, op, value, tol = m.groups()
            j = _peak_index_by_id(grid, ref_id)
            if j is None or j == i or j >= num_peaks:
                continue
            # Height, L/G and the line-shape values only between peaks of the
            # same model (units differ)
            if (quantity in ('Height', 'L/G') or pname) and models[i] != models[j]:
                continue
            if pname:
                target, ref = f'{prefix}{pname}', f'peak{j}_{pname}'
                if not (usable(target) and usable(ref)):
                    continue
            else:
                target = _lmfit_name(params, prefix, models[i], quantity)
                ref = _lmfit_name(params, f'peak{j}_', models[j], quantity)
            if target is None or ref is None:
                continue
            value = float(value)
            if tol is not None:
                tol, exact = float(tol), False
            elif op in '+-':
                tol, exact = _SIMPLE_TOL_ADD, False
            else:
                tol, exact = _SIMPLE_TOL_MUL, True
            if op == '/' and value == 0:
                continue
            if pname and op in '+-':
                # An offset typed in grid units -> lmfit units
                try:
                    scale = float(grid.GetCellValue(i * 2, col)) / params[target].value
                except (ValueError, ZeroDivisionError):
                    continue
                if not np.isfinite(scale) or scale <= 0:
                    continue
                value, tol = value / scale, tol / scale
            wanted.append((i, quantity, target, j, ref, op, value, tol, exact))

    # Drop links that would make a loop (A = B*1 and B = A*1)
    depends = {w[2]: w[4] for w in wanted}

    def loops(start):
        seen, cur = set(), start
        while cur in depends:
            if cur in seen:
                return True
            seen.add(cur)
            cur = depends[cur]
        return cur == start

    linked = {}
    for (i, quantity, target, j, ref, op, value, tol, exact) in wanted:
        if loops(target):
            continue
        k_name = f'{target}_link'
        t_val, r_val = params[target].value, params[ref].value
        try:
            k0 = {'+': t_val - r_val, '-': r_val - t_val,
                  '*': t_val / r_val, '/': r_val / t_val}[op]
        except ZeroDivisionError:
            k0 = value
        if not np.isfinite(k0) or exact or not (value - tol <= k0 <= value + tol):
            k0 = value
        # Snap float noise (464.50 - 458.80 = 5.6999999999999886). A bounded
        # parameter just off the middle of its range has an internal value of
        # ~1e-13 in lmfit's arcsin transform, and MINPACK's step, relative to
        # it, is then too small to move it at all: the link would stay frozen.
        if abs(k0 - value) <= 1e-9 * max(1.0, abs(value)):
            k0 = value
        if exact:
            params.add(k_name, value=value, vary=False)
        else:
            params.add(k_name, value=k0, min=value - tol, max=value + tol, vary=True)
        # An expression parameter ignores its own bounds in the fit; clear
        # them so the pre-fit numeric window cannot clip the linked value.
        params[target].set(min=-np.inf, max=np.inf)
        params[target].set(expr=f'{ref} {op} {k_name}')
        linked[(i, quantity)] = f'linked to {_grid_id(grid, j)}'
    return linked


def _grid_id(grid, j):
    return grid.GetCellValue(j * 2, 0) or chr(ord('A') + j)


# ---------------------------------------------------------------------------
# 2. Peak quantities from a parameter set (the formulas of the peak grid)
# ---------------------------------------------------------------------------

def peak_quantities(model, pv, prefix, x=None):
    """Position / Height / FWHM / L/G / Area of one peak from parameter values.

    ``pv(name)`` returns a parameter value. Mirrors the conversions in
    Functions.fit_peaks that fill the peak grid (L/G in %); quantities that
    are only found numerically there (maximum over the data points) are left
    out, as their derivative is not meaningful.
    """
    P = PeakFunctions
    q = {}
    try:
        q['Position'] = pv(f'{prefix}center')
    except KeyError:
        return q

    def g(name):
        return pv(f'{prefix}{name}')

    try:
        if model in ("Voigt (Area, L/G, σ)", "Voigt (Area, σ, γ)"):
            a, s, gm = g('amplitude'), g('sigma'), g('gamma')
            q['Area'] = a
            q['Height'] = P.get_voigt_height(a, s, gm)
            q['FWHM'] = P.voigt_fwhm(s, gm)
            q['L/G'] = (2 * gm) / (s * 2.355 + 2 * gm) * 100
        elif model == "Voigt (Area, L/G, σ, S)":
            a, s, gm, sk = g('amplitude'), g('sigma'), g('gamma'), g('skew')
            q['Area'] = a
            q['Height'] = P.get_skewedvoigt_height(a, s, gm, sk)
            q['FWHM'] = P.skewed_voigt_fwhm(s, gm, sk)
            q['L/G'] = (2 * gm) / (s * 2.355 + 2 * gm) * 100
        elif model == "DS (A, σ, γ)":
            import lmfit
            a, c, s, gm, asym = g('amplitude'), g('center'), g('sigma'), g('gamma'), g('asymmetry')
            h = float(lmfit.models.DoniachModel().eval(
                x=np.array([c]), amplitude=a, center=c, sigma=s, gamma=gm, asymmetry=asym)[0])
            q['Height'] = h
            q['Area'] = P.doniach_sunjic_height_to_area(h, s, gm, asym)
            q['FWHM'] = 2 * s
        elif model == "Pseudo-Voigt (Area)":
            a, s, f = g('area'), g('sigma'), g('fraction') * 100
            q['Area'] = a
            q['FWHM'] = 2 * s
            q['L/G'] = f
            q['Height'] = P.get_pseudo_voigt_height(a, s, f)
        elif model in ("GL (Area)",):
            a, w, f = g('area'), g('fwhm'), g('fraction')
            q.update(Area=a, FWHM=w, **{'L/G': f})
            q['Height'] = a / (w * np.sqrt(np.pi / (4 * np.log(2))))
        elif model == "SGL (Area)":
            a, w, f = g('area'), g('fwhm'), g('fraction')
            q.update(Area=a, FWHM=w, **{'L/G': f})
            sig, gam = w / (2 * np.sqrt(2 * np.log(2))), w / 2
            q['Height'] = a / ((1 - f / 100) * sig * np.sqrt(2 * np.pi) + (f / 100) * np.pi * gam)
        elif model in ("GL (Height)", "SGL (Height)"):
            h, w, f = g('amplitude'), g('fwhm'), g('fraction')
            q.update(Height=h, FWHM=w, **{'L/G': f})
            q['Area'] = h * w * np.sqrt(np.pi / (4 * np.log(2)))
        elif model == "Voigt (Area)":
            a, w, f = g('area'), g('fwhm'), g('fraction')
            q.update(Area=a, FWHM=w, **{'L/G': f})
            c = q['Position']
            q['Height'] = float(P.voigt_simple(c, c, a, w, f))
        elif model == "Voigt (Area, L/G, S)":
            a, w, f, sk = g('area'), g('fwhm'), g('fraction'), g('skew')
            q.update(Area=a, FWHM=w, **{'L/G': f})
            c = q['Position']
            q['Height'] = float(P.voigt_simple_skewed(c, c, a, w, f, sk))
        elif model == "A*GL (Area, a, b)":
            a, w, f = g('area'), g('fwhm'), g('fraction')
            q.update(Area=a, FWHM=w, **{'L/G': f})
            q['Height'] = P.A_GL_area_to_height(a, w, f, g('a'), g('b'))
        elif model == "A*SGL (Area, a, b)":
            a, w, f = g('area'), g('fwhm'), g('fraction')
            q.update(Area=a, FWHM=w, **{'L/G': f})
            q['Height'] = P.A_SGL_area_to_height(a, w, f, g('a'), g('b'))
        elif model == "SB (Height)":
            q.update(Height=g('amplitude'), FWHM=g('fwhm'), **{'L/G': g('fraction')})
        elif model in _AMPLITUDE_IS_AREA:
            q['Area'] = g('amplitude')
            if f'{prefix}fwhm' in _names(pv):
                q['FWHM'] = g('fwhm')
            if model in ("LA (Area, σ/γ, γ)", "LA*G (Area, σ/γ, γ)"):
                q['L/G'] = g('fraction')
    except (KeyError, ValueError, ZeroDivisionError, FloatingPointError):
        pass
    return {k: float(v) for k, v in q.items() if v is not None and np.isfinite(v)}


def _names(pv):
    return getattr(pv, 'names', ())


class _Values:
    """``pv`` for peak_quantities over an lmfit Parameters (expressions
    re-evaluated on access)."""

    def __init__(self, params):
        self.params = params
        self.names = tuple(params.keys())

    def __call__(self, name):
        return self.params[name].value


def all_quantities(params, peaks, x=None):
    """{(i, quantity): value} for every peak. ``peaks`` = [(i, model), ...]."""
    # Re-evaluate every expression in dependency order first. lmfit evaluates
    # an expression lazily from the values its inputs last had, so after one
    # parameter is nudged a chain like amplitude = area = A_area * k (Voigt
    # linked to A) read the old area - the derivative came out 0 and the
    # linked peak's area error was 0.
    try:
        params.update_constraints()
    except Exception:
        pass
    pv = _Values(params)
    out = {}
    for i, model in peaks:
        for k, v in peak_quantities(model, pv, f'peak{i}_', x).items():
            out[(i, k)] = v
    return out


# ---------------------------------------------------------------------------
# Parameter status (why an error is missing or not trustworthy)
# ---------------------------------------------------------------------------

def _status(params, prefix, model, quantity, links):
    name = _lmfit_name_any(params, prefix, model, quantity)
    if name is None:
        return None
    p = params[name]
    if p.expr is not None and not p.expr.startswith(prefix):
        return links or 'linked'
    if not p.vary and p.expr is None:
        return 'fixed'
    # At a bound: closer to it than a small fraction of the value itself (a
    # fraction of the range would flag an area of 997 inside 0:1e7). Only
    # finite bounds count.
    near = max(abs(p.value) * 1e-4, 1e-12)
    for bound in (p.min, p.max):
        if np.isfinite(bound) and abs(p.value - bound) <= near:
            return 'at limit'
    return None


def _lmfit_name_any(params, prefix, model, quantity):
    # Like _lmfit_name, but also for parameters that are already expressions
    for cand in {'Position': ('center',), 'Area': ('area', 'amplitude'),
                 'FWHM': ('fwhm',), 'Height': ('amplitude',),
                 'L/G': ('fraction', 'lg')}.get(quantity, ()):
        if cand == 'amplitude' and quantity == 'Area' and model not in _AMPLITUDE_IS_AREA:
            continue
        if cand == 'amplitude' and quantity == 'Height' and model not in _HEIGHT_MODELS:
            continue
        if f'{prefix}{cand}' in params:
            return f'{prefix}{cand}'
    return None


def statuses(params, peaks, links):
    out = {}
    for i, model in peaks:
        for qty in QUANTITIES:
            st = _status(params, f'peak{i}_', model, qty, links.get((i, qty)))
            if st:
                out[(i, qty)] = st
    return out


# ---------------------------------------------------------------------------
# 2b. Covariance errors
# ---------------------------------------------------------------------------

def covariance_errors(result, peaks, x=None):
    """{(i, quantity): 1-sigma} from the fit covariance, through a numerical
    Jacobian of peak_quantities. Empty when the fit gave no covariance
    (Nelder-Mead, Powell, COBYLA, or a singular problem)."""
    covar = getattr(result, 'covar', None)
    names = list(getattr(result, 'var_names', None) or [])
    if covar is None and names:
        covar = numeric_covariance(result, names)
    if covar is None or not names:
        return {}
    covar = np.asarray(covar, dtype=float)
    if covar.shape != (len(names), len(names)) or not np.all(np.isfinite(covar)):
        return {}

    params = result.params.copy()
    base = all_quantities(params, peaks, x)
    grads = {k: np.zeros(len(names)) for k in base}
    for j, n in enumerate(names):
        p = params[n]
        v0 = p.value
        sd = np.sqrt(covar[j, j]) if covar[j, j] > 0 else 0.0
        h = max(sd * 1e-2, abs(v0) * 1e-7, 1e-12)
        p.value = v0 + h
        v_up = p.value
        up = all_quantities(params, peaks, x)
        p.value = v0 - h
        v_dn = p.value
        dn = all_quantities(params, peaks, x)
        p.value = v0
        step = v_up - v_dn
        if step == 0:
            continue
        for k in base:
            if k in up and k in dn:
                grads[k][j] = (up[k] - dn[k]) / step
    errors = {}
    for k, gvec in grads.items():
        var = float(gvec @ covar @ gvec)
        if var >= 0 and np.isfinite(var):
            errors[k] = np.sqrt(var)
    return errors


def numeric_covariance(result, names):
    """Covariance of the varied parameters at the best fit, from a numerical
    Jacobian of the weighted residual: inv(J^T J) * reduced chi-square - what
    lmfit reports with scale_covar=True.

    Needed because MINPACK's leastsq often returns no covariance when it
    starts at (or very near) the minimum - which is every refit the app does
    from the grid's converged values - and because Nelder-Mead, Powell and
    COBYLA never return one.
    """
    try:
        model, data = result.model, np.asarray(result.data, dtype=float)
        kws = dict(getattr(result, 'userkws', {}) or {})
        weights = getattr(result, 'weights', None)
        params = result.params.copy()

        def resid():
            r = model.eval(params, **kws) - data
            if weights is not None:
                r = r * weights
            return np.asarray(r, dtype=float)

        base = resid()
        ok = np.isfinite(base)
        J = np.zeros((int(ok.sum()), len(names)))
        for j, n in enumerate(names):
            p = params[n]
            v0 = p.value
            h = max(abs(v0) * 1e-6, 1e-9)
            p.value = v0 + h
            v_up = p.value
            up = resid()
            p.value = v0 - h
            v_dn = p.value
            dn = resid()
            p.value = v0
            if v_up == v_dn:
                return None
            J[:, j] = (up[ok] - dn[ok]) / (v_up - v_dn)
        nfree = ok.sum() - len(names)
        if nfree <= 0:
            return None
        redchi = float(np.sum(base[ok] ** 2)) / nfree
        cov = np.linalg.inv(J.T @ J) * redchi
        if not np.all(np.isfinite(cov)) or np.any(np.diag(cov) < 0):
            return None
        return cov
    except (np.linalg.LinAlgError, AttributeError, TypeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# 3. Monte Carlo (residual bootstrap)
# ---------------------------------------------------------------------------

def monte_carlo_errors(result, peaks, x, n_runs=100, progress=None, seed=None, stats=None):
    """Refit ``n_runs`` synthetic spectra (best fit + resampled residuals).

    Weighted residual bootstrap: with fit weights w_i (e.g. 1/sqrt(counts)
    for statistical weighting) the residuals are first standardised,
    e_i = w_i (y_i - f_i), resampled with replacement, and put back at each
    point on that point's own scale, y*_i = f_i + e*_i / w_i. So the noise
    on a peak top stays larger than on the baseline, as in the measurement.
    With uniform weights this is the plain residual bootstrap.

    ``progress(k, n)`` is called after each run; returning False stops early.
    ``stats``, a dict, receives per-quantity 'mean', 'p16', 'p84', the
    'reference' values, every refit's values ('runs', for the correlation
    matrix and scatter plots) and the number of 'failed' refits.
    Returns ({(i, quantity): std}, runs_done).
    """
    rng = np.random.default_rng(seed)
    y = np.asarray(result.data, dtype=float)
    best = np.asarray(result.best_fit, dtype=float)
    weights = getattr(result, 'weights', None)
    w = np.ones_like(best) if weights is None else np.asarray(weights, dtype=float)
    if w.shape != best.shape:
        w = np.ones_like(best)
    ok = np.isfinite(y) & np.isfinite(best) & np.isfinite(w) & (w > 0)
    std_resid = ((y - best) * w)[ok]
    if std_resid.size < 3:
        return {}, 0
    w_safe = np.where(ok, w, 1.0)
    kws = dict(getattr(result, 'userkws', {}) or {})
    reference = all_quantities(result.params, peaks, x)
    samples = {}
    runs = []   # one {(i, quantity): value} per successful refit
    done = failed = 0
    for k in range(n_runs):
        y_sim = best + rng.choice(std_resid, size=best.size, replace=True) / w_safe
        try:
            r = result.model.fit(y_sim, result.params.copy(), weights=weights,
                                 method='leastsq', nan_policy='omit',
                                 max_nfev=2000, **kws)
            q = all_quantities(r.params, peaks, x)
            for key, v in q.items():
                samples.setdefault(key, []).append(v)
            runs.append(q)
            done += 1
        except Exception:
            failed += 1
        if progress is not None and progress(k + 1, n_runs) is False:
            break
    errors = {key: float(np.std(v, ddof=1)) for key, v in samples.items() if len(v) >= 3}
    if stats is not None:
        stats['failed'] = failed
        stats['reference'] = reference
        stats['runs'] = runs
        for key, v in samples.items():
            if len(v) >= 3:
                a = np.asarray(v)
                stats.setdefault('mean', {})[key] = float(a.mean())
                stats.setdefault('p16', {})[key] = float(np.percentile(a, 15.87))
                stats.setdefault('p84', {})[key] = float(np.percentile(a, 84.13))
    return errors, done


# ---------------------------------------------------------------------------
# Storing on the peaks
# ---------------------------------------------------------------------------

def store_errors(existing_peaks, labels, errors, status, method, key='Errors'):
    """Put the errors on each peak's dict as ``peak[key]``: 'Errors' for the
    covariance estimate made by every fit, 'Errors_MC' for a Monte Carlo run.
    A new fit (key 'Errors') drops the Monte Carlo result of the old one."""
    for i, label in labels:
        peak = existing_peaks.get(label)
        if peak is None:
            continue
        entry = {'method': method}
        st = {}
        for qty in QUANTITIES:
            s = status.get((i, qty))
            if s:
                st[qty] = s
            if s == 'fixed':
                continue
            v = errors.get((i, qty))
            if v is not None and np.isfinite(v):
                entry[qty] = float(v)
                # An error larger than the value: the data do not determine
                # this quantity with this model (overlapping peaks, a bound,
                # a near-singular problem - see the User Guide, Uncertainties).
                if qty in ('Height', 'Area', 'FWHM') and not s:
                    try:
                        value = abs(float(peak.get(qty)))
                    except (TypeError, ValueError):
                        value = None
                    if value is not None and float(v) > value:
                        st[qty] = 'ill-conditioned'
        if st:
            entry['status'] = st
        peak[key] = entry
        if key == 'Errors':
            peak.pop('Errors_MC', None)


def format_pm(value, error):
    """'1234 ± 12' with the value rounded to the error's precision."""
    if error is None or not np.isfinite(error) or error <= 0:
        return None
    digits = max(0, 1 - int(np.floor(np.log10(error))))
    digits = min(digits, 8)
    return f"{value:.{digits}f} ± {error:.{digits}f}"


# ---------------------------------------------------------------------------
# Results grid: error columns appended after the 31 original ones
# ---------------------------------------------------------------------------

# (results-row key, quantity in peak['Errors'], column header)
RESULT_ERROR_COLUMNS = [
    ('Pos. Err', 'Position', '± Position\n(eV)'),
    ('Height Err', 'Height', '± Height\n(CPS)'),
    ('FWHM Err', 'FWHM', '± FWHM\n(eV)'),
    ('L/G Err', 'L/G', '± L/G\n(%)'),
    ('Area Err', 'Area', '± Area\n(CPS.eV)'),
    ('at. % Err', None, '± Atomic\n(%)'),
    ('Err Method', None, 'Error\nfrom'),
]
RESULT_ERROR_FIRST_COL = 31
RESULT_ERROR_COL_SIZES = [60, 60, 55, 55, 70, 60, 110]


def fmt_err(value):
    """An uncertainty with two significant figures ('0.0042', '35', '1200')."""
    if value is None or value == '':
        return ''
    try:
        v = float(value)
    except (TypeError, ValueError):
        return str(value)
    if not np.isfinite(v):
        return ''
    if v == 0:
        return '0'
    digits = max(0, 1 - int(np.floor(np.log10(abs(v)))))
    return f"{v:.{min(digits, 8)}f}"


def result_error_fields(peak):
    """Results-row keys for one fitted peak dict (its 'Errors' entry)."""
    peak = peak or {}
    errors = peak.get('Errors_MC') or peak.get('Errors') or {}
    status = errors.get('status', {})
    fields = {}
    for key, qty, _hdr in RESULT_ERROR_COLUMNS:
        if qty is None:
            continue
        if status.get(qty) == 'fixed':
            fields[key] = 'fixed'
        elif qty in errors:
            fields[key] = float(errors[qty])
        else:
            fields[key] = ''
    method = errors.get('method', '')
    ill = [q for q, st in status.items() if st == 'ill-conditioned' and q in errors]
    if ill and method:
        method += f" (ill-conditioned: {', '.join(ill)})"
    fields['Err Method'] = method
    return fields


def fill_result_error_cells(window, row, row_data):
    grid = window.results_grid
    need = RESULT_ERROR_FIRST_COL + len(RESULT_ERROR_COLUMNS)
    if grid.GetNumberCols() < need:
        return
    for k, (key, _qty, _hdr) in enumerate(RESULT_ERROR_COLUMNS):
        value = row_data.get(key, '')
        text = value if isinstance(value, str) else fmt_err(value)
        grid.SetCellValue(row, RESULT_ERROR_FIRST_COL + k, text)
        grid.SetReadOnly(row, RESULT_ERROR_FIRST_COL + k, True)


def fitted_peak_for(window, sheet_name, peak_name, peak_index=None):
    peaks = (window.Data.get('Core levels', {}).get(sheet_name, {})
             .get('Fitting', {}).get('Peaks', {}))
    if peak_name in peaks:
        return peaks[peak_name]
    if peak_index is not None and 0 <= peak_index < len(peaks):
        return list(peaks.values())[peak_index]
    return None


# ---------------------------------------------------------------------------
# Peak grid: hover a value to see its uncertainty
# ---------------------------------------------------------------------------

_GRID_QUANTITY = {2: 'Position', 3: 'Height', 4: 'FWHM', 5: 'L/G', 6: 'Area'}
_UNITS = {'Position': 'eV', 'FWHM': 'eV', 'L/G': '%', 'Height': '', 'Area': ''}

_METHOD_TEXT = {
    'covariance': ("covariance matrix of the fit (1σ, scaled by the reduced χ²;\n"
                   "Fitting window > Report ± > How does it work?)"),
}
_STATUS_TEXT = {
    'fixed': "Fixed: not fitted, so it has no uncertainty.",
    'at limit': ("At a limit of its constraint: the error may be underestimated -\n"
                 "widen the constraint and fit again."),
    'ill-conditioned': ("Ill-conditioned: the error is larger than the value, so the data\n"
                        "do not determine it with this model (it overlaps another peak,\n"
                        "or a bound holds it). Constrain it, report the sum of the\n"
                        "overlapping peaks, or run Monte Carlo."),
}


def grid_tooltip(window, row, col):
    """Tooltip text for a peak-grid cell, or '' when there is nothing to say."""
    qty = _GRID_QUANTITY.get(col)
    if qty is None or row % 2:
        return ''
    grid = window.peak_params_grid
    label = grid.GetCellValue(row, 1)
    sheet = window.sheet_combobox.GetValue()
    peak = fitted_peak_for(window, sheet, label, row // 2)
    errors = (peak or {}).get('Errors') or (peak or {}).get('Errors_MC')
    if not errors:
        return ''
    method = errors.get('method', '')
    status = errors.get('status', {}).get(qty)
    lines = []
    # The cell as the user sees it, then the error - no invented digits
    shown = grid.GetCellValue(row, col).strip()
    err = errors.get(qty)
    unit = _UNITS.get(qty, '')
    if status == 'fixed':
        lines.append(f"{qty}: {shown} (fixed)")
    elif err is not None:
        lines.append(f"{qty}: {shown} ± {fmt_err(err)} {unit}".rstrip())
    else:
        lines.append(f"{qty}: no uncertainty available")
    mc = (peak or {}).get('Errors_MC') or {}
    if status != 'fixed' and qty in mc:
        n = mc.get('method', '')[len('monte carlo'):].strip(' ()')
        lines.append(f"Monte Carlo ({n} refits): ± {fmt_err(mc[qty])} {unit}".rstrip())
    if method.startswith('monte carlo'):
        lines.append(f"From: Monte Carlo refits ({method[len('monte carlo'):].strip(' ()')} runs,"
                     " residual bootstrap, background fixed)")
    elif method in _METHOD_TEXT:
        lines.append(f"From: {_METHOD_TEXT[method]}")
    elif method:
        lines.append(f"Uncertainty {method}")
    if status and status.startswith('linked'):
        lines.append(f"{status[0].upper()}{status[1:]}: follows that peak's fitted value,\n"
                     "and carries its uncertainty.")
    elif status in _STATUS_TEXT:
        lines.append(_STATUS_TEXT[status])
    return "\n".join(lines)



# ---------------------------------------------------------------------------
# Fitting window actions
# ---------------------------------------------------------------------------

# The full method (covariance errors, Monte Carlo, why an error can exceed the
# value, a worked example, limits) is the "Uncertainties" page of the User
# Guide (libraries/HelpMenu/guide/ch_fitting.py); "How does it work?" opens it.

_ALLOWED_MODELS_EXCLUDED = ("D-parameter", "Unfitted", "Fermi", "")


def _reference_fit(window, parent):
    """The lmfit result Monte Carlo starts from: the last fit of this sheet,
    or - for a peak table that has not been fitted in this session - the
    model evaluated at the table's values (the table is not changed).
    Returns (fit_results, 'fit' | 'table') or (None, message)."""
    sheet = window.sheet_combobox.GetValue()
    fr = getattr(window, 'fit_results', None) or {}
    result = fr.get('result')
    if (result is not None and hasattr(result, 'model') and fr.get('sheet_name') == sheet
            and not getattr(result, 'evaluated_only', False)):
        return fr, 'fit'
    grid = getattr(window, 'peak_params_grid', None)
    if grid is None or grid.GetNumberRows() < 2:
        return None, "This core level has no peaks. Add peaks to the table first."
    if grid.GetCellValue(0, 13) in _ALLOWED_MODELS_EXCLUDED:
        return None, "Monte Carlo needs a fitted line shape (not D-parameter / Fermi / Unfitted)."
    # Evaluating the table rebuilds the peak dicts' covariance entry: keep
    # the errors a saved fit may carry.
    peaks = (window.Data.get('Core levels', {}).get(sheet, {})
             .get('Fitting', {}).get('Peaks', {}))
    kept = {k: v.get('Errors') for k, v in peaks.items() if v.get('Errors')}
    try:
        from .fitting import fit_peaks
        fit_peaks(window, grid, evaluate=True)
    except Exception as e:
        return None, f"Could not build the model from the peak table:\n{e}"
    for k, err in kept.items():
        if k in peaks:
            peaks[k]['Errors'] = err
    fr = getattr(window, 'fit_results', None) or {}
    if fr.get('sheet_name') != sheet or not hasattr(fr.get('result'), 'model'):
        return None, "Could not build the model from the peak table."
    return fr, 'table'


def mc_correlation(stats):
    """(keys, matrix) of Pearson correlations between every quantity that
    varied in all the refits. Fixed or exactly-linked values (zero spread)
    are left out."""
    runs = stats.get('runs') or []
    if len(runs) < 3:
        return [], np.zeros((0, 0))
    keys = [k for k in runs[0] if all(k in r for r in runs)]
    data = np.array([[r[k] for k in keys] for r in runs], dtype=float)
    sd = data.std(axis=0)
    keep = [j for j, v in enumerate(sd) if v > 1e-12 * max(1.0, abs(data[:, j].mean()))]
    keys = [keys[j] for j in keep]
    if len(keys) < 2:
        return keys, np.ones((len(keys), len(keys)))
    corr = np.corrcoef(data[:, keep], rowvar=False)
    # Order by peak, then Position / FWHM / Area / Height / L/G
    order = sorted(range(len(keys)),
                   key=lambda j: (keys[j][0], _REPORT_QTYS.index(keys[j][1])
                                  if keys[j][1] in _REPORT_QTYS else 9))
    keys = [keys[j] for j in order]
    return keys, corr[np.ix_(order, order)]


def _mc_key_name(stats, key):
    i, q = key
    return f"{stats.get('names', {}).get(i, i)} {q}"


def mc_summary_rows(stats):
    """Rows: peak, quantity, reference, MC mean, ±1σ, 16 %, 84 %, shift/σ."""
    rows = []
    ref, mean = stats.get('reference', {}), stats.get('mean', {})
    p16, p84, err = stats.get('p16', {}), stats.get('p84', {}), stats.get('errors', {})
    st = stats.get('status', {})
    for key in sorted(ref, key=lambda k: (k[0], _REPORT_QTYS.index(k[1]) if k[1] in _REPORT_QTYS else 9)):
        i, q = key
        name = stats.get('names', {}).get(i, i)
        if st.get(key) == 'fixed':
            rows.append([name, q, _report_value(q, ref[key]), '', 'fixed', '', '', '', 'fixed'])
            continue
        e = err.get(key)
        shift = ((mean[key] - ref[key]) / e) if e and key in mean else None
        rows.append([name, q, _report_value(q, ref[key]),
                     _report_value(q, mean[key]) if key in mean else '',
                     _report_err(e),
                     _report_value(q, p16[key]) if key in p16 else '',
                     _report_value(q, p84[key]) if key in p84 else '',
                     f"{shift:+.2f}" if shift is not None else '',
                     st.get(key, '')])
    return rows


def uncertainty_summary(window, sheet):
    """Plain-text table of every peak's value ± uncertainty on a sheet."""
    peaks = (window.Data['Core levels'].get(sheet, {}).get('Fitting', {}).get('Peaks', {}))
    lines = []
    method = ''
    for label, peak in peaks.items():
        errors = peak.get('Errors_MC') or peak.get('Errors') or {}
        method = errors.get('method', method)
        status = (peak.get('Errors') or {}).get('status', {})
        parts = []
        for qty in ('Position', 'FWHM', 'Area', 'Height', 'L/G'):
            if qty not in peak:
                continue
            if status.get(qty) == 'fixed':
                parts.append(f"{qty} {peak[qty]} (fixed)")
            elif qty in errors:
                parts.append(f"{qty} {peak[qty]} ± {fmt_err(errors[qty])}")
        if parts:
            lines.append(f"{label}:\n    " + "\n    ".join(parts))
    if not lines:
        return "No uncertainties available for this core level yet."
    head = {'covariance': "1σ from the covariance matrix (scaled by reduced χ²)"}.get(
        method, f"1σ, {method}")
    return head + "\n\n" + "\n".join(lines) + (
        "\n\nHover a value in the peak table to see its uncertainty; the Results\n"
        "table has ± columns (filled when a peak is added to the results).")


# ---------------------------------------------------------------------------
# Atomic % uncertainty (Results grid)
# ---------------------------------------------------------------------------


_REPORT_QTYS = ('Position', 'FWHM', 'Area', 'Height', 'L/G')


def _report_value(qty, v):
    """A value for the report table: readable even for areas of 1e10."""
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    if qty in ('Height', 'Area'):
        return f"{f:.4g}" if abs(f) >= 1e6 else format_intensity(f)
    return f"{f:.2f}"


def _report_err(e):
    if e is None:
        return ''
    try:
        f = float(e)
    except (TypeError, ValueError):
        return str(e)
    return f"{f:.2g}" if abs(f) >= 1e6 else fmt_err(f)


def _report_rows(window, sheet):
    """Rows: peak, then for each quantity value / ± covariance / ± Monte Carlo,
    then notes. Returns (rows, covariance method text, Monte Carlo method text)."""
    peaks = (window.Data['Core levels'].get(sheet, {}).get('Fitting', {}).get('Peaks', {}))
    rows, method, mc_method = [], '', ''
    for label, peak in peaks.items():
        errors = peak.get('Errors') or {}
        mc = peak.get('Errors_MC') or {}
        method = errors.get('method', method)
        mc_method = mc.get('method', mc_method)
        status = errors.get('status', {})
        cells = [label]
        notes = []
        for qty in _REPORT_QTYS:
            cells.append(_report_value(qty, peak.get(qty, '')))
            st = status.get(qty)
            if st == 'fixed':
                cells += ['fixed', 'fixed']
            else:
                cells.append(_report_err(errors.get(qty)))
                cells.append(_report_err(mc.get(qty)))
            if st and st != 'fixed':
                notes.append(f"{qty} {st}")
        cells.append('; '.join(notes))
        rows.append(cells)
    return rows, method, mc_method


# ---------------------------------------------------------------------------
# KherveOS: headless versions of the wx parts
# ---------------------------------------------------------------------------

def run_monte_carlo(window, n_runs=100, progress=None, seed=None):
    """run_monte_carlo without the dialogs: refit ``n_runs`` times (Monte
    Carlo residual bootstrap), store peak['Errors_MC'] on every peak and the
    statistics in window.mc_results[sheet] (as the desktop does).

    Returns the stats dict ('errors', 'done', 'requested', 'source', 'names',
    'status', 'sheet', 'mean', 'p16', 'p84', 'reference', 'runs', 'failed');
    raises ValueError with the desktop's message when it cannot run.
    """
    sheet = window.sheet_combobox.GetValue()
    fr, source = _reference_fit(window, None)
    if fr is None:
        raise ValueError(source)
    result = fr['result']
    peaks = fr.get('error_peaks') or []
    labels = fr.get('error_labels') or []
    x = fr.get('x_filtered')
    stats = {}
    errors, done = monte_carlo_errors(result, peaks, x, n_runs=int(n_runs), progress=progress,
                                      seed=seed, stats=stats)
    if done < 3:
        raise ValueError("Not enough refits finished to estimate uncertainties.")
    existing = window.Data['Core levels'][sheet]['Fitting']['Peaks']
    status = statuses(result.params, peaks, fr.get('peak_links') or {})
    store_errors(existing, labels, errors, status, f'monte carlo ({done})', key='Errors_MC')
    names = {i: lab for i, lab in labels}
    stats.update(errors=errors, done=done, requested=int(n_runs), source=source,
                 names=names, status=status, sheet=sheet)
    if not hasattr(window, 'mc_results') or window.mc_results is None:
        window.mc_results = {}
    window.mc_results[sheet] = stats
    window.fit_errors = errors_by_peak(window, sheet)
    return stats


def mc_report(stats):
    """The Monte Carlo results window as data: summary rows (peak, quantity,
    reference, MC mean, ±1σ, 16 %, 84 %, shift/σ, status) and the
    correlation matrix (names, matrix)."""
    keys, corr = mc_correlation(stats)
    return {
        'columns': ['Peak', 'Quantity', 'Fit value', 'MC mean', '± 1σ', '16 %', '84 %',
                    'Shift / σ', 'Status'],
        'rows': mc_summary_rows(stats),
        'corrNames': [_mc_key_name(stats, k) for k in keys],
        'corr': [[float(v) for v in row] for row in np.asarray(corr)],
        'done': stats.get('done'), 'requested': stats.get('requested'),
        'failed': stats.get('failed', 0), 'source': stats.get('source'),
    }


def report_table(window, sheet=None):
    """The "Report ±" window as data: columns, rows (_report_rows) and the
    covariance / Monte Carlo method texts."""
    sheet = sheet or window.sheet_combobox.GetValue()
    rows, method, mc_method = _report_rows(window, sheet)
    columns = ['Peak']
    for qty in _REPORT_QTYS:
        columns += [qty, f'± {qty} (cov.)', f'± {qty} (MC)']
    columns.append('Notes')
    return {'columns': columns, 'rows': rows, 'method': method, 'mcMethod': mc_method}


def errors_by_peak(window, sheet=None):
    """{peak index: {'Position': err, 'Height': err, 'FWHM': err, 'L/G': err,
    'Area': err, 'method': ..., 'status': {...}, 'mc': {...}}} for the current
    peak table, from peak['Errors'] (covariance, every fit) and
    peak['Errors_MC'] (Monte Carlo). Quantities without an error are absent."""
    sheet = sheet or window.sheet_combobox.GetValue()
    grid = window.peak_params_grid
    out = {}
    for row in range(0, grid.GetNumberRows(), 2):
        peak = fitted_peak_for(window, sheet, grid.GetCellValue(row, 1), row // 2) or {}
        errors = peak.get('Errors') or {}
        mc = peak.get('Errors_MC') or {}
        if not errors and not mc:
            continue
        entry = {q: float(errors[q]) for q in QUANTITIES if q in errors}
        entry['method'] = errors.get('method', '')
        if errors.get('status'):
            entry['status'] = dict(errors['status'])
        if mc:
            entry['mc'] = {q: float(mc[q]) for q in QUANTITIES if q in mc}
            entry['mcMethod'] = mc.get('method', '')
        out[row // 2] = entry
    return out


def grid_tooltips(window):
    """{(row, col): hover text} for every value cell of the peak table that
    has something to say (grid_tooltip for columns 2-6 of each value row)."""
    grid = window.peak_params_grid
    out = {}
    for row in range(0, grid.GetNumberRows(), 2):
        for col in _GRID_QUANTITY:
            text = grid_tooltip(window, row, col)
            if text:
                out[(row, col)] = text
    return out


def atomic_percent_errors(window, results_table_key, checked, total):
    """Fit_Uncertainty.atomic_percent_errors on the results table data.

    ``checked`` = [(label, normalised area), ...] of the ticked rows. Each
    row's area error ('Area Err', from the fit) is taken as independent and
    pushed through at% = n_i / sum(n); the area is the results grid's text
    (format_intensity), the error the grid's text (fmt_err), as on the
    desktop. Sets 'at. % Err' on every row ('' when it cannot be given).
    """
    peaks = window.Data.get(results_table_key, {}).get('Peak', {})
    if total <= 0:
        return
    rel = {}
    for label, n in checked:
        p = peaks.get(label, {})
        try:
            area = float(format_intensity(p.get('Area', '')))
            err = float(fmt_err(p.get('Area Err', '')))
            rel[label] = (n * err / area) if area else None
        except (TypeError, ValueError):
            rel[label] = None
    ticked = {label for label, _n in checked}
    for label, n in checked:
        if rel.get(label) is None:
            value = ''
        else:
            var = ((total - n) / total ** 2) ** 2 * rel[label] ** 2
            for j, _nj in checked:
                if j != label and rel.get(j) is not None:
                    var += (n / total ** 2) ** 2 * rel[j] ** 2
            value = 100.0 * float(np.sqrt(var))
        peaks[label]['at. % Err'] = value
    for label, p in peaks.items():
        if label not in ticked:
            p['at. % Err'] = ''
