"""More of the compound library (Qt-free): benzene and its derivatives,
and the medicines a pharmacist dispenses most, by what they treat.

Same contract as molecule_library.COMPOUNDS — key -> (name, SMILES,
category, formula it must give) — merged into it at import, so the
library tree lists them with the rest, and the tests build every one. Chirality
is not drawn (the SMILES reader ignores @), so a drug and its mirror
image are the same model here.

Copyright (C) 2026 Gwilherm Kerherve

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
"""

BENZENES = "Benzene derivatives"
POLYAROMATICS = "Polycyclic & fused aromatics"
PAIN = "Medicines: pain & inflammation"
ANTI_INFECTIVES = "Medicines: antibiotics, antifungals & antivirals"
HEART = "Medicines: heart & blood"
BRAIN = "Medicines: brain & nerves"
GUT = "Medicines: stomach, allergy & breathing"
HORMONES = "Medicines: diabetes, hormones & vitamins"
CATEGORIES = (BENZENES, POLYAROMATICS, PAIN, ANTI_INFECTIVES, HEART, BRAIN,
              GUT, HORMONES)

_NO2 = "[N+](=O)[O-]"

_ROWS = {
    BENZENES: [
        # one substituent
        ("fluorobenzene", "Fluorobenzene", "Fc1ccccc1", "C6H5F"),
        ("chlorobenzene", "Chlorobenzene", "Clc1ccccc1", "C6H5Cl"),
        ("bromobenzene", "Bromobenzene", "Brc1ccccc1", "C6H5Br"),
        ("iodobenzene", "Iodobenzene", "Ic1ccccc1", "C6H5I"),
        ("benzonitrile", "Benzonitrile", "N#Cc1ccccc1", "C7H5N"),
        ("anisole", "Anisole", "COc1ccccc1", "C7H8O"),
        ("acetophenone", "Acetophenone", "CC(=O)c1ccccc1", "C8H8O"),
        ("benzyl_alcohol", "Benzyl alcohol", "OCc1ccccc1", "C7H8O"),
        ("benzylamine", "Benzylamine", "NCc1ccccc1", "C7H9N"),
        ("benzyl_chloride", "Benzyl chloride", "ClCc1ccccc1", "C7H7Cl"),
        ("thiophenol", "Thiophenol", "Sc1ccccc1", "C6H6S"),
        ("benzenesulfonic_acid", "Benzenesulfonic acid",
         "OS(=O)(=O)c1ccccc1", "C6H6O3S"),
        ("phenylacetylene", "Phenylacetylene", "C#Cc1ccccc1", "C8H6"),
        ("propylbenzene", "Propylbenzene", "CCCc1ccccc1", "C9H12"),
        ("tert_butylbenzene", "tert-Butylbenzene", "CC(C)(C)c1ccccc1",
         "C10H14"),
        ("benzamide", "Benzamide", "NC(=O)c1ccccc1", "C7H7NO"),
        ("phenylacetic_acid", "Phenylacetic acid", "OC(=O)Cc1ccccc1",
         "C8H8O2"),
        ("benzoyl_chloride", "Benzoyl chloride", "ClC(=O)c1ccccc1",
         "C7H5ClO"),
        ("phenyl_isocyanate", "Phenyl isocyanate", "O=C=Nc1ccccc1",
         "C7H5NO"),
        ("n_methylaniline", "N-Methylaniline", "CNc1ccccc1", "C7H9N"),
        ("nn_dimethylaniline", "N,N-Dimethylaniline", "CN(C)c1ccccc1",
         "C8H11N"),
        ("acetanilide", "Acetanilide", "CC(=O)Nc1ccccc1", "C8H9NO"),
        ("phenylhydrazine", "Phenylhydrazine", "NNc1ccccc1", "C6H8N2"),
        ("benzotrifluoride", "Benzotrifluoride", "FC(F)(F)c1ccccc1",
         "C7H5F3"),
        # two rings joined
        ("benzophenone", "Benzophenone", "O=C(c1ccccc1)c1ccccc1",
         "C13H10O"),
        ("diphenyl_ether", "Diphenyl ether", "c1ccc(Oc2ccccc2)cc1",
         "C12H10O"),
        ("diphenylmethane", "Diphenylmethane", "c1ccc(Cc2ccccc2)cc1",
         "C13H12"),
        ("stilbene", "trans-Stilbene", "C(=Cc1ccccc1)c1ccccc1", "C14H12"),
        ("azobenzene", "Azobenzene", "N(=Nc1ccccc1)c1ccccc1", "C12H10N2"),
        ("benzil", "Benzil", "O=C(C(=O)c1ccccc1)c1ccccc1", "C14H10O2"),
        ("triphenylmethane", "Triphenylmethane",
         "C(c1ccccc1)(c1ccccc1)c1ccccc1", "C19H16"),
        ("triphenylphosphine", "Triphenylphosphine",
         "P(c1ccccc1)(c1ccccc1)c1ccccc1", "C18H15P"),
        # two substituents
        ("o_dichlorobenzene", "o-Dichlorobenzene", "Clc1ccccc1Cl",
         "C6H4Cl2"),
        ("m_dichlorobenzene", "m-Dichlorobenzene", "Clc1cccc(Cl)c1",
         "C6H4Cl2"),
        ("p_dichlorobenzene", "p-Dichlorobenzene", "Clc1ccc(Cl)cc1",
         "C6H4Cl2"),
        ("o_cresol", "o-Cresol", "Cc1ccccc1O", "C7H8O"),
        ("m_cresol", "m-Cresol", "Cc1cccc(O)c1", "C7H8O"),
        ("o_toluidine", "o-Toluidine", "Cc1ccccc1N", "C7H9N"),
        ("p_toluidine", "p-Toluidine", "Cc1ccc(N)cc1", "C7H9N"),
        ("p_nitrophenol", "p-Nitrophenol", f"Oc1ccc(cc1){_NO2}",
         "C6H5NO3"),
        ("p_nitrotoluene", "p-Nitrotoluene", f"Cc1ccc(cc1){_NO2}",
         "C7H7NO2"),
        ("p_nitroaniline", "p-Nitroaniline", f"Nc1ccc(cc1){_NO2}",
         "C6H6N2O2"),
        ("p_aminophenol", "p-Aminophenol", "Nc1ccc(O)cc1", "C6H7NO"),
        ("o_phenylenediamine", "o-Phenylenediamine", "Nc1ccccc1N",
         "C6H8N2"),
        ("p_phenylenediamine", "p-Phenylenediamine", "Nc1ccc(N)cc1",
         "C6H8N2"),
        ("phthalic_acid", "Phthalic acid", "OC(=O)c1ccccc1C(=O)O",
         "C8H6O4"),
        ("isophthalic_acid", "Isophthalic acid",
         "OC(=O)c1cccc(c1)C(=O)O", "C8H6O4"),
        ("terephthalic_acid", "Terephthalic acid",
         "OC(=O)c1ccc(cc1)C(=O)O", "C8H6O4"),
        ("phthalic_anhydride", "Phthalic anhydride",
         "O=C1OC(=O)c2ccccc12", "C8H4O3"),
        ("p_toluic_acid", "p-Toluic acid", "Cc1ccc(cc1)C(=O)O", "C8H8O2"),
        ("tosic_acid", "p-Toluenesulfonic acid",
         "Cc1ccc(cc1)S(=O)(=O)O", "C7H8O3S"),
        ("methyl_salicylate", "Methyl salicylate (wintergreen)",
         "COC(=O)c1ccccc1O", "C8H8O3"),
        ("anthranilic_acid", "Anthranilic acid", "Nc1ccccc1C(=O)O",
         "C7H7NO2"),
        ("paba", "p-Aminobenzoic acid (PABA)", "Nc1ccc(cc1)C(=O)O",
         "C7H7NO2"),
        ("sulfanilamide", "Sulfanilamide", "Nc1ccc(cc1)S(N)(=O)=O",
         "C6H8N2O2S"),
        ("p_benzoquinone", "p-Benzoquinone", "O=C1C=CC(=O)C=C1", "C6H4O2"),
        ("guaiacol", "Guaiacol", "COc1ccccc1O", "C7H8O2"),
        ("divinylbenzene", "p-Divinylbenzene", "C=Cc1ccc(C=C)cc1",
         "C10H10"),
        # three or more
        ("mesitylene", "Mesitylene", "Cc1cc(C)cc(C)c1", "C9H12"),
        ("pseudocumene", "1,2,4-Trimethylbenzene", "Cc1ccc(C)c(C)c1",
         "C9H12"),
        ("durene", "Durene", "Cc1cc(C)c(C)cc1C", "C10H14"),
        ("hexamethylbenzene", "Hexamethylbenzene",
         "Cc1c(C)c(C)c(C)c(C)c1C", "C12H18"),
        ("hexachlorobenzene", "Hexachlorobenzene",
         "Clc1c(Cl)c(Cl)c(Cl)c(Cl)c1Cl", "C6Cl6"),
        ("hexafluorobenzene", "Hexafluorobenzene",
         "Fc1c(F)c(F)c(F)c(F)c1F", "C6F6"),
        ("tnt", "TNT (2,4,6-trinitrotoluene)",
         f"Cc1c(cc(cc1{_NO2}){_NO2}){_NO2}", "C7H5N3O6"),
        ("picric_acid", "Picric acid",
         f"Oc1c(cc(cc1{_NO2}){_NO2}){_NO2}", "C6H3N3O7"),
        ("pyrogallol", "Pyrogallol", "Oc1cccc(O)c1O", "C6H6O3"),
        ("phloroglucinol", "Phloroglucinol", "Oc1cc(O)cc(O)c1", "C6H6O3"),
        ("gallic_acid", "Gallic acid", "OC(=O)c1cc(O)c(O)c(O)c1",
         "C7H6O5"),
        ("bht", "BHT (butylated hydroxytoluene)",
         "CC(C)(C)c1cc(C)cc(C(C)(C)C)c1O", "C15H24O"),
        ("bisphenol_a", "Bisphenol A", "CC(C)(c1ccc(O)cc1)c1ccc(O)cc1",
         "C15H16O2"),
        ("trimesic_acid", "Trimesic acid",
         "OC(=O)c1cc(cc(c1)C(=O)O)C(=O)O", "C9H6O6"),
    ],
    POLYAROMATICS: [
        ("phenanthrene", "Phenanthrene", "c1ccc2c(c1)ccc1ccccc12",
         "C14H10"),
        ("pyrene", "Pyrene", "c1cc2ccc3cccc4ccc(c1)c2c34", "C16H10"),
        ("tetracene", "Tetracene", "c1ccc2cc3cc4ccccc4cc3cc2c1", "C18H12"),
        ("pentacene", "Pentacene", "c1ccc2cc3cc4cc5ccccc5cc4cc3cc2c1",
         "C22H14"),
        ("chrysene", "Chrysene", "c1ccc2c(c1)ccc1c3ccccc3ccc21", "C18H12"),
        ("triphenylene", "Triphenylene", "c1ccc2c(c1)c1ccccc1c1ccccc21",
         "C18H12"),
        ("benzo_a_pyrene", "Benzo[a]pyrene",
         "c1ccc2c(c1)cc1ccc3cccc4ccc2c1c34", "C20H12"),
        ("perylene", "Perylene", "c1cc2cccc3c4cccc5cccc(c(c1)c23)c54",
         "C20H12"),
        ("coronene", "Coronene",
         "c1cc2ccc3ccc4ccc5ccc6ccc1c1c2c3c4c5c61", "C24H12"),
        ("azulene", "Azulene", "c1ccc2cccc2cc1", "C10H8"),
        ("fluorene", "Fluorene", "c1ccc2c(c1)Cc1ccccc12", "C13H10"),
        ("acenaphthylene", "Acenaphthylene", "C1=Cc2cccc3cccc1c23",
         "C12H8"),
        ("fluoranthene", "Fluoranthene", "c1ccc2c(c1)-c1cccc3cccc-2c13",
         "C16H10"),
        ("benzofuran", "Benzofuran", "c1ccc2occc2c1", "C8H6O"),
        ("benzothiophene", "Benzothiophene", "c1ccc2sccc2c1", "C8H6S"),
        ("isoquinoline", "Isoquinoline", "c1ccc2cnccc2c1", "C9H7N"),
        ("quinoxaline", "Quinoxaline", "c1ccc2nccnc2c1", "C8H6N2"),
        ("benzimidazole", "Benzimidazole", "c1ccc2[nH]cnc2c1", "C7H6N2"),
        ("benzoxazole", "Benzoxazole", "c1ccc2ocnc2c1", "C7H5NO"),
        ("carbazole", "Carbazole", "c1ccc2c(c1)[nH]c1ccccc12", "C12H9N"),
        ("dibenzofuran", "Dibenzofuran", "c1ccc2c(c1)oc1ccccc12",
         "C12H8O"),
        ("acridine", "Acridine", "c1ccc2nc3ccccc3cc2c1", "C13H9N"),
        ("phenazine", "Phenazine", "c1ccc2nc3ccccc3nc2c1", "C12H8N2"),
        ("xanthene", "Xanthene", "c1ccc2c(c1)Cc1ccccc1O2", "C13H10O"),
    ],
    PAIN: [
        ("naproxen", "Naproxen", "COc1ccc2cc(ccc2c1)C(C)C(=O)O",
         "C14H14O3"),
        ("diclofenac", "Diclofenac", "OC(=O)Cc1ccccc1Nc1c(Cl)cccc1Cl",
         "C14H11Cl2NO2"),
        ("ketoprofen", "Ketoprofen",
         "CC(C(=O)O)c1cccc(c1)C(=O)c1ccccc1", "C16H14O3"),
        ("indometacin", "Indometacin",
         "COc1ccc2n(C(=O)c3ccc(Cl)cc3)c(C)c(CC(=O)O)c2c1", "C19H16ClNO4"),
        ("celecoxib", "Celecoxib",
         "Cc1ccc(cc1)-c1cc(nn1-c1ccc(cc1)S(N)(=O)=O)C(F)(F)F",
         "C17H14F3N3O2S"),
        ("meloxicam", "Meloxicam",
         "CN1C(C(=O)Nc2ncc(C)s2)=C(O)c2ccccc2S1(=O)=O", "C14H13N3O4S2"),
        ("piroxicam", "Piroxicam",
         "CN1C(C(=O)Nc2ccccn2)=C(O)c2ccccc2S1(=O)=O", "C15H13N3O4S"),
        ("mefenamic_acid", "Mefenamic acid",
         "Cc1cccc(Nc2ccccc2C(=O)O)c1C", "C15H15NO2"),
        ("morphine", "Morphine", "CN1CCC23C4Oc5c3c(CC1C2C=CC4O)ccc5O",
         "C17H19NO3"),
        ("codeine", "Codeine", "COc1ccc2CC3N(C)CCC45C(Oc1c24)C(O)C=CC35",
         "C18H21NO3"),
        ("oxycodone", "Oxycodone",
         "COc1ccc2CC3N(C)CCC45C(Oc1c24)C(=O)CCC35O", "C18H21NO4"),
        ("tramadol", "Tramadol", "COc1cccc(c1)C1(O)CCCCC1CN(C)C",
         "C16H25NO2"),
        ("fentanyl", "Fentanyl",
         "CCC(=O)N(c1ccccc1)C1CCN(CCc2ccccc2)CC1", "C22H28N2O"),
        ("methadone", "Methadone",
         "CCC(=O)C(CC(C)N(C)C)(c1ccccc1)c1ccccc1", "C21H27NO"),
        ("lidocaine", "Lidocaine", "CCN(CC)CC(=O)Nc1c(C)cccc1C",
         "C14H22N2O"),
        ("benzocaine", "Benzocaine", "CCOC(=O)c1ccc(N)cc1", "C9H11NO2"),
        ("procaine", "Procaine", "CCN(CC)CCOC(=O)c1ccc(N)cc1",
         "C13H20N2O2"),
        ("hydrocortisone", "Hydrocortisone",
         "CC12CCC(=O)C=C1CCC1C2C(O)CC2(C)C1CCC2(O)C(=O)CO", "C21H30O5"),
        ("prednisolone", "Prednisolone",
         "CC12CC(O)C3C(CCC4=CC(=O)C=CC34C)C1CCC2(O)C(=O)CO", "C21H28O5"),
        ("dexamethasone", "Dexamethasone",
         "CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O)C(=O)CO",
         "C22H29FO5"),
        ("allopurinol", "Allopurinol", "O=c1[nH]cnc2[nH]ncc12",
         "C5H4N4O"),
    ],
    ANTI_INFECTIVES: [
        ("penicillin_g", "Penicillin G",
         "CC1(C)SC2C(NC(=O)Cc3ccccc3)C(=O)N2C1C(=O)O", "C16H18N2O4S"),
        ("amoxicillin", "Amoxicillin",
         "CC1(C)SC2C(NC(=O)C(N)c3ccc(O)cc3)C(=O)N2C1C(=O)O",
         "C16H19N3O5S"),
        ("ampicillin", "Ampicillin",
         "CC1(C)SC2C(NC(=O)C(N)c3ccccc3)C(=O)N2C1C(=O)O", "C16H19N3O4S"),
        ("flucloxacillin", "Flucloxacillin",
         "Cc1onc(c1C(=O)NC1C2SC(C)(C)C(N2C1=O)C(=O)O)-c1c(F)cccc1Cl",
         "C19H17ClFN3O5S"),
        ("cefalexin", "Cefalexin",
         "CC1=C(N2C(SC1)C(NC(=O)C(N)c1ccccc1)C2=O)C(=O)O", "C16H17N3O4S"),
        ("ciprofloxacin", "Ciprofloxacin",
         "OC(=O)c1cn(C2CC2)c2cc(N3CCNCC3)c(F)cc2c1=O", "C17H18FN3O3"),
        ("levofloxacin", "Levofloxacin",
         "CC1COc2c(N3CCN(C)CC3)c(F)cc3c(=O)c(C(=O)O)cn1c23",
         "C18H20FN3O4"),
        ("doxycycline", "Doxycycline",
         "CC1C2C(O)C3C(N(C)C)C(=O)C(C(N)=O)=C(O)C3(O)C(=O)C2=C(O)"
         "c2c(O)cccc21", "C22H24N2O8"),
        ("metronidazole", "Metronidazole", f"Cc1ncc({_NO2})n1CCO",
         "C6H9N3O3"),
        ("trimethoprim", "Trimethoprim",
         "COc1cc(Cc2cnc(N)nc2N)cc(OC)c1OC", "C14H18N4O3"),
        ("sulfamethoxazole", "Sulfamethoxazole",
         "Cc1cc(NS(=O)(=O)c2ccc(N)cc2)no1", "C10H11N3O3S"),
        ("nitrofurantoin", "Nitrofurantoin",
         f"O=C1CN(N=Cc2ccc(o2){_NO2})C(=O)N1", "C8H6N4O5"),
        ("isoniazid", "Isoniazid", "NNC(=O)c1ccncc1", "C6H7N3O"),
        ("chloramphenicol", "Chloramphenicol",
         f"OCC(NC(=O)C(Cl)Cl)C(O)c1ccc(cc1){_NO2}", "C11H12Cl2N2O5"),
        ("linezolid", "Linezolid",
         "CC(=O)NCC1CN(c2ccc(N3CCOCC3)c(F)c2)C(=O)O1", "C16H20FN3O4"),
        ("fluconazole", "Fluconazole",
         "OC(Cn1cncn1)(Cn1cncn1)c1ccc(F)cc1F", "C13H12F2N6O"),
        ("clotrimazole", "Clotrimazole",
         "Clc1ccccc1C(c1ccccc1)(c1ccccc1)n1ccnc1", "C22H17ClN2"),
        ("terbinafine", "Terbinafine",
         "CN(CC=CC#CC(C)(C)C)Cc1cccc2ccccc12", "C21H25N"),
        ("aciclovir", "Aciclovir", "Nc1nc2n(COCCO)cnc2c(=O)[nH]1",
         "C8H11N5O3"),
        ("oseltamivir", "Oseltamivir",
         "CCOC(=O)C1=CC(OC(CC)CC)C(NC(C)=O)C(N)C1", "C16H28N2O4"),
        ("zidovudine", "Zidovudine (AZT)",
         "Cc1cn(C2CC(N=[N+]=[N-])C(CO)O2)c(=O)[nH]c1=O", "C10H13N5O4"),
        ("chloroquine", "Chloroquine",
         "CCN(CC)CCCC(C)Nc1ccnc2cc(Cl)ccc12", "C18H26ClN3"),
        ("hydroxychloroquine", "Hydroxychloroquine",
         "CCN(CCO)CCCC(C)Nc1ccnc2cc(Cl)ccc12", "C18H26ClN3O"),
        ("mebendazole", "Mebendazole",
         "COC(=O)Nc1nc2ccc(cc2[nH]1)C(=O)c1ccccc1", "C16H13N3O3"),
    ],
    HEART: [
        ("atorvastatin", "Atorvastatin",
         "CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)"
         "n1CCC(O)CC(O)CC(=O)O", "C33H35FN2O5"),
        ("simvastatin", "Simvastatin",
         "CCC(C)(C)C(=O)OC1CC(C)C=C2C=CC(C)C(CCC3CC(O)CC(=O)O3)C12",
         "C25H38O5"),
        ("rosuvastatin", "Rosuvastatin",
         "CC(C)c1nc(N(C)S(C)(=O)=O)nc(-c2ccc(F)cc2)c1C=CC(O)CC(O)CC(=O)O",
         "C22H28FN3O6S"),
        ("amlodipine", "Amlodipine",
         "CCOC(=O)C1=C(COCCN)NC(C)=C(C(=O)OC)C1c1ccccc1Cl",
         "C20H25ClN2O5"),
        ("nifedipine", "Nifedipine",
         f"COC(=O)C1=C(C)NC(C)=C(C(=O)OC)C1c1ccccc1{_NO2}", "C17H18N2O6"),
        ("lisinopril", "Lisinopril",
         "NCCCCC(NC(CCc1ccccc1)C(=O)O)C(=O)N1CCCC1C(=O)O", "C21H31N3O5"),
        ("enalapril", "Enalapril",
         "CCOC(=O)C(CCc1ccccc1)NC(C)C(=O)N1CCCC1C(=O)O", "C20H28N2O5"),
        ("ramipril", "Ramipril",
         "CCOC(=O)C(CCc1ccccc1)NC(C)C(=O)N1C2CCCC2CC1C(=O)O",
         "C23H32N2O5"),
        ("captopril", "Captopril", "CC(CS)C(=O)N1CCCC1C(=O)O",
         "C9H15NO3S"),
        ("losartan", "Losartan",
         "CCCCc1nc(Cl)c(CO)n1Cc1ccc(cc1)-c1ccccc1-c1nn[nH]n1",
         "C22H23ClN6O"),
        ("valsartan", "Valsartan",
         "CCCCC(=O)N(Cc1ccc(cc1)-c1ccccc1-c1nn[nH]n1)C(C(C)C)C(=O)O",
         "C24H29N5O3"),
        ("metoprolol", "Metoprolol", "COCCc1ccc(OCC(O)CNC(C)C)cc1",
         "C15H25NO3"),
        ("atenolol", "Atenolol", "CC(C)NCC(O)COc1ccc(CC(N)=O)cc1",
         "C14H22N2O3"),
        ("propranolol", "Propranolol", "CC(C)NCC(O)COc1cccc2ccccc12",
         "C16H21NO2"),
        ("bisoprolol", "Bisoprolol",
         "CC(C)NCC(O)COc1ccc(COCCOC(C)C)cc1", "C18H31NO4"),
        ("carvedilol", "Carvedilol",
         "COc1ccccc1OCCNCC(O)COc1cccc2[nH]c3ccccc3c12", "C24H26N2O4"),
        ("furosemide", "Furosemide",
         "NS(=O)(=O)c1cc(C(=O)O)c(NCc2ccco2)cc1Cl", "C12H11ClN2O5S"),
        ("hydrochlorothiazide", "Hydrochlorothiazide",
         "NS(=O)(=O)c1cc2c(cc1Cl)NCNS2(=O)=O", "C7H8ClN3O4S2"),
        ("bendroflumethiazide", "Bendroflumethiazide",
         "NS(=O)(=O)c1cc2c(cc1C(F)(F)F)NC(Cc1ccccc1)NS2(=O)=O",
         "C15H14F3N3O4S2"),
        ("spironolactone", "Spironolactone",
         "CC(=O)SC1CC2=CC(=O)CCC2(C)C2CCC3(C)C(CCC34CCC(=O)O4)C12",
         "C24H32O4S"),
        ("warfarin", "Warfarin",
         "CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O", "C19H16O4"),
        ("clopidogrel", "Clopidogrel",
         "COC(=O)C(c1ccccc1Cl)N1CCc2sccc2C1", "C16H16ClNO2S"),
        ("apixaban", "Apixaban",
         "COc1ccc(cc1)-n1nc(C(N)=O)c2CCN(C(=O)c21)c1ccc(cc1)N1CCCCC1=O",
         "C25H25N5O4"),
        ("rivaroxaban", "Rivaroxaban",
         "Clc1ccc(s1)C(=O)NCC1CN(C(=O)O1)c1ccc(cc1)N1CCOCC1=O",
         "C19H18ClN3O5S"),
        ("nitroglycerin", "Nitroglycerin (glyceryl trinitrate)",
         f"C(C(CO{_NO2})O{_NO2})O{_NO2}", "C3H5N3O9"),
        ("isosorbide_mononitrate", "Isosorbide mononitrate",
         f"OC1COC2C(COC12)O{_NO2}", "C6H9NO6"),
        ("amiodarone", "Amiodarone",
         "CCCCc1oc2ccccc2c1C(=O)c1cc(I)c(OCCN(CC)CC)c(I)c1",
         "C25H29I2NO3"),
        ("diltiazem", "Diltiazem",
         "COc1ccc(cc1)C1Sc2ccccc2N(CCN(C)C)C(=O)C1OC(C)=O",
         "C22H26N2O4S"),
        ("verapamil", "Verapamil",
         "COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2)cc1OC",
         "C27H38N2O4"),
        ("tranexamic_acid", "Tranexamic acid", "NCC1CCC(CC1)C(=O)O",
         "C8H15NO2"),
    ],
    BRAIN: [
        ("sertraline", "Sertraline", "CNC1CCC(c2ccc(Cl)c(Cl)c2)c2ccccc12",
         "C17H17Cl2N"),
        ("fluoxetine", "Fluoxetine",
         "CNCCC(Oc1ccc(cc1)C(F)(F)F)c1ccccc1", "C17H18F3NO"),
        ("citalopram", "Citalopram",
         "CN(C)CCCC1(OCc2cc(C#N)ccc12)c1ccc(F)cc1", "C20H21FN2O"),
        ("paroxetine", "Paroxetine",
         "Fc1ccc(cc1)C1CCNCC1COc1ccc2OCOc2c1", "C19H20FNO3"),
        ("venlafaxine", "Venlafaxine",
         "COc1ccc(cc1)C(CN(C)C)C1(O)CCCCC1", "C17H27NO2"),
        ("amitriptyline", "Amitriptyline",
         "CN(C)CCC=C1c2ccccc2CCc2ccccc12", "C20H23N"),
        ("mirtazapine", "Mirtazapine", "CN1CCN2C(C1)c1ccccc1Cc1cccnc21",
         "C17H19N3"),
        ("bupropion", "Bupropion", "CC(NC(C)(C)C)C(=O)c1cccc(Cl)c1",
         "C13H18ClNO"),
        ("diazepam", "Diazepam", "CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc12",
         "C16H13ClN2O"),
        ("lorazepam", "Lorazepam",
         "OC1N=C(c2ccccc2Cl)c2cc(Cl)ccc2NC1=O", "C15H10Cl2N2O2"),
        ("alprazolam", "Alprazolam",
         "Cc1nnc2CN=C(c3ccccc3)c3cc(Cl)ccc3-n12", "C17H13ClN4"),
        ("zolpidem", "Zolpidem",
         "Cc1ccc(cc1)-c1nc2ccc(C)cn2c1CC(=O)N(C)C", "C19H21N3O"),
        ("haloperidol", "Haloperidol",
         "OC1(CCN(CCCC(=O)c2ccc(F)cc2)CC1)c1ccc(Cl)cc1", "C21H23ClFNO2"),
        ("risperidone", "Risperidone",
         "Cc1nc2CCCCn2c(=O)c1CCN1CCC(CC1)c1noc2cc(F)ccc12",
         "C23H27FN4O2"),
        ("quetiapine", "Quetiapine",
         "OCCOCCN1CCN(CC1)C1=Nc2ccccc2Sc2ccccc12", "C21H25N3O2S"),
        ("olanzapine", "Olanzapine",
         "CN1CCN(CC1)C1=Nc2ccccc2Nc2sc(C)cc12", "C17H20N4S"),
        ("aripiprazole", "Aripiprazole",
         "Clc1cccc(N2CCN(CCCCOc3ccc4CCC(=O)Nc4c3)CC2)c1Cl",
         "C23H27Cl2N3O2"),
        ("levodopa", "Levodopa", "NC(Cc1ccc(O)c(O)c1)C(=O)O", "C9H11NO4"),
        ("carbamazepine", "Carbamazepine",
         "NC(=O)N1c2ccccc2C=Cc2ccccc12", "C15H12N2O"),
        ("valproic_acid", "Valproic acid", "CCCC(CCC)C(=O)O", "C8H16O2"),
        ("lamotrigine", "Lamotrigine",
         "Nc1nnc(c(N)n1)-c1cccc(Cl)c1Cl", "C9H7Cl2N5"),
        ("levetiracetam", "Levetiracetam", "CCC(N1CCCC1=O)C(N)=O",
         "C8H14N2O2"),
        ("gabapentin", "Gabapentin", "NCC1(CC(=O)O)CCCCC1", "C9H17NO2"),
        ("pregabalin", "Pregabalin", "CC(C)CC(CN)CC(=O)O", "C8H17NO2"),
        ("phenytoin", "Phenytoin", "O=C1NC(=O)C(N1)(c1ccccc1)c1ccccc1",
         "C15H12N2O2"),
        ("donepezil", "Donepezil",
         "COc1cc2CC(CC3CCN(Cc4ccccc4)CC3)C(=O)c2cc1OC", "C24H29NO3"),
        ("methylphenidate", "Methylphenidate",
         "COC(=O)C(c1ccccc1)C1CCCCN1", "C14H19NO2"),
        ("sumatriptan", "Sumatriptan",
         "CNS(=O)(=O)Cc1ccc2[nH]cc(CCN(C)C)c2c1", "C14H21N3O2S"),
        ("melatonin", "Melatonin", "COc1ccc2[nH]cc(CCNC(C)=O)c2c1",
         "C13H16N2O2"),
        ("naloxone", "Naloxone",
         "Oc1ccc2CC3N(CC=C)CCC45C(Oc1c24)C(=O)CCC35O", "C19H21NO4"),
    ],
    GUT: [
        ("omeprazole", "Omeprazole",
         "COc1ccc2[nH]c(nc2c1)S(=O)Cc1ncc(C)c(OC)c1C", "C17H19N3O3S"),
        ("lansoprazole", "Lansoprazole",
         "Cc1c(OCC(F)(F)F)ccnc1CS(=O)c1nc2ccccc2[nH]1", "C16H14F3N3O2S"),
        ("pantoprazole", "Pantoprazole",
         "COc1ccnc(CS(=O)c2nc3cc(OC(F)F)ccc3[nH]2)c1OC",
         "C16H15F2N3O4S"),
        ("ranitidine", "Ranitidine",
         f"CNC(=C{_NO2})NCCSCc1ccc(CN(C)C)o1", "C13H22N4O3S"),
        ("famotidine", "Famotidine",
         "NC(N)=Nc1nc(CSCCC(N)=NS(N)(=O)=O)cs1", "C8H15N7O2S3"),
        ("metoclopramide", "Metoclopramide",
         "CCN(CC)CCNC(=O)c1cc(Cl)c(N)cc1OC", "C14H22ClN3O2"),
        ("ondansetron", "Ondansetron",
         "Cc1nccn1CC1CCc2n(C)c3ccccc3c2C1=O", "C18H19N3O"),
        ("loperamide", "Loperamide",
         "CN(C)C(=O)C(CCN1CCC(O)(CC1)c1ccc(Cl)cc1)(c1ccccc1)c1ccccc1",
         "C29H33ClN2O2"),
        ("mesalazine", "Mesalazine", "Nc1ccc(O)c(c1)C(=O)O", "C7H7NO3"),
        ("cetirizine", "Cetirizine",
         "OC(=O)COCCN1CCN(CC1)C(c1ccccc1)c1ccc(Cl)cc1", "C21H25ClN2O3"),
        ("loratadine", "Loratadine",
         "CCOC(=O)N1CCC(=C2c3ccc(Cl)cc3CCc3cccnc23)CC1", "C22H23ClN2O2"),
        ("fexofenadine", "Fexofenadine",
         "CC(C)(C(=O)O)c1ccc(cc1)C(O)CCCN1CCC(CC1)C(O)(c1ccccc1)"
         "c1ccccc1", "C32H39NO4"),
        ("diphenhydramine", "Diphenhydramine",
         "CN(C)CCOC(c1ccccc1)c1ccccc1", "C17H21NO"),
        ("chlorphenamine", "Chlorphenamine",
         "CN(C)CCC(c1ccc(Cl)cc1)c1ccccn1", "C16H19ClN2"),
        ("promethazine", "Promethazine",
         "CC(CN1c2ccccc2Sc2ccccc12)N(C)C", "C17H20N2S"),
        ("salbutamol", "Salbutamol",
         "CC(C)(C)NCC(O)c1ccc(O)c(CO)c1", "C13H21NO3"),
        ("montelukast", "Montelukast",
         "CC(C)(O)c1ccccc1CCC(SCC1(CC(=O)O)CC1)c1cccc(C=Cc2ccc3ccc(Cl)"
         "cc3n2)c1", "C35H36ClNO3S"),
        ("theophylline", "Theophylline", "Cn1c2nc[nH]c2c(=O)n(C)c1=O",
         "C7H8N4O2"),
        ("pseudoephedrine", "Pseudoephedrine", "CNC(C)C(O)c1ccccc1",
         "C10H15NO"),
        ("dextromethorphan", "Dextromethorphan",
         "COc1ccc2CC3N(C)CCC4(CCCCC34)c2c1", "C18H25NO"),
        ("guaifenesin", "Guaifenesin", "COc1ccccc1OCC(O)CO", "C10H14O4"),
    ],
    HORMONES: [
        ("metformin", "Metformin", "CN(C)C(=N)NC(N)=N", "C4H11N5"),
        ("glibenclamide", "Glibenclamide",
         "COc1ccc(Cl)cc1C(=O)NCCc1ccc(cc1)S(=O)(=O)NC(=O)NC1CCCCC1",
         "C23H28ClN3O5S"),
        ("gliclazide", "Gliclazide",
         "Cc1ccc(cc1)S(=O)(=O)NC(=O)NN1CC2CCCC2C1", "C15H21N3O3S"),
        ("sitagliptin", "Sitagliptin",
         "NC(CC(=O)N1CCn2c(C1)nnc2C(F)(F)F)Cc1cc(F)c(F)cc1F",
         "C16H15F6N5O"),
        ("pioglitazone", "Pioglitazone",
         "CCc1ccc(CCOc2ccc(CC3SC(=O)NC3=O)cc2)nc1", "C19H20N2O3S"),
        ("empagliflozin", "Empagliflozin",
         "OCC1OC(c2ccc(Cl)c(Cc3ccc(OC4CCOC4)cc3)c2)C(O)C(O)C1O",
         "C23H27ClO7"),
        ("dapagliflozin", "Dapagliflozin",
         "CCOc1ccc(Cc2cc(ccc2Cl)C2OC(CO)C(O)C(O)C2O)cc1", "C21H25ClO6"),
        ("levothyroxine", "Levothyroxine",
         "NC(Cc1cc(I)c(Oc2cc(I)c(O)c(I)c2)c(I)c1)C(=O)O", "C15H11I4NO4"),
        ("estradiol", "Estradiol", "CC12CCC3c4ccc(O)cc4CCC3C1CCC2O",
         "C18H24O2"),
        ("ethinylestradiol", "Ethinylestradiol",
         "CC12CCC3c4ccc(O)cc4CCC3C1CCC2(O)C#C", "C20H24O2"),
        ("levonorgestrel", "Levonorgestrel",
         "CCC12CCC3C(CCC4=CC(=O)CCC34)C1CCC2(O)C#C", "C21H28O2"),
        ("progesterone", "Progesterone",
         "CC(=O)C1CCC2C3CCC4=CC(=O)CCC4(C)C3CCC12C", "C21H30O2"),
        ("testosterone", "Testosterone",
         "CC12CCC3C(CCC4=CC(=O)CCC34C)C1CCC2O", "C19H28O2"),
        ("cholesterol", "Cholesterol",
         "CC(C)CCCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C", "C27H46O"),
        ("finasteride", "Finasteride",
         "CC(C)(C)NC(=O)C1CCC2C3CCC4NC(=O)C=CC4(C)C3CCC12C",
         "C23H36N2O2"),
        ("tamoxifen", "Tamoxifen",
         "CCC(=C(c1ccccc1)c1ccc(OCCN(C)C)cc1)c1ccccc1", "C26H29NO"),
        ("methotrexate", "Methotrexate",
         "CN(Cc1cnc2nc(N)nc(N)c2n1)c1ccc(cc1)C(=O)NC(CCC(=O)O)C(=O)O",
         "C20H22N8O5"),
        ("alendronic_acid", "Alendronic acid",
         "NCCCC(O)(P(=O)(O)O)P(=O)(O)O", "C4H13NO7P2"),
        ("sildenafil", "Sildenafil",
         "CCCc1nn(C)c2c1nc([nH]c2=O)-c1cc(ccc1OCC)S(=O)(=O)"
         "N1CCN(C)CC1", "C22H30N6O4S"),
        ("tadalafil", "Tadalafil",
         "CN1CC(=O)N2C(Cc3c([nH]c4ccccc34)C2c2ccc3OCOc3c2)C1=O",
         "C22H19N3O4"),
        ("tamsulosin", "Tamsulosin",
         "CCOc1ccccc1OCCNC(C)Cc1ccc(OC)c(c1)S(N)(=O)=O", "C20H28N2O5S"),
        ("folic_acid", "Folic acid",
         "Nc1nc2ncc(CNc3ccc(cc3)C(=O)NC(CCC(=O)O)C(=O)O)nc2c(=O)[nH]1",
         "C19H19N7O6"),
        ("niacin", "Niacin (vitamin B3)", "OC(=O)c1cccnc1", "C6H5NO2"),
        ("nicotinamide", "Nicotinamide", "NC(=O)c1cccnc1", "C6H6N2O"),
        ("pyridoxine", "Pyridoxine (vitamin B6)", "Cc1ncc(CO)c(CO)c1O",
         "C8H11NO3"),
        ("riboflavin", "Riboflavin (vitamin B2)",
         "Cc1cc2nc3c(=O)[nH]c(=O)nc-3n(CC(O)C(O)C(O)CO)c2cc1C",
         "C17H20N4O6"),
    ],
}

#: key -> (name, SMILES, category, formula)
MORE = {key: (name, smiles, category, formula)
        for category, rows in _ROWS.items()
        for key, name, smiles, formula in rows}
