// GENERATED from dev-AI Fitting_Screen.get_background_description / get_fitting_description (the '?' buttons).

export const BACKGROUND_HELP: Record<string, string> = {
 "Multi-Regions Smart": "Same as the Smart background but not restricted to a single region",
 "Smart": "Single region Smart background estimation. It applies a Shirley background when the intensity is going up and a linear background when the intensity is going down. If the calculated background is above the data then the background is set equal to the data.",
 "Shirley": "Iterated Shirley background (the CasaXPS 'Iterated Shirley'): the Shirley integral is recomputed until convergence (up to 100 iterations). Reliable for increasing background when the data contains symmetrical peaks.",
 "Iterated Shirley": "Shirley background with a finite, user-defined number of iterations (the CasaXPS Iterated Shirley behaviour). The iteration count is taken from the Averaging Points control (default 5). Fewer iterations give a softer step; the standard Shirley instead iterates to convergence. During a fit the integral is driven by the fitted peak envelope rather than the raw data, so the background follows the peaks and converges with them - use 'Fit N# Times'. The endpoints never move.",
 "Spline Shirley": "CasaXPS-style cubic spline background with five polynomial sections, fitted by least squares to the iterated Shirley curve: a smoothed, low-curvature version of the Shirley background. Endpoints are pinned to the averaged data endpoints plus the offsets. No physical meaning - use it when the raw Shirley shows structure/noise you want relaxed.",
 "Spline Tougaard": "CasaXPS-style cubic spline background with five polynomial sections, fitted by least squares to a U4-Tougaard curve (using the current cross-section parameters): a smoothed, low-curvature version of the Tougaard background with endpoints pinned to the averaged data endpoints plus the offsets. No physical meaning.",
 "Active Shirley": "Dynamic/Active Shirley background (Herrera-Gomez method). The background is recalculated from the fitted peaks after each iteration. Initial background is a flat offset at the low BE endpoint. Use 'Fit N# Times' to iterate - background converges with peaks for better accuracy.",
 "Active Tougaard": "Dynamic/Active Tougaard background. The background is recalculated from the fitted peaks after each iteration using the 4-PIESCS loss function. Initial background is a flat offset. Use 'Fit N# Times' to iterate - background converges with peaks. Uses C=1643, D=1.",
 "Power-EELS": "Power law A*E^-r for EELS core-loss edges, the background DigitalMicrograph uses. It is fitted to a window in front of the edge and extrapolated underneath it, so the edge itself never pulls the background up. Set the width of that window in eV in the parameter box (0 = automatic, 30% of the selected range). The Left/Right offsets do not apply: the curve is fitted to the pre-edge window, not pinned to the endpoints of the range.",
 "Linear": "Simple linear background. Usually used on negative background",
 "U4-Tougaard": "U4 Tougaard background for Advanced users. B, C, D and T0 can be varied.",
 "U2-Tougaard": "2-parameter Tougaard background (auto B, user C, D=0, T0=0)",
 "ALS-Raman": "Asymmetric Least Squares background estimation. Good for uneven backgrounds with broad features. Lambda controls smoothness and p controls asymmetry.",
 "Poly-2": "Second-order polynomial background. A quadratic fitted to the flat background at the two ends of the region and arced smoothly underneath the peaks. Fitting only the endpoints keeps it from humping up into the valley between peaks. The offsets nudge the two ends.",
 "Poly-3": "Third-order polynomial background. A cubic fitted to the flat background at the two ends of the region and arced smoothly underneath the peaks. Fitting only the endpoints keeps it from humping up into the valley between peaks. The offsets nudge the two ends.",
 "ALS": "Asymmetric Least Squares baseline (peak-aware). Follows the smooth lower envelope of the data and never climbs into the peaks. Good for curved or uneven backgrounds; the offsets nudge the two ends."
}

export const MODEL_HELP: Record<string, string> = {
 "A*GL (Area, a, b)": "CasaXPS-style asymmetric Gaussian-Lorentzian product A(a,b,0)GL(p) due to Ulrik Gelius. The L/G column is p, the σ column holds a and the γ column holds b (e.g. A(0.2,0.4,0)GL(30) -> L/G=30, σ=0.2, γ=0.4). Area-based: the fitted Area is the numeric integral over ±10×FWHM and the Height is derived. The Position is the peak maximum and the tail extends to higher BE.",
 "A*SGL (Area, a, b)": "CasaXPS-style asymmetric Gaussian-Lorentzian sum A(a,b,0)SGL(p) due to Ulrik Gelius. Same as A*GL but with the SGL sum form as the symmetric base. L/G column is p, σ column holds a, γ column holds b.",
 "LF (Area, σ, γ, w)": "Finite Lorentzian LF(α,β,w,m): identical to LA except the exponents α (σ column) and β (γ column) ramp to the constant 3 via 3-(3-α)/(1+4(t/w)²), with w (eV) in the Skew column, which restricts the extent of the tails and makes the area finite. Exact form from Major et al., Vacuum Technology & Coating, April 2020 (with N. Fairley, CasaXPS). w ~ 1 (strong damping) to 1000 (recovers LA).",
 "TLA (A, μ, α, Wg)": "CasaXPS TLA asymmetric line shape: a Lorentzian raised to the power α (γ column, usually fixed at 1) and modulated by the arctangent tail factor π/2+atan(2t/F)+π/μ, then convolved with a Gaussian of FWHM Wg (W_g/Skew column, eV). μ (σ column) sets the asymmetry: larger μ = stronger high-BE tail. The FWHM column is the width of the TLA shape BEFORE the Gaussian convolution (like LA*G); press TAB on the peak for the measured width. e.g. CasaXPS TLA(20,80) -> σ=20. Area-based; Position = true maximum.",
 "SB (Height)": "Shirley-background component SB(0)V: the sigmoid response of a true Voigt bell (FWHM and L/G columns), i.e. a step of the given Height rising toward higher BE, as in CasaXPS SB(0)LA(...). Use it as an optimisable background component under a photoelectron peak, e.g. to model an energy-offset Shirley step.",
 "DL (A, σ, γ, aDL)": "Double Lorentzian (Herrera-Gomez et al., JVST A 41, 043208 (2023); AAnalyzer): a split Lorentzian, narrow width σ to low BE and wide width aDL×σ to high BE, convolved with a Gaussian of FWHM γ. The Area is the exact analytic area of the full profile. aDL (Skew column, ≥1) controls the asymmetry; at aDL = 1 the DL is exactly a Voigt. Position is anchored to the true peak maximum.",
 "GL (Height)": "Gaussian-Lorentzian product function (height-based).  Constrained by Peak position, Height, FWHM and L/G. Based on GL from Thermo Avantage",
 "SGL (Height)": "Sum of Gaussian and Lorentzian functions (height-based).  Constrained by Peak position, Height, FWHM and L/G.   Based on GL from Thermo Avantage",
 "GL (Area)": "Product of Gaussian and Lorentzian model (area-based).  Constrained by Peak position, Area, FWHM and L/G.   Based on GL from CasaXPS",
 "SGL (Area)": "Sum of Gaussian and Lorentzian functions (area-based). Constrained by Peak position, Area, FWHM and L/G.   Based on SGL from CasaXPS",
 "Pseudo-Voigt (Area)": "Linear combination of Gaussian and Lorentzian provided by LMFIT.  Constrained by Peak position, Area, FWHM and L/G",
 "Voigt (Area, L/G, σ, S)": "Asymmetric Voigt Function controlled by A, L/G, Wg and S.  Wl is calculated from Wg and L/G. In this case S controls the Asymmetry. Based on the LMFIT skewed Voigt, re-anchored so that the Position is the true peak maximum (apex) whatever the value of S.",
 "Voigt (Area)": "Simple true Voigt: the FWHM column is the actual total FWHM of the peak (Olivero-Longbothum, accurate to ~0.02%) and the L/G column sets the Lorentzian share of that width. W_g and W_l are derived automatically and shown for information. Controlled by Position, Area, FWHM and L/G only.",
 "Voigt (Area, L/G, S)": "Hybrid Voigt: single total FWHM + L/G ratio like Voigt (Area), plus a tail/asymmetry parameter S. Designed for XRD whole-pattern fitting.",
 "Voigt (Area,σ, γ)": "Voigt function with separate Gaussian and Lorentzian widths.  It is controlled by A, Wg and Wl. Wl is independent of Wg and L/G  is calculated from Wl and Wg.  The model is provided by LMFIT",
 "Voigt (Area, L/G, σ)": "Voigt Function controlled by A, L/G, Wg.   Wl is calculated from Wg and L/G. The Model is provided by LMFIT",
 "ExpGauss.(Area, σ, γ)": "Gaussian shape model with asymmetric side. The asymmetry is modelled using an exponential decay. Model provided by LMFIT",
 "LA (Area, σ, γ)": "Asymmetrical lorentzian similar to the model used in casa XPS.  σ and γ can be varied independently.Constrained by Peak position, Area, FWHM, L/G, σ and γ.  σ controlled the high BE side of the peak while γ controlled the low BE side of the peak.",
 "LA (Area, σ/γ, γ)": "Asymmetrical lorentzian with asymmetry controlled by the ratio between σ and γ. The model is similar to the one used in casa XPS. σ controlled the high BE side of the peak while γ controlled the low BE side of the peak.",
 "LA*G (Area, σ/γ, γ)": "Asymmetrical lorentzian convoluted with a gaussian peak of a width Wg (see skew colum). The model is similar to the one used in casa XPS. σ controlled the high BE side of the peak while γ controlled the low BE side of the peak."
}
