"""Export the desktop KherveTeX examples (khervedoc/examples.py) as document.json files.

    python3 src/apps/khervetex/examples/export_examples.py <KherveTeX dev checkout>

Reads the dev branch's khervedoc package (no Qt needed) and writes one
<slug>.json per example here, plus index.ts (label, file, group) for the
Examples menu. The JSON is model.to_json, so it is exactly what a .ktex holds.
"""
import json
import re
import sys
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(sys.argv[1]).resolve()))
from khervedoc import examples, model  # noqa: E402


def slug(label: str) -> str:
    s = unicodedata.normalize("NFKD", label.replace("&", "").lower()).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


index = []
for group, entries in (("main", examples.EXAMPLES), ("journal", examples.JOURNAL_EXAMPLES)):
    for label, factory in entries:
        name = slug(label) + ".json"
        (HERE / name).write_text(model.to_json(factory()) + "\n", encoding="utf-8")
        index.append({"label": label.replace("&", ""), "file": name, "group": group})
lines = [
    "// Generated by export_examples.py from the desktop KherveTeX's examples — do not edit.",
    "",
    "export interface ExampleEntry {",
    "  label: string",
    "  file: string",
    "  group: 'main' | 'journal'",
    "}",
    "",
    "export const EXAMPLES: ExampleEntry[] = [",
    *[f"  {{ label: {json.dumps(e['label'], ensure_ascii=False)}, file: {json.dumps(e['file'])}, group: '{e['group']}' }}," for e in index],
    "]",
    "",
    "const files = import.meta.glob('./*.json', { query: '?raw', import: 'default' })",
    "",
    "/** The document.json text of an example. */",
    "export async function loadExample(file: string): Promise<string> {",
    "  const load = files[`./${file}`]",
    "  if (!load) throw new Error(`No example ${file}`)",
    "  return (await load()) as string",
    "}",
]
(HERE / "index.ts").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"{len(index)} examples written to {HERE}")
