// Generated by export_examples.py from the desktop KherveTeX's examples — do not edit.

export interface ExampleEntry {
  label: string
  file: string
  group: 'main' | 'journal'
}

export const EXAMPLES: ExampleEntry[] = [
  { label: "Welcome tour", file: "welcome-tour.json", group: 'main' },
  { label: "Blank document", file: "blank-document.json", group: 'main' },
  { label: "Single-column article", file: "single-column-article.json", group: 'main' },
  { label: "Two-column article", file: "two-column-article.json", group: 'main' },
  { label: "Three-column document", file: "three-column-document.json", group: 'main' },
  { label: "Math-heavy document", file: "math-heavy-document.json", group: 'main' },
  { label: "Letter", file: "letter.json", group: 'main' },
  { label: "CV / résumé", file: "cv-resume.json", group: 'main' },
  { label: "Lab report", file: "lab-report.json", group: 'main' },
  { label: "Homework / problem set", file: "homework-problem-set.json", group: 'main' },
  { label: "Technical memo", file: "technical-memo.json", group: 'main' },
  { label: "Literature review", file: "literature-review.json", group: 'main' },
  { label: "Research proposal", file: "research-proposal.json", group: 'main' },
  { label: "Book chapter", file: "book-chapter.json", group: 'main' },
  { label: "Meeting minutes", file: "meeting-minutes.json", group: 'main' },
  { label: "Lecture notes", file: "lecture-notes.json", group: 'main' },
  { label: "Poster / two-column", file: "poster-two-column.json", group: 'main' },
  { label: "White paper", file: "white-paper.json", group: 'main' },
  { label: "How-to guide", file: "how-to-guide.json", group: 'main' },
  { label: "Daily journal", file: "daily-journal.json", group: 'main' },
  { label: "Weekly journal", file: "weekly-journal.json", group: 'main' },
  { label: "Monthly journal", file: "monthly-journal.json", group: 'main' },
  { label: "Calendar", file: "calendar.json", group: 'main' },
  { label: "XPS surface-science paper", file: "xps-surface-science-paper.json", group: 'main' },
  { label: "XRD / nanomaterials paper", file: "xrd-nanomaterials-paper.json", group: 'main' },
  { label: "DFT computational study", file: "dft-computational-study.json", group: 'main' },
  { label: "Battery / electrochemistry paper", file: "battery-electrochemistry-paper.json", group: 'main' },
  { label: "Clinical trial (CONSORT)", file: "clinical-trial-consort.json", group: 'main' },
  { label: "Ecology field study", file: "ecology-field-study.json", group: 'main' },
  { label: "Quantum mechanics lecture", file: "quantum-mechanics-lecture.json", group: 'main' },
  { label: "Grant proposal (work packages)", file: "grant-proposal-work-packages.json", group: 'main' },
  { label: "Response to reviewers", file: "response-to-reviewers.json", group: 'main' },
  { label: "Lab SOP / risk assessment", file: "lab-sop-risk-assessment.json", group: 'main' },
  { label: "Elsevier preprint (elsarticle)", file: "elsevier-preprint-elsarticle.json", group: 'journal' },
  { label: "Elsevier two-column (5p)", file: "elsevier-two-column-5p.json", group: 'journal' },
  { label: "IEEE conference (IEEEtran)", file: "ieee-conference-ieeetran.json", group: 'journal' },
  { label: "APS / Physical Review (revtex4-2)", file: "aps-physical-review-revtex4-2.json", group: 'journal' },
  { label: "ACS journal (achemso)", file: "acs-journal-achemso.json", group: 'journal' },
  { label: "Thesis / report", file: "thesis-report.json", group: 'journal' },
  { label: "Beamer slides", file: "beamer-slides.json", group: 'journal' },
]

const files = import.meta.glob('./*.json', { query: '?raw', import: 'default' })

/** The document.json text of an example. */
export async function loadExample(file: string): Promise<string> {
  const load = files[`./${file}`]
  if (!load) throw new Error(`No example ${file}`)
  return (await load()) as string
}
