// The Gerber package: all layer files and drill files in one zip (pure, uses fflate).

import { strToU8, zipSync } from 'fflate'
import type { Design, Fills } from '../types.ts'
import { exportGerbers } from './gerber.ts'
import { summaryText, boardSummary } from './summary.ts'

export function gerberZip(d: Design, fills?: Fills): Uint8Array {
  const files: Record<string, Uint8Array> = {}
  for (const f of exportGerbers(d, fills)) files[f.name] = strToU8(f.text)
  files[`${d.name}-README.txt`] = strToU8(`${summaryText(boardSummary(d, fills))}\n\nGenerated by kPCB (KherveOS). Gerber RS-274X, Excellon drills, millimetres.\n`)
  return zipSync(files, { level: 6 })
}
