// Per-element data and helpers — the desktop's elements.py (its data is in
// elementsData.ts, generated by tools/export_khervemol.py).

import * as D from './elementsData.ts'

const INDEX = new Map<string, number>(D.SYMBOLS.map((s, i) => [s, i]))
const BOND = new Map<string, number>(D.BOND_LENGTHS.map(([a, b, o, v]) => [`${a}|${b}|${o}`, v]))

export const PALETTE: readonly string[] = D.PALETTE
export const SYMBOLS: readonly string[] = D.SYMBOLS
/** (symbol, row, col) of the wide periodic table (f-block in rows 9 and 10). */
export const TABLE: readonly (readonly [string, number, number])[] = D.TABLE as unknown as readonly (readonly [string, number, number])[]

const at = (el: string) => INDEX.get(el)

export function color(el: string): string {
  const i = at(el)
  return i === undefined ? '#ff1493' : D.COLORS[i]
}
export function radius(el: string): number {
  const i = at(el)
  return i === undefined ? D.DEFAULT_RADIUS : D.RADII[i]
}
export function valence(el: string): number {
  const i = at(el)
  return i === undefined ? 4 : D.VALENCE[i]
}
/** The valence elements.VALENCE knows (molrepr counts implicit H only for these). */
export function knownValence(el: string): number | undefined {
  return (D.KNOWN_VALENCE as Record<string, number>)[el]
}
export function name(el: string): string {
  const i = at(el)
  return i === undefined ? el : D.NAMES[i]
}
export function number(el: string): number | null {
  const i = at(el)
  return i === undefined ? null : i + 1
}
export function weight(el: string): number {
  const i = at(el)
  return i === undefined ? 0 : D.WEIGHTS[i]
}
export function textColor(el: string): string {
  const i = at(el)
  return i === undefined ? '#fff' : D.TEXT_COLOR[i]
}
export function covalentRadius(el: string): number {
  const i = at(el)
  return i === undefined ? D.DEFAULT_COVALENT : D.COVALENT[i]
}
export function isElement(el: string): boolean {
  return INDEX.has(el)
}
export function vdw(el: string): number | undefined {
  return (D.VDW as Record<string, number>)[el]
}
export function valenceElectrons(el: string): number | undefined {
  return (D.VALENCE_E as Record<string, number>)[el]
}

/** Equilibrium A–B length (Å) of a bond of *order*: the experimental table, else the radius sum shrunk by order. */
export function bondLength(a: string, b: string, order = 1): number {
  const o = Math.max(1, Math.min(3, Math.trunc(order)))
  const [x, y] = a <= b ? [a, b] : [b, a]
  const exact = BOND.get(`${x}|${y}|${o}`)
  if (exact !== undefined) return exact
  return (covalentRadius(a) + covalentRadius(b)) * D.ORDER_SHRINK[o - 1]
}
