// The desktop KherveBook's icons: Material Design Icons by their qtawesome names
// ("mdi.play"), from MDI 5.9.55, the release qtawesome's "mdi" prefix draws.

import { memo } from 'react'
import {
  mdiArrowDown, mdiArrowUp, mdiBookPlusOutline, mdiBugOutline, mdiChartBellCurve, mdiChevronDown, mdiChevronRight, mdiCloudDownloadOutline,
  mdiCloudUploadOutline, mdiCodeBraces, mdiCodeJson, mdiCodeTags, mdiCog, mdiCommentTextOutline, mdiContentCopy, mdiContentCut,
  mdiContentPaste, mdiContentSave, mdiContentSaveOutline, mdiCubeOutline, mdiCursorDefaultOutline, mdiDatabaseOutline, mdiDeleteOutline,
  mdiDeleteSweep, mdiDraw, mdiEllipseOutline, mdiEraser, mdiEyeOutline, mdiFastForward, mdiFileDelimitedOutline, mdiFileDocumentOutline,
  mdiFileExcelOutline, mdiFileImageOutline, mdiFileOutline, mdiFilePdfBox, mdiFilePlusOutline, mdiFileTableOutline, mdiFileTree,
  mdiFolderOpenOutline, mdiFolderOutline, mdiFolderZipOutline, mdiFormatAlignCenter, mdiFormatAlignLeft, mdiFormatAlignRight, mdiFormatBold,
  mdiFormatColorFill, mdiFormatColorHighlight, mdiFormatColorText, mdiFormatHeaderPound, mdiFormatIndentDecrease, mdiFormatIndentIncrease,
  mdiFormatItalic, mdiFormatListBulleted, mdiFormatListNumbered, mdiFormatQuoteClose, mdiFormatStrikethroughVariant, mdiFormatText,
  mdiFormatUnderline, mdiGithub, mdiGoogleSpreadsheet, mdiGrid, mdiHelpCircleOutline, mdiHistory, mdiLanguageJavascript, mdiLanguageMarkdown,
  mdiLanguagePython, mdiLinkVariant, mdiMagnet, mdiMagnify, mdiMolecule, mdiOpenInNew, mdiPalette, mdiPaperclip, mdiPlay, mdiPlayCircleOutline,
  mdiPlus, mdiRectangleOutline, mdiRedo, mdiRefresh, mdiRepeat, mdiRestart, mdiRobotOutline, mdiRotate3dVariant, mdiSend, mdiShapeOutline,
  mdiShapePlus, mdiSourceBranch, mdiStop, mdiStopCircleOutline, mdiTable, mdiTableColumnPlusAfter, mdiTableColumnRemove, mdiTablePlus,
  mdiTableRowPlusAfter, mdiTableRowRemove, mdiUndo, mdiVectorLine, mdiVectorPolyline, mdiViewDay, mdiImageOutline, mdiArrowUpBold,
} from '@mdi/js-5'

export const MDI: Record<string, string> = {
  'arrow-down': mdiArrowDown,
  'arrow-up': mdiArrowUp,
  'book-plus-outline': mdiBookPlusOutline,
  'bug-outline': mdiBugOutline,
  'chart-bell-curve': mdiChartBellCurve,
  'chevron-down': mdiChevronDown,
  'chevron-right': mdiChevronRight,
  'cloud-download-outline': mdiCloudDownloadOutline,
  'cloud-upload-outline': mdiCloudUploadOutline,
  'code-braces': mdiCodeBraces,
  'code-json': mdiCodeJson,
  'code-tags': mdiCodeTags,
  'cog': mdiCog,
  'comment-text-outline': mdiCommentTextOutline,
  'content-copy': mdiContentCopy,
  'content-cut': mdiContentCut,
  'content-paste': mdiContentPaste,
  'content-save': mdiContentSave,
  'content-save-outline': mdiContentSaveOutline,
  'cube-outline': mdiCubeOutline,
  'cursor-default-outline': mdiCursorDefaultOutline,
  'database-outline': mdiDatabaseOutline,
  'delete-outline': mdiDeleteOutline,
  'delete-sweep': mdiDeleteSweep,
  'draw': mdiDraw,
  'ellipse-outline': mdiEllipseOutline,
  'eraser': mdiEraser,
  'eye-outline': mdiEyeOutline,
  'fast-forward': mdiFastForward,
  'file-delimited-outline': mdiFileDelimitedOutline,
  'file-document-outline': mdiFileDocumentOutline,
  'file-excel-outline': mdiFileExcelOutline,
  'file-image-outline': mdiFileImageOutline,
  'file-outline': mdiFileOutline,
  'file-pdf-box': mdiFilePdfBox,
  'file-plus-outline': mdiFilePlusOutline,
  'file-table-outline': mdiFileTableOutline,
  'file-tree': mdiFileTree,
  'folder-open-outline': mdiFolderOpenOutline,
  'folder-outline': mdiFolderOutline,
  'folder-zip-outline': mdiFolderZipOutline,
  'format-align-center': mdiFormatAlignCenter,
  'format-align-left': mdiFormatAlignLeft,
  'format-align-right': mdiFormatAlignRight,
  'format-bold': mdiFormatBold,
  'format-color-fill': mdiFormatColorFill,
  'format-color-highlight': mdiFormatColorHighlight,
  'format-color-text': mdiFormatColorText,
  'format-header-pound': mdiFormatHeaderPound,
  'format-indent-decrease': mdiFormatIndentDecrease,
  'format-indent-increase': mdiFormatIndentIncrease,
  'format-italic': mdiFormatItalic,
  'format-list-bulleted': mdiFormatListBulleted,
  'format-list-numbered': mdiFormatListNumbered,
  'format-quote-close': mdiFormatQuoteClose,
  'format-strikethrough-variant': mdiFormatStrikethroughVariant,
  'format-text': mdiFormatText,
  'format-underline': mdiFormatUnderline,
  'github': mdiGithub,
  'google-spreadsheet': mdiGoogleSpreadsheet,
  'grid': mdiGrid,
  'help-circle-outline': mdiHelpCircleOutline,
  'history': mdiHistory,
  'language-javascript': mdiLanguageJavascript,
  'language-markdown': mdiLanguageMarkdown,
  'language-python': mdiLanguagePython,
  'link-variant': mdiLinkVariant,
  'magnet': mdiMagnet,
  'magnify': mdiMagnify,
  'molecule': mdiMolecule,
  'open-in-new': mdiOpenInNew,
  'palette': mdiPalette,
  'paperclip': mdiPaperclip,
  'play': mdiPlay,
  'play-circle-outline': mdiPlayCircleOutline,
  'plus': mdiPlus,
  'rectangle-outline': mdiRectangleOutline,
  'redo': mdiRedo,
  'refresh': mdiRefresh,
  'repeat': mdiRepeat,
  'restart': mdiRestart,
  'robot-outline': mdiRobotOutline,
  'rotate-3d-variant': mdiRotate3dVariant,
  'send': mdiSend,
  'shape-outline': mdiShapeOutline,
  'shape-plus': mdiShapePlus,
  'source-branch': mdiSourceBranch,
  'stop': mdiStop,
  'stop-circle-outline': mdiStopCircleOutline,
  'table': mdiTable,
  'table-column-plus-after': mdiTableColumnPlusAfter,
  'table-column-remove': mdiTableColumnRemove,
  'table-plus': mdiTablePlus,
  'table-row-plus-after': mdiTableRowPlusAfter,
  'table-row-remove': mdiTableRowRemove,
  'undo': mdiUndo,
  'vector-line': mdiVectorLine,
  'vector-polyline': mdiVectorPolyline,
  'view-day': mdiViewDay,
  'image-outline': mdiImageOutline,
  'arrow-up-bold': mdiArrowUpBold,
}

export type MdiName = string

/** A desktop icon (qtawesome name without the "mdi." prefix, or with it). */
export const Mdi = memo(function Mdi({ name, size = 24, color, className, title }: { name: string; size?: number; color?: string; className?: string; title?: string }) {
  const d = MDI[name.replace(/^mdi\./, '')]
  if (!d) return null
  return (
    <svg className={`nb-mdi${className ? ` ${className}` : ''}`} width={size} height={size} viewBox="0 0 24 24" aria-hidden={title ? undefined : true} style={{ flex: 'none' }}>
      {title && <title>{title}</title>}
      <path d={d} fill={color ?? 'currentColor'} />
    </svg>
  )
})

export const hasMdi = (name: string) => name.replace(/^mdi\./, '') in MDI
