"""Export the desktop KherveBook's built-in examples to KherveOS.

KherveBook (dev branch) defines its Examples menu in Python: each example is
a builder returning the notebook's cells. This runs every builder and writes
the notebooks, exactly as the desktop app builds them, to
public/examples/khervebook/ with an index.json the web KherveBook reads.

    ../KherveBook/.venv/bin/python tools/export_khervebook_examples.py [path/to/KherveBook]

Run it again whenever the desktop examples change.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
SOURCE = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else HERE.parent / "KherveBook"
OUT = HERE / "public" / "examples" / "khervebook"

LIVE_RE = re.compile(r"runs continuously(?:\s*\((\d+)\s*ms\))?")


def slug(text: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", text.lower().replace("π", "pi").replace("↔", "and")).strip("-")
    return s or "example"


def kbook(cells: list) -> str:
    return json.dumps({"format": "kbook", "version": 1, "cells": cells}, indent=1, ensure_ascii=False)


def main() -> None:
    sys.path.insert(0, str(SOURCE))
    from khervebook.examples import EXAMPLES  # noqa: E402
    from khervebook.welcome import welcome_json  # noqa: E402

    try:
        commit = subprocess.run(
            ["git", "-C", str(SOURCE), "log", "-1", "--format=%h %ad %s", "--date=short"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
        branch = subprocess.run(
            ["git", "-C", str(SOURCE), "branch", "--show-current"], capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        commit, branch = "unknown", "unknown"

    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.rglob("*.kbook"):
        old.unlink()

    categories: dict[str, list] = {}
    failures = []
    for name, category, builder in EXAMPLES:
        try:
            cells = builder()
        except Exception as exc:  # keep going; report at the end
            failures.append((name, repr(exc)))
            continue
        rel = f"{slug(category)}/{slug(name)}.kbook"
        (OUT / rel).parent.mkdir(parents=True, exist_ok=True)
        (OUT / rel).write_text(kbook(cells), encoding="utf-8")
        first = next((c.get("source", "") for c in cells if c.get("type") == "code"), "")
        live = any(LIVE_RE.search((c.get("source") or "").splitlines()[0] if c.get("source") else "")
                   for c in cells if c.get("type") == "code")
        types = sorted({c.get("type", "code") for c in cells})
        categories.setdefault(category, []).append(
            {"title": name, "file": rel, "cells": len(cells), "types": types, "live": live}
        )
        del first

    (OUT / "welcome.kbook").write_text(json.dumps(json.loads(welcome_json()), indent=1, ensure_ascii=False), encoding="utf-8")

    index = {
        "source": f"KherveBook {branch} @ {commit}",
        "note": "Generated by tools/export_khervebook_examples.py from the desktop KherveBook's Examples menu.",
        "welcome": "welcome.kbook",
        "categories": [{"name": c, "notebooks": nbs} for c, nbs in categories.items()],
    }
    (OUT / "index.json").write_text(json.dumps(index, indent=1, ensure_ascii=False), encoding="utf-8")

    total = sum(len(v) for v in categories.values())
    print(f"exported {total} examples in {len(categories)} categories from {index['source']}")
    for name, err in failures:
        print(f"  FAILED {name}: {err}")


if __name__ == "__main__":
    main()
