// Reaction templates for "Predict products": reaction SMARTS applied with RDKit's reaction engine. Pure data;
// tools/tests/kreaction-rdkit.test.ts runs every example through RDKit when it can be loaded.

export interface Template {
  id: string
  name: string
  /** What kind of reactants it expects, in order (for the hint under the button). */
  needs: string[]
  /** Reaction SMARTS; several when a regiochemical rule needs more than one pattern. */
  smarts: string[]
  /** Reagents and conditions. */
  conditions: string
  /** Species left out of the product list (water, HCl, a salt…). */
  byproducts: string
  rule: string
  example: { reactants: string[]; expect: string }
}

const T = (
  id: string, name: string, needs: string[], smarts: string | string[], conditions: string, byproducts: string, rule: string,
  reactants: string[], expect: string,
): Template => ({ id, name, needs, smarts: Array.isArray(smarts) ? smarts : [smarts], conditions, byproducts, rule, example: { reactants, expect } })

/** A ketone or aldehyde carbon with the given atom map (not an ester, amide, acid chloride or enone). */
const carbonyl = (map: number) => `[CX3;!$(C(=O)[O,N,Cl,Br,F]);!$(C=C):${map}]`

export const TEMPLATES: readonly Template[] = [
  T('esterification', 'Fischer esterification', ['a carboxylic acid', 'an alcohol'],
    '[CX3:1](=[O:2])[OX2H1:3].[CX4:5][OX2H1:4]>>[C:1](=[O:2])[O:4][C:5]',
    'H2SO4 (cat.), heat', 'water', 'The OH of the acid is replaced by the OR of the alcohol.',
    ['CC(=O)O', 'CCO'], 'CCOC(C)=O'),
  T('ester-hydrolysis', 'Ester hydrolysis', ['an ester'],
    '[CX3:1](=[O:2])[OX2:3][CX4:4]>>[C:1](=[O:2])[OH].[O:3][C:4]',
    'H3O+ (reversible) or NaOH then H3O+', 'water is a reagent', 'The C–O single bond to the alkoxy group breaks: acid + alcohol.',
    ['CCOC(C)=O'], 'CC(=O)O'),
  T('acyl-chloride-amide', 'Acyl chloride + amine → amide', ['an acyl chloride', 'a primary or secondary amine'],
    '[CX3:1](=[O:2])[Cl,Br:3].[NX3;H2,H1;!$(NC=O);!$(N[a]):4]>>[C:1](=[O:2])[N:4]',
    '2 equiv. amine or Et3N, CH2Cl2', 'HCl (as the ammonium salt)', 'Chloride is replaced by the nitrogen.',
    ['CC(=O)Cl', 'CN'], 'CNC(C)=O'),
  T('acid-amide', 'Carboxylic acid + amine → amide', ['a carboxylic acid', 'a primary or secondary amine'],
    '[CX3:1](=[O:2])[OX2H1:3].[NX3;H2,H1;!$(NC=O):4]>>[C:1](=[O:2])[N:4]',
    'heat or a coupling agent (DCC, EDC)', 'water', 'Condensation: OH of the acid and H of the amine leave as water.',
    ['CC(=O)O', 'CN'], 'CNC(C)=O'),
  T('alcohol-oxidation', 'Oxidation of a primary or secondary alcohol', ['an alcohol'],
    '[CX4;H2,H1;!$(C[a]);!$(C=*):1][OX2H1:2]>>[C:1]=[O:2]',
    'PCC, CH2Cl2 (or Swern, Dess–Martin)', '—', 'Primary alcohols give aldehydes (PCC), secondary alcohols ketones; tertiary alcohols do not react.',
    ['CC(O)C'], 'CC(C)=O'),
  T('alcohol-to-acid', 'Oxidation of a primary alcohol to a carboxylic acid', ['a primary alcohol'],
    '[CX4;H2:1][OX2H1:2]>>[C:1](=[O:2])[OH]',
    'K2Cr2O7 / H2SO4, reflux (or KMnO4)', '—', 'Strong oxidants go through the aldehyde to the acid.',
    ['CCO'], 'CC(=O)O'),
  T('carbonyl-reduction', 'Reduction of an aldehyde or ketone', ['an aldehyde or ketone'],
    `${carbonyl(1)}=[O:2]>>[C:1][O:2]`,
    'NaBH4, MeOH (or LiAlH4, then H3O+)', '—', 'Hydride adds to C=O: aldehyde → primary alcohol, ketone → secondary alcohol.',
    ['CC(C)=O'], 'CC(C)O'),
  T('ester-reduction', 'Reduction of an ester with LiAlH4', ['an ester'],
    '[#6:5][CX3:1](=[O:2])[OX2:3][#6:4]>>[#6:5][CH2:1][OH:2].[O:3][#6:4]',
    'LiAlH4, THF, then H3O+', '—', 'Esters are reduced to two alcohols.',
    ['CC(=O)OCC'], 'CCO'),
  T('hydrogenation', 'Hydrogenation of an alkene', ['an alkene'],
    '[C;X3:1]=[C;X3:2]>>[C:1][C:2]',
    'H2, Pd/C', '—', 'H2 adds to both carbons of the double bond (syn).',
    ['CC=C'], 'CCC'),
  T('alkyne-semihydrogenation', 'Lindlar reduction of an alkyne', ['an alkyne'],
    '[C;X2:1]#[C;X2:2]>>[C:1]=[C:2]',
    'H2, Lindlar catalyst', '—', 'Stops at the cis alkene.',
    ['CC#C'], 'C=CC'),
  T('hydration', 'Hydration of an alkene (Markovnikov)', ['an alkene'],
    ['[CX3;D3:1]=[CX3;D1,D2:2]>>[C:1]([OH])[C:2]', '[CX3;D2:1]=[CX3;D1:2]>>[C:1]([OH])[C:2]'],
    'H3O+ (H2SO4 or H3PO4)', '—', 'OH goes to the more substituted carbon, H to the one with more hydrogens.',
    ['CC=C'], 'CC(C)O'),
  T('hydrohalogenation', 'Addition of HX to an alkene (Markovnikov)', ['an alkene', 'HBr, HCl or HI'],
    ['[CX3;D3:1]=[CX3;D1,D2:2].[Br,Cl,I;H1:3]>>[C:1]([*:3])[C:2]', '[CX3;D2:1]=[CX3;D1:2].[Br,Cl,I;H1:3]>>[C:1]([*:3])[C:2]'],
    'HBr (no peroxides)', '—', 'The halogen goes to the more substituted carbon (via the more stable carbocation).',
    ['CC=C', 'Br'], 'CC(C)Br'),
  T('halogen-addition', 'Addition of Br2 or Cl2 to an alkene', ['an alkene', 'Br2 or Cl2'],
    '[C:1]=[C:2].[Br,Cl:3][Br,Cl:4]>>[C:1]([*:3])[C:2][*:4]',
    'Br2, CH2Cl2', '—', 'Anti addition across the double bond (bromonium ion).',
    ['C=C', 'BrBr'], 'BrCCBr'),
  T('epoxidation', 'Epoxidation of an alkene', ['an alkene'],
    '[C;X3:1]=[C;X3:2]>>[C:1]1[O][C:2]1',
    'mCPBA, CH2Cl2', 'the carboxylic acid', 'The peracid delivers one oxygen atom to the double bond (syn).',
    ['C=C'], 'C1CO1'),
  T('sn2-hydroxide', 'SN2 with hydroxide: alkyl halide → alcohol', ['an alkyl halide', 'hydroxide'],
    '[CX4;!$(C(F)(F));!$(C=*):1][Cl,Br,I:2].[OH-:3]>>[C:1][O+0:3]',
    'NaOH, water / DMSO', 'the halide ion', 'Backside attack; best on methyl and primary halides.',
    ['CCBr', '[OH-]'], 'CCO'),
  T('williamson', 'Williamson ether synthesis', ['an alkyl halide', 'an alkoxide'],
    '[CX4;!$(C=*):1][Cl,Br,I:2].[CX4:5][OX1H0-:3]>>[C:1][O+0:3][C:5]',
    'NaOR, THF', 'the halide ion', 'SN2: use the less hindered halide.',
    ['CBr', 'CC[O-]'], 'CCOC'),
  T('sn2-cyanide', 'SN2 with cyanide: alkyl halide → nitrile', ['an alkyl halide', 'cyanide'],
    '[CX4;!$(C=*):1][Cl,Br,I:2].[C-:3]#[N:4]>>[C:1][C+0:3]#[N:4]',
    'NaCN, DMSO', 'the halide ion', 'Adds one carbon to the chain.',
    ['CCBr', '[C-]#N'], 'CCC#N'),
  T('amine-alkylation', 'SN2 with an amine: alkyl halide → amine', ['an alkyl halide', 'ammonia or an amine'],
    '[CX4;!$(C=*):1][Cl,Br,I:2].[NX3;H3,H2,H1;!$(NC=O):3]>>[C:1][N:3]',
    'excess amine', 'HX (as the ammonium salt)', 'Over-alkylation is a problem: use a large excess of the amine.',
    ['CBr', 'N'], 'CN'),
  T('e2', 'E2 elimination of an alkyl halide', ['an alkyl halide'],
    '[CX4;!H0:1][CX4:2][Cl,Br,I:3]>>[C:1]=[C:2]',
    'NaOEt, EtOH, heat (strong base)', 'HX', 'Removes H and X from adjacent carbons; several alkenes can form (Zaitsev: the most substituted wins).',
    ['CC(C)Br'], 'CC=C'),
  T('alcohol-dehydration', 'Dehydration of an alcohol', ['an alcohol'],
    '[CX4;!H0:1][CX4:2][OX2H1:3]>>[C:1]=[C:2]',
    'conc. H2SO4 or H3PO4, 170 °C', 'water', 'Acid-catalysed loss of water; the more substituted alkene predominates.',
    ['CCO'], 'C=C'),
  T('alcohol-to-halide', 'Alcohol + HX → alkyl halide', ['an alcohol', 'HBr, HCl or HI'],
    '[CX4;!$(C=*):1][OX2H1:2].[Br,Cl,I;H1:3]>>[C:1][*:3]',
    'conc. HBr (or PBr3, SOCl2)', 'water', 'Tertiary alcohols react by SN1 and primary ones by SN2.',
    ['CC(C)(C)O', 'Br'], 'CC(C)(C)Br'),
  T('grignard', 'Grignard addition to a carbonyl', ['an aldehyde or ketone', 'a Grignard reagent'],
    `${carbonyl(1)}=[O:2].[C:3][Mg:4][Br,Cl,I:5]>>[C:1]([C:3])[OH:2]`,
    'RMgX in dry ether, then H3O+', 'Mg(OH)X', 'The R group of the Grignard adds to the carbonyl carbon (formaldehyde → primary, other aldehydes → secondary, ketones → tertiary alcohol).',
    ['CC(C)=O', 'C[Mg]Br'], 'CC(C)(C)O'),
  T('aldol', 'Aldol addition', ['an aldehyde with an α-hydrogen', 'an aldehyde'],
    '[CX3H1:1](=[O:2])[CX4;!H0:3].[CX3H1:4]=[O:5]>>[C:1](=[O:2])[C:3][C:4][OH:5]',
    'NaOH (cat.), 5 °C', '—', 'The α-carbon of one aldehyde adds to the carbonyl carbon of another (give the aldehyde twice to react it with itself).',
    ['CC=O', 'CC=O'], 'CC(O)CC=O'),
  T('imine', 'Imine formation', ['an aldehyde or ketone', 'a primary amine'],
    `${carbonyl(1)}=[O:2].[NX3;H2:3][#6:4]>>[C:1]=[N:3][#6:4]`,
    'trace acid, remove water', 'water', 'C=O is replaced by C=N–R.',
    ['O=Cc1ccccc1', 'CN'], 'CN=Cc1ccccc1'),
  T('nitrile-hydrolysis', 'Hydrolysis of a nitrile', ['a nitrile'],
    '[#6:3][CX2:1]#[N:2]>>[#6:3][C:1](=O)[OH]',
    'H3O+, reflux', 'ammonium ion', 'R–C≡N becomes R–COOH.',
    ['CC#N'], 'CC(=O)O'),
  T('diels-alder', 'Diels–Alder cycloaddition', ['a conjugated diene', 'a dienophile (alkene)'],
    '[CX3:1]=[CX3:2][CX3:3]=[CX3:4].[CX3:5]=[CX3:6]>>[C:1]1[C:2]=[C:3][C:4][C:6][C:5]1',
    'heat', '—', 'A six-membered ring forms in one step: two new σ bonds, and the double bond moves between the diene\'s middle carbons.',
    ['C=CC=C', 'C=C'], 'C1=CCCCC1'),
  T('wittig', 'Wittig olefination', ['an aldehyde or ketone', 'a phosphorus ylide'],
    `${carbonyl(1)}=[O:2].[C:3]=[P:4]>>[C:1]=[C:3]`,
    'Ph3P=CHR, THF', 'triphenylphosphine oxide', 'C=O becomes C=C with the ylide carbon.',
    ['O=Cc1ccccc1', 'C=P(c1ccccc1)(c1ccccc1)c1ccccc1'], 'C=Cc1ccccc1'),
  T('nitration', 'Nitration of an arene', ['an aromatic compound'],
    '[cH:1]>>[c:1][N+](=O)[O-]',
    'HNO3 / H2SO4, 50 °C', 'water', 'Substitutes one ring hydrogen; every distinct position is listed (the directing effects of the substituent decide which dominates).',
    ['Cc1ccccc1'], 'Cc1ccccc1[N+](=O)[O-]'),
  T('arene-bromination', 'Bromination of an arene', ['an aromatic compound', 'Br2'],
    '[cH:1].[Br:2][Br:3]>>[c:1][Br:2]',
    'Br2, FeBr3', 'HBr', 'Electrophilic aromatic substitution of one ring hydrogen.',
    ['c1ccccc1', 'BrBr'], 'Brc1ccccc1'),
  T('sulfonation', 'Sulfonation of an arene', ['an aromatic compound'],
    '[cH:1]>>[c:1]S(=O)(=O)O',
    'fuming H2SO4', 'water', 'Reversible.',
    ['c1ccccc1'], 'O=S(=O)(O)c1ccccc1'),
  T('fc-alkylation', 'Friedel–Crafts alkylation', ['an aromatic compound', 'an alkyl halide'],
    '[cH:1].[CX4;!$(C=*):2][Cl,Br,I:3]>>[c:1][C:2]',
    'AlCl3', 'HX', 'The alkyl group replaces a ring hydrogen (rearrangements and polyalkylation are not predicted).',
    ['c1ccccc1', 'CC(C)Cl'], 'CC(C)c1ccccc1'),
  T('fc-acylation', 'Friedel–Crafts acylation', ['an aromatic compound', 'an acyl chloride'],
    '[cH:1].[#6:5][CX3:2](=[O:3])[Cl:4]>>[c:1][C:2](=[O:3])[#6:5]',
    'AlCl3 (> 1 equiv.)', 'HCl', 'Gives an aryl ketone; no rearrangement and no second acylation.',
    ['c1ccccc1', 'CC(=O)Cl'], 'CC(=O)c1ccccc1'),
  T('deprotonation', 'Carboxylic acid + base → carboxylate', ['a carboxylic acid'],
    '[CX3:1](=[O:2])[OX2H1:3]>>[C:1](=[O:2])[O-:3]',
    'NaOH or NaHCO3', 'water / CO2', 'The acidic O–H proton is removed (pKa about 5).',
    ['CC(=O)O'], 'CC(=O)[O-]'),
  T('thiol-oxidation', 'Oxidation of thiols to a disulfide', ['a thiol (twice, or two thiols)'],
    '[SX2H1:1][#6:2].[SX2H1:3][#6:4]>>[#6:2][S:1][S:3][#6:4]',
    'I2 or air', '2 H', 'The S–S bond of cystine in proteins forms this way.',
    ['CS', 'CS'], 'CSSC'),
]

export function findTemplate(id: string): Template | null {
  return TEMPLATES.find((t) => t.id === id) ?? null
}
